export interface Article { slug: string; title: string; kicker: string; minutes: number; intro: string; sections: Array<{ h: string; p: string }>; links: Array<{ label: string; to: string }>; coupleImage?: string }

export const ARTICLES: Article[] = [
  { slug: 'garba-night-outfit-formula', kicker: 'Garba', minutes: 5, title: 'The Garba Night Outfit Formula: Flare, Mirror, Move',
    intro: 'Nine nights, hours of dancing, and a hundred photos. Here is how to pick a chaniya choli that twirls well and survives the whole night.',
    sections: [
      { h: 'Start with flare', p: 'Look for 4–9 metre flare in cotton or rayon. It twirls well and still feels light. Heavy georgette gets hot fast on a crowded ground.' },
      { h: 'Mirror work is the light source', p: 'Garba grounds are lit by string lights and floodlights. Mirror work and gota pick that light up in photos, so one mirror-heavy piece is often enough.' },
      { h: 'Secure the dupatta', p: 'Cross-tie at the waist or pin at one shoulder so both hands are free for dandiya.' },
    ], links: [{ label: 'Shop Chaniya Choli', to: '/women/chaniya-choli' }, { label: 'Garba world', to: '/occasions/garba' }, { label: 'Garba couple looks', to: '/couple-edit?world=garba' }] },
  { slug: 'navratri-9-days-9-colours-young', kicker: 'Navratri', minutes: 6, title: 'Navratri Colours, Worn Young',
    intro: 'Follow the colour of the day without looking like a uniform. Keep one base and rotate the hero colour.',
    sections: [
      { h: 'One neutral base', p: 'A black or ivory skirt pairs with five different dupattas and crop tops.' },
      { h: 'Rotate the hero', p: 'Change the dupatta or blouse to match the day: rani pink, royal blue, emerald, mustard.' },
      { h: 'Oxidised silver ties it together', p: 'Oxidised jewellery works with every colour on the list.' },
    ], links: [{ label: 'Black chaniya cholis', to: '/search?q=black%20chaniya%20choli' }, { label: 'Jewellery', to: '/accessories?cat=jewellery' }] },
  { slug: 'mens-garba-without-costume', kicker: "Men's Festive Style", minutes: 5, title: "Men's Garba Style Without the Costume",
    intro: 'You do not need a full kediyu to look festive. Here is the modern formula.',
    sections: [
      { h: 'Kurta + statement stole', p: 'A white chikankari or black kurta with a bandhani, phulkari or paisley stole looks festive without feeling like a costume.' },
      { h: 'Printed ethnic shirts', p: 'Paisley and block-print shirts with relaxed trousers are easy to dance in and still read festive.' },
      { h: 'Keep mirror work selective', p: 'A mirror-sequin kurta in black-on-black is enough. Skip the rest.' },
    ], links: [{ label: 'Modern Kurtas', to: '/men/modern-kurta' }, { label: 'Traditional Layers', to: '/men/traditional-layer' }, { label: 'Men · Garba', to: '/search?q=garba%20men' }] },
  { slug: 'diwali-house-party-edit', kicker: 'Diwali', minutes: 4, title: 'The Diwali House-Party Edit',
    intro: 'Diya light is warm and low. Dress for it with soft gold, jewel tones and fabrics that catch light gently.',
    sections: [
      { h: 'Jewel tones win', p: 'Emerald, wine and royal blue look richest in candlelight.' },
      { h: 'Pre-draped for convenience', p: 'A pre-draped saree gives you the drape in two minutes and stays put through rangoli and sparklers.' },
      { h: 'Watch the dupatta near diyas', p: 'Keep synthetic dupattas pinned and away from open flames.' },
    ], links: [{ label: 'Diwali world', to: '/occasions/diwali' }, { label: 'Pre-Draped Sarees', to: '/women/pre-draped-saree' }] },
  { slug: 'college-fest-ethnic-day', kicker: 'College Fest', minutes: 4, title: 'Ethnic Day at College: Look Good From 9am to Concert Night',
    intro: 'Comfort first. You will walk, sit on steps and dance at the concert.',
    sections: [
      { h: 'Sharara and gharara', p: 'Easy to walk in, photogenic, and fine for sitting on amphitheatre steps.' },
      { h: 'Lightweight lehenga', p: 'Choose printed cotton or light georgette over heavy embroidery.' },
      { h: 'For him: shirt, not sherwani', p: 'A linen mandarin ethnic shirt or a short kurta is ideal.' },
    ], links: [{ label: 'College Fest world', to: '/occasions/college-fest' }, { label: 'Sharara', to: '/women/sharara' }, { label: 'Ethnic Shirts', to: '/men/ethnic-shirt' }] },
  { slug: 'womens-festive-silhouettes', kicker: "Women's Festive Style", minutes: 6, title: 'Chaniya, Lehenga, Sharara, Gharara: Which Silhouette When?',
    intro: 'A quick guide to the festive silhouettes on VIRAAS.',
    sections: [
      { h: 'Chaniya choli', p: 'Made for garba: short blouse, wide flare, usually cotton.' },
      { h: 'Lehenga', p: 'More structured, often silk or georgette. Works for Diwali and parties.' },
      { h: 'Sharara vs gharara', p: 'A sharara flares from the hip. A gharara is gathered at the knee.' },
    ], links: [{ label: 'Lehenga', to: '/women/lehenga' }, { label: 'Gharara', to: '/women/gharara' }] },
  { slug: 'saree-for-first-timers', kicker: 'Sarees', minutes: 5, title: 'Your First Festive Saree (Without Panic)',
    intro: 'Georgette and satin drape easily. Cotton holds pleats. Pre-draped removes the fear completely.',
    sections: [
      { h: 'Pick the fabric first', p: 'Georgette falls well and forgives beginner pleats.' },
      { h: 'Blouse makes it modern', p: 'Sleeveless, square-neck or bandeau-style blouses make a saree feel young.' },
      { h: 'Pin, pin, pin', p: 'Four safety pins: pallu, pleats, shoulder and waist.' },
    ], links: [{ label: 'Sarees', to: '/women/saree' }, { label: 'Pre-Draped Sarees', to: '/women/pre-draped-saree' }] },
  { slug: 'chaniya-choli-buying-guide', kicker: 'Chaniya Choli', minutes: 5, title: 'Chaniya Choli Buying Guide: Flare, Fabric, Fit',
    intro: 'What to check on the product page before you buy.',
    sections: [
      { h: 'Flare in metres', p: 'Look for the flare in metres in the listing. Around 6m twirls well.' },
      { h: 'Blouse type', p: 'Stitched, semi-stitched or unstitched. Pick stitched if Navratri starts this week.' },
      { h: 'Dupatta included?', p: 'Many listings include one. Check before you buy a separate one.' },
    ], links: [{ label: 'Chaniya Choli', to: '/women/chaniya-choli' }] },
  { slug: 'lehenga-under-2999', kicker: 'Lehenga', minutes: 4, title: 'Lehengas That Look Expensive (Under ₹2,999)',
    intro: 'Budget lehengas can look premium. It comes down to colour, fabric sheen and restraint.',
    sections: [
      { h: 'Solid + one detail', p: 'A solid skirt with a gota border photographs better than all-over cheap sequins.' },
      { h: 'Deep colours', p: 'Black, wine and emerald hide fabric shortcuts well.' },
      { h: 'Swap the dupatta', p: 'A contrast bandhani or phulkari dupatta instantly lifts the whole look.' },
    ], links: [{ label: 'Lehenga ₹1,999–₹2,999', to: '/women/lehenga?budget=1999-2999' }] },
  { slug: 'sharara-styling', kicker: 'Sharara', minutes: 3, title: 'Three Ways to Style a Sharara',
    intro: 'The easiest festive silhouette to wear, styled three ways.',
    sections: [
      { h: 'Campus', p: 'Cotton sharara, kolhapuris and oxidised jhumkas.' },
      { h: 'Diwali', p: 'Georgette with gota, a potli bag and embroidered juttis.' },
      { h: 'Party', p: 'Sequin sharara with block heels and a statement ring.' },
    ], links: [{ label: 'Sharara', to: '/women/sharara' }, { label: 'Accessories', to: '/accessories' }] },
  { slug: 'festive-accessories-that-matter', kicker: 'Accessories', minutes: 4, title: 'The Only Festive Accessories You Need',
    intro: 'Jhumkas, a choker, a bangle stack, a potli and juttis cover every festive occasion.',
    sections: [
      { h: 'Oxidised vs gold', p: 'Oxidised silver for Garba and college, gold for Diwali and Traditional.' },
      { h: 'Footwear for dancing', p: 'Flat mojaris or juttis. Keep heels for the party.' },
      { h: 'One statement piece', p: 'Wear either a statement necklace or statement earrings, not both.' },
    ], links: [{ label: 'Accessories', to: '/accessories' }] },
  { slug: 'festive-on-a-budget', kicker: 'Budget Fashion', minutes: 4, title: 'Festive on a Student Budget',
    intro: 'Build a festive season wardrobe for under ₹3,000 total.',
    sections: [
      { h: 'Buy a base', p: 'Buy one black or ivory skirt or kurta.' },
      { h: 'Rotate layers', p: 'Two dupattas and two blouses give you four looks.' },
      { h: 'Accessories under ₹499', p: 'Jhumkas and bangles change the whole feel of an outfit.' },
    ], links: [{ label: 'Under ₹999', to: '/trending?budget=under-999' }, { label: 'Under ₹499', to: '/accessories?budget=under-499' }] },
  { slug: 'office-festive-day', kicker: 'Office Festive', minutes: 3, title: 'Office Festive Day: Polished, Not Overdone',
    intro: 'Festive, but still work-appropriate.',
    sections: [
      { h: 'For her', p: 'A chikankari kurta set or a cotton saree with a contrast border.' },
      { h: 'For him', p: 'A linen mandarin kurta or a tonal-embroidered ethnic shirt.' },
      { h: 'Keep it quiet', p: 'Wear minimal jewellery and no heavy sequins before evening.' },
    ], links: [{ label: 'Kurta Sets', to: '/women/kurta-sets' }, { label: 'Ethnic Shirts', to: '/men/ethnic-shirt' }] },
  { slug: 'wedding-guest-young', kicker: 'Wedding Guest', minutes: 4, title: 'Young Wedding-Guest Styling (Not Bridal, Not Boring)',
    intro: 'Look festive without competing with the couple.',
    sections: [
      { h: 'Avoid bridal red', p: 'Choose wine, emerald, lilac or powder blue instead.' },
      { h: 'Sharara or pre-draped', p: 'Both are elegant and comfortable through a long ceremony.' },
      { h: 'For him', p: 'A festive jacket over a kurta is enough. You do not need a sherwani.' },
    ], links: [{ label: 'Festive Party world', to: '/occasions/festive-party' }, { label: 'Festive Jackets', to: '/men/festive-jacket' }] },
  { slug: 'traditional-worn-young', kicker: 'Traditional', minutes: 4, title: 'Traditional, Worn Young',
    intro: 'Handloom sarees, block prints and temple borders, styled for 2026.',
    sections: [
      { h: 'Modern blouse, classic saree', p: 'A cotton saree with a temple border and a sleeveless blouse.' },
      { h: 'Block prints for him', p: 'An indigo block-print kurta with white pyjama.' },
      { h: 'Temple visits', p: 'Comfortable cotton, flat juttis and minimal jewellery.' },
    ], links: [{ label: 'Traditional world', to: '/occasions/traditional' }] },
  { slug: 'couple-twinning-without-matching', kicker: 'Couple Edit', minutes: 5, title: 'Twinning Without Matching: The Couple Colour Rule',
    intro: 'The best couple looks share one colour, not the whole outfit.',
    sections: [
      { h: 'Share an accent', p: 'Her rani pink lehenga plus his red phulkari dupatta over white.' },
      { h: 'Share a neutral', p: 'Black brocade and a black kurta, each with a different accent.' },
      { h: 'Share a texture', p: 'Her mirror work, his mirror-sequin kurta.' },
    ], links: [{ label: 'Couple Edit', to: '/couple-edit' }] },
];
