// Per-look "Get Outfit Details" values (9 fields) for MEN 210 + WOMEN 236.
// Generated by scripts/build-look-details.mjs from each look's locked outfit definition
// + the hand-recorded visual overlay (scripts/gen-visual-overlay.mjs). Individually matched
// per look; honest fallbacks where a field is genuinely not determinable from the reference.
import menRaw from '../data/men-look-details.json';
import womenRaw from '../data/women-look-details.json';

export interface LookDetail {
  garment: string;
  colour: string;
  pattern: string;
  layering: string;
  bottomwear: string;
  footwear: string;
  accessories: string;
  poseFraming: string;
  settingLight: string;
}

const MEN_DETAILS = menRaw as Record<string, LookDetail>;
const WOMEN_DETAILS = womenRaw as Record<string, LookDetail>;

export const menLookDetail = (id: string): LookDetail | undefined => MEN_DETAILS[id];
export const womenLookDetail = (id: string): LookDetail | undefined => WOMEN_DETAILS[id];

export const DETAIL_FIELDS: { key: keyof LookDetail; label: string }[] = [
  { key: 'garment', label: 'Garment' },
  { key: 'colour', label: 'Colour' },
  { key: 'pattern', label: 'Pattern' },
  { key: 'layering', label: 'Layering' },
  { key: 'bottomwear', label: 'Bottomwear' },
  { key: 'footwear', label: 'Footwear' },
  { key: 'accessories', label: 'Accessories' },
  { key: 'poseFraming', label: 'Pose / framing' },
  { key: 'settingLight', label: 'Setting / light' },
];
