// The 54 TRENDING-ONLY editorial looks (TREND-447 … TREND-500) that complete the 500-look Trending
// target: 236 Women catalog looks + 210 Men catalog looks + 54 editorial looks.
//
// These records are separate from — and never overwrite — the product catalog, the Women/Men look
// catalogs or the workbook mappings. Generated by `scripts/build-trending-editorial.mjs`.
import raw from '../data/trending-editorial.client.json';

export interface TrendingEditorialLook {
  id: string;
  source: string;
  recordType: string;
  gender: 'men' | 'women';
  occasion: string[];
  occasionLabel: string;
  category: string;
  colour: string;
  title: string;
  description: string;
  styleTags: string[];
  /** Agreed upload target for the look image. Not a live URL until the asset is uploaded. */
  assetPath: string;
  imageStatus: 'pending-upload' | 'uploaded';
  imageSupplied: boolean;
  price: number | null;
  priceType: string | null;
  merchant: string | null;
  affiliateUrl: string | null;
  tryOnEnabled: boolean;
  status: string;
}

export const TRENDING_EDITORIAL_LOOKS = raw as unknown as TrendingEditorialLook[];
export const trendingEditorialById = new Map<string, TrendingEditorialLook>(
  TRENDING_EDITORIAL_LOOKS.map((look) => [look.id, look]),
);
/** Kept in one place so no page hardcodes the editorial count. */
export const TRENDING_EDITORIAL_TOTAL = TRENDING_EDITORIAL_LOOKS.length;
/** Editorial looks whose image has actually been uploaded. */
export const TRENDING_EDITORIAL_WITH_IMAGE = TRENDING_EDITORIAL_LOOKS.filter((look) => look.imageStatus === 'uploaded').length;
/** Editorial looks still awaiting their supplied image (reported honestly in the UI). */
export const TRENDING_EDITORIAL_PENDING_IMAGE = TRENDING_EDITORIAL_LOOKS.length - TRENDING_EDITORIAL_WITH_IMAGE;

/**
 * Editorial look image — only when the asset really exists. Returning `undefined` while the image
 * is pending makes `ImageFrame` render its labelled "Coming soon" state instead of a broken URL.
 */
export const trendingEditorialImage = (id: string): string | undefined => {
  const look = trendingEditorialById.get(id);
  return look && look.imageStatus === 'uploaded' && look.imageSupplied ? look.assetPath : undefined;
};
