import { Link, useParams, useSearchParams } from 'react-router-dom';
import { WOMEN_LOOKS, womenLookById, womenOccasionLabel, womenOccasions, type WomenLook } from '../lib/womenCatalog';
import { ImageFrame } from '../components/ui';
import womenPreviews from '../data/women-previews.client.json';
type WomenPreview = { qaStatus: string; approval: string; live: boolean; referenceId: string; src: string };
const previewStatus = womenPreviews as Record<string, WomenPreview | undefined>;
const previewSrc = (id: string) => { const s = previewStatus[id]; return s?.live && s.src ? s.src : undefined; };
export const WOMEN_LIVE_COUNT = Object.values(previewStatus).filter((s) => s?.live).length;
function Card({ look }: { look: WomenLook }) { return <article className="men-look-card women-look-card" data-women-look-id={look.id}>
  <Link to={`/women-look/${look.id}`} className="men-look-image"><ImageFrame src={previewSrc(look.id)} alt={`${look.id} reference ${look.referenceId}`} label={`Look ${look.id.replace('women-look-', '')}`} detail={`Reference ${look.referenceId} · image pending QA`} /></Link>
  <div className="men-look-body"><div className="kicker">{womenOccasionLabel(look.occasion)}</div><Link to={`/women-look/${look.id}`} className="men-look-title">Look {look.id.replace('women-look-', '')}</Link><p>{look.outfitDescription.split('. Picked')[0]}.</p><div className="men-look-meta"><span>{look.garmentType}</span><span>{look.colors.primary}</span></div><div className="men-look-actions">{previewSrc(look.id) && <Link className="btn btn-ghost sm" to={`/try-on?womenLook=${look.id}`}>Try On</Link>}<Link to={`/women-look/${look.id}`} className="link-arrow">View outfit details →</Link></div></div>
</article>; }
export default function WomenCatalog() { const { category }=useParams(); const [params,setParams]=useSearchParams(); const q=params.get('q')?.trim().toLowerCase()??''; const occasion=category||params.get('occasion')||''; const list=WOMEN_LOOKS.filter(x=>(!occasion||x.occasion===occasion)&&(!q||`${x.id} ${x.referenceId} ${x.outfitDescription} ${x.garmentType} ${x.colors.primary} ${x.patternOrEmbroidery?.embroidery}`.toLowerCase().includes(q))); return <div className="page men-catalog women-catalog"><div className="page-head"><div className="crumbs"><Link to="/">Home</Link> / <Link to="/women">Women</Link>{occasion&&<> / {womenOccasionLabel(occasion)}</>}</div><div className="kicker">The Women edit · 236 reference-driven looks</div><h1>{occasion?womenOccasionLabel(occasion):'Women'}</h1><p className="muted">Every look is mapped to one supplied reference panel. {WOMEN_LIVE_COUNT} of 236 QA-approved images are now live; the remaining {236 - WOMEN_LIVE_COUNT} keep a labelled placeholder until they pass visual QA.</p></div><div className="men-catalog-toolbar"><div className="men-occasion-tabs"><Link className={!occasion?'active':''} to="/women">All · 236</Link>{womenOccasions.map(o=><Link key={o.slug} className={occasion===o.slug?'active':''} to={`/women/${o.slug}`}>{o.label} <span>{o.range}</span></Link>)}</div><input value={q} onChange={e=>{const n=new URLSearchParams(params),v=e.target.value;if(v)n.set('q',v);else n.delete('q');setParams(n,{replace:true})}} placeholder="Search look ID, reference or outfit detail" aria-label="Search Women looks" /></div><div className="men-catalog-summary"><strong>{list.length}</strong> of 236 looks · {WOMEN_LIVE_COUNT} approved images live · canonical mappings unchanged</div>{list.length?<div className="men-look-grid">{list.map(x=><Card key={x.id} look={x}/>)}</div>:<div className="empty"><h3>No Women looks match</h3><Link className="btn btn-dark" to="/women">Clear filters</Link></div>}</div>; }
export function WomenLookDetail(){const {id}=useParams();const x=id?womenLookById.get(id):undefined;if(!x)return <div className="page"><div className="empty"><h3>Women look not found</h3><Link className="btn btn-dark" to="/women">Back to Women</Link></div></div>;return <div className="page men-detail"><div className="crumbs"><Link to="/">Home</Link> / <Link to="/women">Women</Link> / {x.id}</div><div className="men-detail-grid"><ImageFrame src={previewSrc(x.id)} alt={`${x.id} reference ${x.referenceId}`} label={`Look ${x.id.replace('women-look-','')}`} detail={`Reference ${x.referenceId} · image pending QA`} ratio="3 / 4"/><div><div className="kicker">{womenOccasionLabel(x.occasion)} · {x.referenceId}</div><h1>Look {x.id.replace('women-look-','')}</h1><p className="men-detail-lead">{x.outfitDescription}</p><dl className="specs"><div><dt>Garment</dt><dd>{x.garmentType??'Not recorded'}</dd></div><div><dt>Colour</dt><dd>{x.colors.primary??'Not recorded'}{x.colors.secondary?.length?` · ${x.colors.secondary.join(', ')}`:''}</dd></div><div><dt>Pattern</dt><dd>{x.patternOrEmbroidery?.pattern??'Not recorded'} · {x.patternOrEmbroidery?.embroidery??'Not recorded'}</dd></div><div><dt>Layering</dt><dd>{x.layering??'Not recorded'}</dd></div><div><dt>Bottomwear</dt><dd>{x.bottomwear??'Not recorded'}</dd></div><div><dt>Footwear</dt><dd>{x.footwear??'Not recorded'}</dd></div><div><dt>Accessories</dt><dd>{x.accessories??'Not recorded'}</dd></div><div><dt>Pose / framing</dt><dd>{x.pose??'Not recorded'} · {x.framing??'Not recorded'}</dd></div><div><dt>Setting / light</dt><dd>{x.environment??'Not recorded'} · {x.lighting??'Not recorded'}</dd></div></dl>{previewSrc(x.id) ? <p className="placeholder-callout">QA-approved VIRAAS preview image · matched to reference {x.referenceId}. Generated original, non-production preview.</p> : <p className="placeholder-callout">Image pending QA · this reserved frame will show the approved image once it passes visual QA.</p>}<div className="row">{previewSrc(x.id) && <Link className="btn btn-accent" to={`/try-on?womenLook=${x.id}`}>Try this on</Link>}<Link className="btn btn-dark" to={`/women/${x.occasion}`}>Browse {womenOccasionLabel(x.occasion)}</Link></div></div></div></div>;}
