// 100 VIRAAS couple looks — exactly 20 per public world.
// Each look is anchored to a supplied reference (REF-C1..C3 individual screenshots, REF-S1/S2 sheet panels)
// and records the outfit + pose + framing language to recreate. `her`/`him` drive the linked products,
// so the couple image and the linked catalog products always describe the same garments.
//
// Fields: id, world, title, ref, pose, framing, setting, light, her{cat,colour,fabric,detail,desc},
//         him{cat,colour,fabric,detail,desc}, layer (optional men's stole/dupatta), tone (jewellery metal),
//         colourStory, tags

const H = (cat, colour, fabric, detail, desc) => ({ cat, colour, fabric, detail, desc });

export const WORLDS = [
  { slug: 'garba', name: 'Garba', long: 'Garba / Navratri', blurb: 'Nine nights of mirror work, bandhani and twirl-ready flare.' },
  { slug: 'college-fest', name: 'College Fest', long: 'College Fest', blurb: 'Light, move-all-day festive looks for campus ethnic day.' },
  { slug: 'diwali', name: 'Diwali', long: 'Diwali', blurb: 'Diya-lit silks, soft gold and house-party ready drapes.' },
  { slug: 'festive-party', name: 'Festive Party', long: 'Festive Party', blurb: 'After-dark sequins, jewel tones and black-on-black.' },
  { slug: 'traditional', name: 'Traditional', long: 'Traditional', blurb: 'Handloom, temple borders and heirloom-inspired styling — worn young.' },
];

export const COUPLES = [
  // ───────────── GARBA / NAVRATRI (priority 1) ─────────────
  { id: 'garba-01', world: 'garba', title: 'Rani Pink Fitting-Room Mirror Check', ref: 'REF-C1',
    pose: 'standing mirror selfie; she holds the phone over part of her face with her other hand on her cheek; he stands close behind her shoulder with an arm around her waist',
    framing: 'vertical 3/4-length mirror reflection', setting: 'clothing store fitting area with garment racks', light: 'cool fluorescent store light',
    her: H('Lehenga', 'Rani Pink', 'Silk Blend', 'gota border dupatta', 'rani pink flared silk lehenga skirt with a white strapless embroidered bandeau top and a rani pink gota-border dupatta with tassels'),
    him: H('Festive Kurta Set', 'White', 'Cotton', 'solid', 'plain white cotton kurta pyjama set'),
    layer: H('Traditional Layer', 'Red', 'Cotton', 'phulkari embroidery', 'rani red phulkari dupatta with multicolour floral embroidery and tassels'),
    tone: 'Oxidised Silver', colourStory: 'Rani pink · White · Phulkari red', tags: ['mirror-selfie', 'twinning'] },
  { id: 'garba-02', world: 'garba', title: 'Black Brocade Overhead Outfit Check', ref: 'REF-C2',
    pose: 'both lying side by side on the ground, bodies angled diagonally; her hand rests on her hair, his hands clasped at chest',
    framing: 'directly overhead top-down, full body', setting: 'sunlit grey concrete', light: 'hard afternoon sun with crisp shadows',
    her: H('Lehenga', 'Black', 'Brocade', 'gold-teal paisley brocade', 'black flared lehenga with gold and teal brocade paisley motifs and a fitted white long-sleeve crop top'),
    him: H('Modern Kurta', 'Black', 'Cotton Silk', 'copper thread placket embroidery', 'black kurta with copper-brown thread embroidery on the neckline placket'),
    layer: H('Traditional Layer', 'Ivory', 'Cotton', 'paisley block print', 'ivory paisley block-printed stole with black border'),
    tone: 'Oxidised Silver', colourStory: 'Black · White · Ivory paisley', tags: ['overhead', 'twinning'] },
  { id: 'garba-03', world: 'garba', title: 'Ivory Mirror-Work on the Diya Steps', ref: 'REF-C3',
    pose: 'seated close on stone steps; she takes a phone photo leaning into him; his forearm rests on his knee, head tilted to her',
    framing: 'vertical, full seated bodies', setting: 'old stone steps beside a carved pillar with lit diyas', light: 'warm golden hour',
    her: H('Lehenga', 'Ivory', 'Georgette', 'mirror work embellishment', 'ivory lehenga densely covered in round mirror work with a sleeveless embellished crop blouse and sheer ivory dupatta'),
    him: H('Modern Kurta', 'White', 'Cotton', 'chikankari', 'white chikankari kurta worn with blue denim'),
    tone: 'Silver', colourStory: 'Ivory · White · Denim', tags: ['seated', 'golden-hour'] },
  { id: 'garba-04', world: 'garba', title: 'Red Backless Choli, Face-Cup Laugh', ref: 'REF-C2 side panel',
    pose: 'she, seen from behind at three-quarter, cups his face with both hands; he laughs',
    framing: 'vertical waist-up', setting: 'outdoor navratri venue with string lights and trees', light: 'night ambient light',
    her: H('Chaniya Choli', 'Red', 'Cotton', 'kutchi embroidered backless blouse', 'red chaniya choli with a multicolour kutchi-embroidered tie-up backless blouse and red dupatta'),
    him: H('Festive Kurta Set', 'White', 'Cotton', 'solid', 'white cotton kurta set'),
    layer: H('Traditional Layer', 'Red', 'Cotton', 'bandhani print', 'long red bandhani dupatta'),
    tone: 'Oxidised Silver', colourStory: 'Red · White · Multicolour kutch', tags: ['night', 'candid'] },
  { id: 'garba-05', world: 'garba', title: 'Pink Bandhani Hand-Hold on the Lawn', ref: 'REF-C1 side panel',
    pose: 'standing side by side holding hands between them; chest-down crop focusing on outfits',
    framing: 'vertical chest-to-feet crop', setting: 'evening garba ground lawn', light: 'soft dusk light',
    her: H('Chaniya Choli', 'Rani Pink', 'Cotton', 'bandhani print with mirror hem', 'rani pink bandhani flared chaniya with a mirror-work hem, white blouse and sheer white lace-edged dupatta'),
    him: H('Modern Kurta', 'White', 'Cotton', 'chikankari sequin', 'white chikankari kurta with fine sequins and white pyjama'),
    tone: 'Silver', colourStory: 'Rani pink bandhani · White', tags: ['hand-hold', 'detail-crop'] },
  { id: 'garba-06', world: 'garba', title: 'Red & Ivory Shoulder-to-Shoulder', ref: 'REF-C1 side panel',
    pose: 'standing shoulder to shoulder, her bangled arm resting against him; nose-to-knee crop',
    framing: 'vertical nose-to-knee crop', setting: 'plain cream indoor wall', light: 'warm indoor light',
    her: H('Lehenga', 'Red', 'Silk', 'gold border', 'red silk lehenga with gold-border dupatta and ivory embroidered blouse'),
    him: H('Festive Kurta Set', 'Ivory', 'Cotton', 'self stripe', 'ivory self-stripe cotton kurta pyjama set with sheer white dupatta'),
    tone: 'Silver', colourStory: 'Red · Ivory', tags: ['outfit-check'] },
  { id: 'garba-07', world: 'garba', title: 'Patchwork Walk Into the Canopy', ref: 'REF-S1 panel 2/10',
    pose: 'walking hand in hand away from camera into the crowd, three-quarter back view',
    framing: 'vertical full body from behind', setting: 'crowded garba ground under striped canopy and string lights', light: 'night festival light',
    her: H('Chaniya Choli', 'Multicolour', 'Cotton', 'patchwork with mirror work', 'multicolour patchwork flared chaniya choli in pink, orange, yellow and green with mirror work and a backless tie-up blouse'),
    him: H('Festive Kurta Set', 'Black', 'Cotton', 'solid', 'black kurta and black pants'),
    layer: H('Traditional Layer', 'Red', 'Cotton', 'bandhani print', 'red bandhani dupatta over one shoulder'),
    tone: 'Oxidised Silver', colourStory: 'Multicolour patchwork · Black · Red', tags: ['walking', 'back-view'] },
  { id: 'garba-08', world: 'garba', title: 'Black Patola Dandiya Face-Off', ref: 'REF-S1 panel 5',
    pose: 'facing each other mid-dandiya, sticks crossed between them, both laughing',
    framing: 'vertical full body', setting: 'night garba ground with dancers', light: 'festival lights',
    her: H('Chaniya Choli', 'Black', 'Rayon', 'gold lampi border with patola dupatta', 'black chaniya with gold border, black long-sleeve crop top and multicolour patola dupatta with tassels'),
    him: H('Ethnic Shirt', 'Navy', 'Cotton', 'small embroidered motifs', 'navy short kurta-shirt with small white embroidered motifs and cream pants'),
    tone: 'Oxidised Silver', colourStory: 'Black · Patola multicolour · Navy', tags: ['dandiya', 'playful'] },
  { id: 'garba-09', world: 'garba', title: 'Kutchi Halter, Dupatta Fix', ref: 'REF-S1 panel 6',
    pose: 'he gently adjusts the dupatta on her shoulder; she looks down smiling',
    framing: 'vertical waist-up', setting: 'evening path beside a garba venue', light: 'warm bokeh light',
    her: H('Chaniya Choli', 'White', 'Cotton', 'kutchi mirror halter', 'white chaniya with kutchi mirror-embroidered halter blouse and multicolour patchwork tasselled dupatta'),
    him: H('Modern Kurta', 'White', 'Cotton', 'chikankari', 'white chikankari kurta'),
    layer: H('Traditional Layer', 'Navy', 'Georgette', 'sequin scatter', 'navy sequin-scattered stole'),
    tone: 'Oxidised Silver', colourStory: 'White · Kutch multicolour · Navy sequin', tags: ['dupatta-adjust'] },
  { id: 'garba-10', world: 'garba', title: 'Red Flare Twirl Under the Floodlights', ref: 'REF-S1 panel 8 / REF-S2 panel 16',
    pose: 'she twirls mid-spin while he holds her hand above her head guiding the twirl',
    framing: 'vertical full body', setting: 'grass garba field with floodlights and bunting', light: 'night floodlight',
    her: H('Chaniya Choli', 'Red', 'Cotton', 'kutchi mirror crop top', 'wide red flared chaniya with black kutchi mirror crop top and red-black bandhani dupatta'),
    him: H('Festive Kurta Set', 'Ivory', 'Cotton', 'solid', 'ivory kurta pyjama set'),
    layer: H('Traditional Layer', 'Red', 'Cotton', 'bandhani print', 'red bandhani dupatta'),
    tone: 'Oxidised Silver', colourStory: 'Red · Black kutch · Ivory', tags: ['twirl', 'motion'] },
  { id: 'garba-11', world: 'garba', title: 'Royal Blue Cheek-to-Cheek Selfie', ref: 'REF-S2 panel 11/19',
    pose: 'arm-length selfie taken by him, cheek to cheek, both grinning', framing: 'vertical head-and-shoulders', setting: 'night garba ground bokeh', light: 'slight phone-flash night',
    her: H('Chaniya Choli', 'Royal Blue', 'Cotton', 'mirror work', 'royal blue mirror-work chaniya choli with red bandhani dupatta loosely over her head'),
    him: H('Festive Kurta Set', 'White', 'Cotton', 'solid', 'white kurta set'),
    layer: H('Traditional Layer', 'Red', 'Cotton', 'solid', 'red cotton dupatta around the neck'),
    tone: 'Oxidised Silver', colourStory: 'Royal blue · Red · White', tags: ['selfie'] },
  { id: 'garba-12', world: 'garba', title: 'Mustard Mirror Mat-Side Laughs', ref: 'REF-S2 panel 20',
    pose: 'seated on a mat on the ground laughing, her head on his shoulder', framing: 'vertical full seated', setting: 'garba venue edge with fairy lights', light: 'warm night',
    her: H('Chaniya Choli', 'Mustard', 'Cotton', 'red mirror border', 'mustard chaniya choli with red mirror-work border, red embroidered blouse and green bandhani dupatta'),
    him: H('Printed Ethnic Shirt', 'Olive', 'Rayon', 'botanical print', 'olive printed ethnic shirt with ivory trousers'),
    tone: 'Oxidised Silver', colourStory: 'Mustard · Red · Olive', tags: ['seated', 'candid'] },
  { id: 'garba-13', world: 'garba', title: 'Black Sequin Stage-Glow Embrace', ref: 'REF-S2 panel 13',
    pose: 'gentle embrace, her head on his chest, eyes closed', framing: 'vertical waist-up', setting: 'near a garba stage', light: 'orange-red stage glow',
    her: H('Chaniya Choli', 'Rust', 'Rayon', 'mirror work', 'rust-ochre and red mirror-work chaniya choli with black bandhani dupatta'),
    him: H('Modern Kurta', 'Black', 'Georgette', 'mirror sequin', 'black mirror-sequin kurta'),
    tone: 'Oxidised Silver', colourStory: 'Rust · Black', tags: ['embrace', 'night'] },
  { id: 'garba-14', world: 'garba', title: 'Emerald Lift Mirror Selfie', ref: 'REF-S2 panel 14',
    pose: 'mirror selfie inside a steel lift; she holds the phone, he rests his chin on her head', framing: 'vertical full body mirror', setting: 'steel elevator interior', light: 'cool overhead lift light',
    her: H('Chaniya Choli', 'Emerald', 'Cotton', 'gamthi print with mirror', 'emerald gamthi-print chaniya choli with mirror blouse and magenta dupatta'),
    him: H('Ethnic Shirt', 'Ivory', 'Cotton', 'tonal embroidery', 'ivory ethnic shirt with tonal embroidery and emerald trousers'),
    tone: 'Oxidised Silver', colourStory: 'Emerald · Magenta · Ivory', tags: ['mirror-selfie'] },
  { id: 'garba-15', world: 'garba', title: 'Black-on-Black Fairy Light Bench', ref: 'REF-S2 panel 15',
    pose: 'seated on a bench, knees touching, he whispers, she laughs looking away', framing: 'vertical full seated', setting: 'bench under fairy lights', light: 'fairy-light glow',
    her: H('Chaniya Choli', 'Black', 'Rayon', 'black mirror work', 'black chaniya choli with black embroidered crop blouse and black mirror-dot dupatta'),
    him: H('Festive Kurta Set', 'Black', 'Cotton Silk', 'tonal embroidery', 'black kurta set with tonal embroidery'),
    layer: H('Traditional Layer', 'Black', 'Cotton', 'gold paisley', 'black and gold paisley shawl'),
    tone: 'Oxidised Silver', colourStory: 'Black-on-black · Gold', tags: ['seated', 'black-on-black'] },
  { id: 'garba-16', world: 'garba', title: 'Wine Lehenga Twirl, Hand in Hand', ref: 'REF-S2 panel 16',
    pose: 'both spinning together holding both hands, leaning back', framing: 'vertical full body', setting: 'night garba field', light: 'floodlights',
    her: H('Lehenga', 'Wine', 'Cotton Silk', 'kutch embroidery', 'wine lehenga with kutch-embroidered blouse'),
    him: H('Modern Kurta', 'Cream', 'Cotton', 'embroidered placket', 'cream kurta with embroidered placket'),
    layer: H('Traditional Layer', 'Wine', 'Cotton', 'bandhani print', 'wine bandhani stole'),
    tone: 'Oxidised Silver', colourStory: 'Wine · Cream', tags: ['twirl'] },
  { id: 'garba-17', world: 'garba', title: 'Blue Bandhani Festive-Lights Hug', ref: 'REF-S2 panel 17',
    pose: 'side hug facing camera, she tucks under his arm, both laughing', framing: 'vertical 3/4', setting: 'lit garba entrance arch', light: 'festive lights',
    her: H('Chaniya Choli', 'Navy', 'Cotton', 'bandhani print', 'navy bandhani chaniya choli with red mirror blouse'),
    him: H('Printed Ethnic Shirt', 'White', 'Cotton', 'indigo block print', 'white shirt with indigo block print'),
    tone: 'Oxidised Silver', colourStory: 'Navy bandhani · Red · Indigo', tags: ['hug'] },
  { id: 'garba-18', world: 'garba', title: 'Ivory Twirl, Navy Kurta Watch', ref: 'REF-S2 panel 18',
    pose: 'she twirls in the foreground, he watches smiling behind', framing: 'vertical full body', setting: 'garba courtyard', light: 'night warm',
    her: H('Chaniya Choli', 'Ivory', 'Cotton', 'multicolour embroidered border', 'ivory chaniya with multicolour embroidered border and kutch balloon-sleeve blouse'),
    him: H('Modern Kurta', 'Navy', 'Cotton', 'embroidered yoke', 'navy kurta with embroidered yoke'),
    tone: 'Oxidised Silver', colourStory: 'Ivory · Multicolour · Navy', tags: ['twirl'] },
  { id: 'garba-19', world: 'garba', title: 'Maroon Mirror Kurta, Ground Walk', ref: 'REF-S1 panel 4',
    pose: 'walking toward camera side by side, fingers linked, mid-laugh', framing: 'vertical full body', setting: 'garba ground walkway', light: 'dusk',
    her: H('Chaniya Choli', 'Maroon', 'Cotton', 'gota and mirror', 'maroon chaniya with gota and mirror work and mustard dupatta'),
    him: H('Modern Kurta', 'Maroon', 'Cotton', 'mirror work', 'maroon mirror-work kurta with ivory pants'),
    tone: 'Oxidised Silver', colourStory: 'Maroon · Mustard · Ivory', tags: ['walking'] },
  { id: 'garba-20', world: 'garba', title: 'Pink Pair Forehead Touch', ref: 'REF-S1 panel 6',
    pose: 'foreheads touching, eyes closed, dandiya sticks held together', framing: 'vertical waist-up', setting: 'garba ground night', light: 'soft night',
    her: H('Chaniya Choli', 'Hot Pink', 'Cotton', 'mirror work', 'hot pink mirror-work chaniya choli with white blouse'),
    him: H('Modern Kurta', 'White', 'Cotton', 'solid', 'white kurta'),
    layer: H('Traditional Layer', 'Pink', 'Cotton', 'bandhani print', 'pink bandhani scarf'),
    tone: 'Oxidised Silver', colourStory: 'Hot pink · White', tags: ['close'] },

  // ───────────── COLLEGE FEST (priority 2) ─────────────
  { id: 'college-fest-01', world: 'college-fest', title: 'Black Kurta, Mirror Doorway', ref: 'LOOK-01',
    pose: 'standing very close together, she slightly in front and to the left, he slightly behind and to the right with his arm naturally around her shoulder, she stands relaxed with her handbag hanging from one hand, both looking toward the camera, casual affectionate not formal', framing: 'vertical full-body portrait, couple centred, entire outfits visible down to footwear', setting: 'dark reflective modern interior with a tall glass doorway behind them', light: 'night indoor lighting',
    her: H('Kurta Sets', 'Black', 'Cotton', 'white floral embroidery with palazzo', 'black long straight kurta with prominent white floral embroidery, white loose palazzo bottoms, statement silver layered necklace, long silver earrings, silver embellished small handbag, white embroidered flats'),
    him: H('Ethnic Shirt', 'Black', 'Cotton', 'solid full-sleeve', 'solid black full-sleeve button-up shirt, relaxed fit, white wide trousers, white sneakers, simple wristwatch'),
    tone: 'Silver', colourStory: 'Black · White', tags: ['standing','mirror-doorway'] },
  { id: 'college-fest-02', world: 'college-fest', title: 'Cream Printed Set on the Cafe Bench', ref: 'LOOK-02',
    pose: 'both seated together on a wooden bench, he on the left and she on the right, bodies slightly turned toward each other, looking at each other naturally in relaxed conversation, one arm resting naturally rather than posed', framing: 'vertical lifestyle portrait, full seated bodies and footwear visible, small round black cafe table in the left foreground', setting: 'indoor modern cafe lounge with plants and window elements behind', light: 'soft daylight',
    her: H('Kurta Sets', 'Ivory', 'Cotton', 'olive floral print with dupatta', 'cream printed kurta set with a delicate olive floral pattern, matching bottoms, a long flowing dupatta with a green printed border, white sneakers, light beige shoulder bag'),
    him: H('Ethnic Shirt', 'Olive', 'Cotton', 'solid full-sleeve', 'dark olive casual full-sleeve button-up shirt, relaxed fit, off-white loose trousers, white sneakers, wristwatch'),
    tone: 'Silver', colourStory: 'Cream · Olive', tags: ['seated','cafe'] },
  { id: 'college-fest-03', world: 'college-fest', title: 'Ivory Mirror Lehenga, Steps Selfie', ref: 'LOOK-03',
    pose: 'both seated very close together on stone steps, she slightly forward holding a smartphone up in front of her face like a selfie with the phone partially obscuring her face, he leaning closely toward her face, heads close together', framing: 'vertical close lifestyle portrait, camera slightly close to the subjects', setting: 'stone haveli steps with diyas and soft festive lights around, warm beige environment', light: 'warm golden evening lighting',
    her: H('Lehenga', 'Ivory', 'Georgette', 'mirror-work blouse', 'ivory heavily mirror-work and sequin lehenga with a matching embellished blouse with thin shoulder straps, ivory dupatta, traditional silver bangles, large silver jhumka earrings'),
    him: H('Modern Kurta', 'Cream', 'Cotton', 'embroidered', 'cream embroidered kurta with light blue relaxed jeans, wristwatch, dark footwear'),
    tone: 'Silver', colourStory: 'Ivory · Cream', tags: ['seated','selfie'] },
  { id: 'college-fest-04', world: 'college-fest', title: 'Wine Dress and Floral Blazer', ref: 'LOOK-04',
    pose: 'standing very close, she on the left slightly leaning toward him, he on the right looking down toward her, both looking at each other rather than the camera, his arm naturally behind and around her', framing: 'vertical full-body portrait', setting: 'warm indoor evening setting with a curtain background strung with warm fairy lights and a dark elegant floor', light: 'soft cinematic lighting',
    her: H('Lehenga', 'Wine', 'Georgette', 'gold border', 'deep wine floor-length festive lehenga with a sleeveless spaghetti-strap bodice, long flowing skirt, decorative gold traditional border near the lower edge and on the dupatta, minimal elegant jewellery'),
    him: H('Festive Jacket', 'Black', 'Cotton Blend', 'burgundy floral pattern', 'solid black shirt and black trousers with black shoes worn under a black and burgundy floral patterned tailored blazer with a dense muted paisley pattern'),
    tone: 'Gold', colourStory: 'Wine · Black', tags: ['standing','evening'] },
  { id: 'college-fest-05', world: 'college-fest', title: 'Overhead Walk, Arm Linked', ref: 'LOOK-05',
    pose: 'top-down overhead photograph with the camera looking almost directly down, couple walking closely together with her arm looped around his arm, bodies seen from above, both looking naturally downward, legs and footwear visible', framing: 'vertical overhead composition with the concrete outdoor walkway visible underneath', setting: 'outdoor stone walkway', light: 'natural daylight',
    her: H('Kurta Sets', 'Ivory', 'Cotton', 'navy block print with white dupatta', 'white printed kurta set with a blue and navy floral block-print pattern, matching light bottoms, white lightweight dupatta, small delicate necklace'),
    him: H('Ethnic Shirt', 'Navy', 'Cotton', 'solid', 'solid navy button-up shirt, relaxed fit, off-white trousers, white sneakers, dark wristwatch'),
    tone: 'Silver', colourStory: 'Ivory · Navy', tags: ['overhead','walking'] },
  { id: 'college-fest-06', world: 'college-fest', title: 'Close Crop, Maroon Dupatta Detail', ref: 'LOOK-06',
    pose: 'very close cropped couple portrait showing torso arms and hands more than faces, she holds and adjusts her deep red dupatta near her front, he stands immediately beside her, their bodies almost touching', framing: 'vertical close crop focused on garment details, dupatta border, embroidery and hand placement', setting: 'neutral indoor background', light: 'soft indoor light',
    her: H('Kurta Sets', 'Ivory', 'Silk Blend', 'gold floral embroidery with maroon dupatta', 'taupe champagne ethnic suit with heavy gold floral embroidery and a deep maroon dupatta with a prominent ornate gold embroidered border, mehendi visible on hands, gold jewellery'),
    him: H('Modern Kurta', 'Cream', 'Cotton', 'plain', 'plain cream kurta with a clean straight silhouette, minimal styling, no jacket'),
    tone: 'Gold', colourStory: 'Champagne · Maroon', tags: ['close-crop','detail'] },
  { id: 'college-fest-07', world: 'college-fest', title: 'Soft Pink Monochrome Close Crop', ref: 'LOOK-07',
    pose: 'extremely close couple crop with their upper torsos touching, he positioned beside and behind her, her arm across and around him, he holds a smartphone close to his body, faces partially cropped out', framing: 'vertical close-up cropped around the chest and waist area', setting: 'outdoor', light: 'natural daylight',
    her: H('Kurta Sets', 'Rani Pink', 'Cotton', 'white floral embroidery', 'soft pastel pink ethnic kurta with white floral embroidery on the sleeves and body, soft feminine silhouette, minimal jewellery'),
    him: H('Ethnic Shirt', 'Pink', 'Cotton', 'solid pastel', 'light pastel pink button-up shirt, relaxed casual fit, holding a smartphone, wristwatch'),
    tone: 'Silver', colourStory: 'Pink · Pink', tags: ['close-crop','monochrome'] },
  { id: 'college-fest-08', world: 'college-fest', title: 'White Outfit, Hot Pink Bandhani Dupatta', ref: 'LOOK-08',
    pose: 'standing side by side, she on the left holding and fanning her hot pink dupatta outward so it becomes the dominant visual element, he on the right standing relaxed with one hand near his pocket, framed from the shoulders through the legs', framing: 'vertical fashion lifestyle photograph', setting: 'outdoor with a green fence and plants behind', light: 'outdoor daylight',
    her: H('Kurta Sets', 'Ivory', 'Cotton', 'hot pink bandhani dupatta', 'white ethnic base outfit with a simple sleeveless inner, bright hot pink bandhani dupatta with a traditional dotted geometric print and gold trim, beige flat sandals'),
    him: H('Modern Kurta', 'White', 'Cotton', 'chikankari', 'white chikankari embroidered kurta with light blue relaxed jeans, white casual footwear, silver watch'),
    tone: 'Silver', colourStory: 'White · Hot Pink', tags: ['standing','bandhani'] },
  { id: 'college-fest-09', world: 'college-fest', title: 'Magenta Set on the Night Staircase', ref: 'LOOK-09',
    pose: 'standing together near a staircase, she close to his side and turning toward him, he raises one hand toward his hair, natural playful interaction, no formal posing', framing: 'vertical full to three-quarter portrait', setting: 'outdoor apartment staircase at night', light: 'night lighting with warm street and festive lights',
    her: H('Lehenga', 'Rani Pink', 'Georgette', 'white floral motifs', 'bright magenta festive lehenga with a patterned skirt carrying white floral motifs and a sheer flowing hot pink dupatta with a gold border'),
    him: H('Modern Kurta', 'Peach', 'Cotton', 'coral with cream ethnic layer', 'peach coral kurta with a white cream embroidered ethnic layer worn over it and a light cream lower garment'),
    tone: 'Gold', colourStory: 'Magenta · Peach', tags: ['staircase','night'] },
  { id: 'college-fest-10', world: 'college-fest', title: 'Sky Blue Suit, Foreheads Touching', ref: 'LOOK-10',
    pose: 'both seated on stairs, she on the left and he on the right, faces leaning very close toward each other with foreheads and cheeks almost touching, natural intimate eye contact, she holds a smartphone down near her lap', framing: 'vertical portrait with a close seated perspective', setting: 'stone indoor stairs', light: 'soft daylight',
    her: H('Kurta Sets', 'Powder Blue', 'Cotton', 'white embroidery', 'light sky blue embroidered ethnic suit with a matching light blue dupatta and white embroidery, traditional salwar styling'),
    him: H('Modern Kurta', 'Powder Blue', 'Cotton', 'embroidered', 'powder light blue embroidered kurta with white trousers in a matching pastel palette with traditional motifs'),
    tone: 'Silver', colourStory: 'Sky Blue · Sky Blue', tags: ['seated','intimate'] },
  { id: 'college-fest-11', world: 'college-fest', title: 'Ivory Anarkali on the Staircase', ref: 'LOOK-11',
    pose: 'seated on a staircase, she lower left and in front, he one or two steps above and to the right, she looking upward at him, he resting his elbow and hand near his face while looking at her, neither looking at the camera', framing: 'vertical lifestyle portrait with the staircase dominating the background', setting: 'indoor staircase', light: 'warm indoor light with a soft warm tone',
    her: H('Anarkali', 'Ivory', 'Georgette', 'floral embroidery', 'ivory embroidered festive anarkali with delicate floral embroidery and a matching sheer dupatta, minimal delicate jewellery'),
    him: H('Modern Kurta', 'White', 'Cotton', 'light embroidery', 'all white kurta pajama with light embroidered detailing, traditional silhouette'),
    tone: 'Silver', colourStory: 'Ivory · White', tags: ['seated','staircase'] },
  { id: 'college-fest-12', world: 'college-fest', title: 'Magenta Dupatta in the Heritage Lane', ref: 'LOOK-12',
    pose: 'both walking side by side in a heritage lane, she slightly ahead and to the left, he slightly behind and to the right, both looking downward naturally, relaxed walking movement with hands close to their bodies', framing: 'vertical full-body photograph', setting: 'old heritage village lane with cream walls and a wooden door', light: 'warm natural daylight',
    her: H('Lehenga', 'Wine', 'Silk Blend', 'gold embroidered dupatta', 'deep magenta ethnic lehenga with a cream printed lower portion, a rich decorative border and a large deep magenta dupatta with ornate gold embroidery'),
    him: H('Modern Kurta', 'Cream', 'Cotton', 'textured', 'cream kurta with a matching cream lower garment and a simple embroidered texture, white footwear'),
    tone: 'Gold', colourStory: 'Magenta · Cream', tags: ['walking','heritage'] },
  { id: 'college-fest-13', world: 'college-fest', title: 'White Lehenga, Navy Dupatta, Steps', ref: 'LOOK-13',
    pose: 'she stands in the foreground to the left with her back partly toward the camera and extends one arm forward and upward, he is seated crouched on the steps below her leaning forward and down, playful unequal-height pose', framing: 'vertical full-body asymmetrical composition', setting: 'night environment with a dark reflective wall and windows behind, staircase visible', light: 'night low light',
    her: H('Lehenga', 'Ivory', 'Georgette', 'navy floral dupatta', 'white long ethnic lehenga skirt with a flowing navy blue floral printed dupatta and a white embroidered blouse, traditional silver jewellery'),
    him: H('Modern Kurta', 'White', 'Cotton', 'embroidered', 'white embroidered kurta with white pajama trousers, minimal festive styling'),
    tone: 'Silver', colourStory: 'White · Navy', tags: ['asymmetric','steps'] },
  { id: 'college-fest-14', world: 'college-fest', title: 'Red Lehenga, Night Driveway', ref: 'LOOK-14',
    pose: 'standing outside at night with his arm around her shoulder, she standing close against him, both smiling and laughing naturally, he looking down toward her and she looking toward him', framing: 'vertical smartphone-style photograph', setting: 'night street driveway with a dark car immediately behind them, festive lights and greenery in the background', light: 'strong overhead light source at night',
    her: H('Lehenga', 'Red', 'Silk', 'gold embellished blouse', 'bright red festive lehenga with a heavy gold embellished blouse, rich festive detailing, gold jewellery, bangles and watch as visible'),
    him: H('Modern Kurta', 'Black', 'Cotton', 'gold motifs', 'charcoal grey ethnic kurta with repeating gold and cream traditional motifs and an embroidered neckline and cuffs, dark lower garment'),
    tone: 'Gold', colourStory: 'Red · Charcoal', tags: ['standing','night'] },
  { id: 'college-fest-15', world: 'college-fest', title: 'Maroon Crop Top, White Stole', ref: 'LOOK-15',
    pose: 'both standing very close in a garden, she facing slightly toward him, he leaning downward toward her, a white stole positioned between them with their hands interacting around the stole and waist area, playful styling moment rather than a camera-facing pose', framing: 'vertical medium to full-body photograph', setting: 'garden terrace with plants and a modern concrete wall', light: 'daylight',
    her: H('Lehenga', 'Maroon', 'Cotton', 'oxidised silver embellishment', 'deep maroon crop top with a matching long skirt, white and silver geometric embellishments, oxidised silver jewellery, large silver earrings, heavy silver bangles, bare midriff'),
    him: H('Printed Ethnic Shirt', 'Maroon', 'Cotton', 'traditional print with white stole', 'red maroon printed shirt with a dense traditional print, black loose wide trousers and a long white scarf draped around his neck'),
    tone: 'Oxidised Silver', colourStory: 'Maroon · White', tags: ['garden','stole'] },
  { id: 'college-fest-16', world: 'college-fest', title: 'Maroon Dress, Lavender Kurta', ref: 'LOOK-16',
    pose: 'both standing and walking together, she on the right and he on the left, he looking toward her, she laughing with one hand raised near her face, natural walking conversation energy with visible space between their bodies', framing: 'vertical portrait', setting: 'ornate upscale interior with a carved golden decorative wall', light: 'warm yellow indoor lighting',
    her: H('Lehenga', 'Wine', 'Georgette', 'soft pink dupatta', 'deep maroon long flowing ethnic dress with a soft pink sheer dupatta, elegant simple jewellery'),
    him: H('Modern Kurta', 'Purple', 'Cotton', 'solid', 'soft lavender kurta with a straight simple silhouette'),
    tone: 'Gold', colourStory: 'Maroon · Lavender', tags: ['walking','interior'] },
  { id: 'college-fest-17', world: 'college-fest', title: 'She Fixes His Hair, Navy Dupatta', ref: 'LOOK-17',
    pose: 'she faces him and lifts both hands toward his face and head, adjusting his hair and collar area, he stands straight looking toward her, close personal interaction', framing: 'vertical three-quarter to full-body', setting: 'outdoor residential or college style environment with green plants behind', light: 'bright daytime',
    her: H('Kurta Sets', 'Ivory', 'Cotton', 'navy dupatta', 'white ethnic outfit with a deep navy blue dupatta with a blue embroidered border, traditional silver earrings, simple white lower'),
    him: H('Modern Kurta', 'Cream', 'Cotton', 'embroidered', 'cream embroidered kurta with a white lower garment, wristwatch, clean contemporary traditional look'),
    tone: 'Silver', colourStory: 'White · Navy', tags: ['interaction','daytime'] },
  { id: 'college-fest-18', world: 'college-fest', title: 'Purple Suit in the Stairwell', ref: 'LOOK-18',
    pose: 'both seated on a staircase, he on the left leaning forward with one hand covering part of his face, she on the right seated upright touching and adjusting her hair, casual slightly awkward youthful pose, neither looking at the camera', framing: 'vertical portrait', setting: 'indoor stairwell with a white wall and the staircase rising behind', light: 'cool indoor lighting',
    her: H('Kurta Sets', 'Purple', 'Cotton', 'embroidered neckline', 'deep purple ethnic suit with a long straight kurta, a detailed embroidered neckline and front panel, a matching purple dupatta, long sleeves, minimal jewellery'),
    him: H('Festive Separates', 'White', 'Cotton', 'long-sleeve top with dark jeans', 'plain white long-sleeve t-shirt with dark charcoal jeans, white sneakers, wristwatch'),
    tone: 'Silver', colourStory: 'Purple · White', tags: ['seated','stairwell'] },
  { id: 'college-fest-19', world: 'college-fest', title: 'Blush Lehenga in the Heritage Arch', ref: 'LOOK-19',
    pose: 'standing a few feet apart inside a grand heritage arch, she on the left partially lifting one hand to her face, he on the right standing upright with relaxed arms, both looking generally toward each other or to the side rather than at the camera, strong negative space between them', framing: 'vertical architectural composition with the archway a major part of the image', setting: 'huge ornate Mughal and Rajasthani style archway with carved walls and a pink doorway far behind', light: 'warm daylight',
    her: H('Anarkali', 'Rani Pink', 'Georgette', 'embroidered upper with dupatta', 'soft blush dusty pink lehenga style anarkali with an intricately embellished upper portion, a flowing dupatta, traditional festive jewellery'),
    him: H('Modern Kurta', 'White', 'Cotton', 'minimal embroidery', 'pure white kurta pajama with minimal embroidery, clean relaxed silhouette, white footwear'),
    tone: 'Gold', colourStory: 'Blush · White', tags: ['archway','heritage'] },
  { id: 'college-fest-20', world: 'college-fest', title: 'Maroon Kurta, Balcony Crop', ref: 'LOOK-20',
    pose: 'standing side by side, he on the right with both arms crossed, she on the left with one hand around her waist, bodies close together, casual relaxed upper-body pose', framing: 'horizontal cropped composition from below the shoulders to the waist, not a full-body shot', setting: 'night balcony terrace with a railing behind', light: 'warm outdoor evening light',
    her: H('Kurta Sets', 'Maroon', 'Cotton', 'subtle embroidery', 'deep maroon ethnic kurta suit with subtle traditional embroidery and a long straight silhouette, minimal jewellery'),
    him: H('Modern Kurta', 'White', 'Cotton', 'embroidered', 'white embroidered kurta with white pajama trousers, arms crossed'),
    tone: 'Silver', colourStory: 'Maroon · White', tags: ['balcony','cropped'] },

  // ───────────── DIWALI (priority 3) ─────────────
  { id: 'diwali-01', world: 'diwali', title: 'Diya-Lit Mirror Selfie at Home', ref: 'REF-C1', pose: 'mirror selfie in a hallway mirror, he behind her shoulder', framing: 'vertical 3/4 mirror', setting: 'home hallway with diyas', light: 'warm diya glow',
    her: H('Saree', 'Wine', 'Silk Blend', 'zari border', 'wine silk saree with zari border'), him: H('Festive Kurta Set', 'Cream', 'Cotton Silk', 'tonal embroidery', 'cream kurta set'), tone: 'Gold', colourStory: 'Wine · Cream', tags: ['mirror-selfie'] },
  { id: 'diwali-02', world: 'diwali', title: 'Rangoli Overhead', ref: 'REF-C2', pose: 'kneeling around a rangoli, shot overhead', framing: 'overhead', setting: 'courtyard rangoli with diyas', light: 'dusk',
    her: H('Lehenga', 'Emerald', 'Silk', 'zari', 'emerald silk lehenga'), him: H('Modern Kurta', 'Ivory', 'Cotton Silk', 'solid', 'ivory kurta'), tone: 'Gold', colourStory: 'Emerald · Ivory', tags: ['overhead'] },
  { id: 'diwali-03', world: 'diwali', title: 'Diya Steps Glow', ref: 'REF-C3', pose: 'seated on steps lined with diyas, she photographs them', framing: 'vertical full seated', setting: 'home steps with diyas', light: 'diya glow',
    her: H('Anarkali', 'Ivory', 'Georgette', 'gold sequin', 'ivory anarkali with gold sequins'), him: H('Modern Kurta', 'Mustard', 'Cotton Silk', 'embroidered neckline', 'mustard kurta'), tone: 'Gold', colourStory: 'Ivory · Mustard', tags: ['seated'] },
  { id: 'diwali-04', world: 'diwali', title: 'Phuljhadi Face-Cup', ref: 'REF-C2 side panel', pose: 'she cups his face holding a sparkler', framing: 'vertical waist-up', setting: 'terrace', light: 'sparkler light',
    her: H('Sharara', 'Red', 'Georgette', 'gota', 'red gota sharara'), him: H('Festive Kurta Set', 'White', 'Cotton', 'solid', 'white kurta set'), tone: 'Gold', colourStory: 'Red · White', tags: ['sparkler'] },
  { id: 'diwali-05', world: 'diwali', title: 'Marigold Door Hand-Hold', ref: 'REF-C1 side panel', pose: 'holding hands, chest-down crop', framing: 'detail crop', setting: 'marigold-decorated doorway', light: 'evening',
    her: H('Pre-Draped Saree', 'Mustard', 'Silk Blend', 'zari', 'mustard pre-draped saree'), him: H('Modern Kurta', 'Maroon', 'Cotton Silk', 'solid', 'maroon kurta'), tone: 'Gold', colourStory: 'Mustard · Maroon', tags: ['hand-hold'] },
  { id: 'diwali-06', world: 'diwali', title: 'Balcony Lights Shoulder-to-Shoulder', ref: 'REF-C1 side panel', pose: 'shoulder to shoulder at balcony', framing: 'vertical nose-to-knee', setting: 'balcony fairy lights', light: 'night',
    her: H('Kurta Sets', 'Rani Pink', 'Silk Blend', 'gota', 'rani pink kurta set'), him: H('Festive Jacket', 'Navy', 'Silk Blend', 'subtle embroidery', 'navy jacket over cream kurta'), tone: 'Gold', colourStory: 'Rani pink · Navy', tags: ['outfit-check'] },
  { id: 'diwali-07', world: 'diwali', title: 'Walking Past the Lantern Lane', ref: 'REF-S1 panel 2', pose: 'walking away hand in hand', framing: 'back view', setting: 'lantern-lit lane', light: 'night lanterns',
    her: H('Lehenga', 'Maroon', 'Velvet', 'zari', 'maroon velvet lehenga'), him: H('Festive Kurta Set', 'Black', 'Cotton Silk', 'tonal', 'black kurta set'), tone: 'Gold', colourStory: 'Maroon · Black', tags: ['walking'] },
  { id: 'diwali-08', world: 'diwali', title: 'Diya Lighting Together', ref: 'REF-S1 panel 6', pose: 'lighting a diya together, heads close', framing: 'vertical waist-up', setting: 'home altar', light: 'diya',
    her: H('Saree', 'Royal Blue', 'Silk', 'zari', 'royal blue silk saree'), him: H('Modern Kurta', 'Cream', 'Cotton Silk', 'solid', 'cream kurta'), tone: 'Gold', colourStory: 'Royal blue · Cream', tags: ['candid'] },
  { id: 'diwali-09', world: 'diwali', title: 'Gharara Twirl on the Terrace', ref: 'REF-S2 panel 16', pose: 'twirl guided by his hand', framing: 'full body', setting: 'terrace lights', light: 'night',
    her: H('Gharara', 'Wine', 'Silk Blend', 'zari', 'wine gharara'), him: H('Modern Kurta', 'Ivory', 'Cotton', 'solid', 'ivory kurta'), tone: 'Gold', colourStory: 'Wine · Ivory', tags: ['twirl'] },
  { id: 'diwali-10', world: 'diwali', title: 'Cheek-to-Cheek Sparkler Selfie', ref: 'REF-S2 panel 11', pose: 'selfie with sparklers', framing: 'head-and-shoulders', setting: 'rooftop', light: 'sparkler',
    her: H('Anarkali', 'Emerald', 'Georgette', 'zari', 'emerald anarkali'), him: H('Modern Kurta', 'Black', 'Cotton', 'solid', 'black kurta'), tone: 'Gold', colourStory: 'Emerald · Black', tags: ['selfie'] },
  { id: 'diwali-11', world: 'diwali', title: 'Sweets Box Sofa Laugh', ref: 'REF-S2 panel 20', pose: 'seated on sofa sharing sweets', framing: 'full seated', setting: 'living room', light: 'warm lamp',
    her: H('Kurta Sets', 'Mustard', 'Silk Blend', 'zari', 'mustard kurta set'), him: H('Printed Ethnic Shirt', 'Wine', 'Rayon', 'paisley', 'wine paisley shirt'), tone: 'Gold', colourStory: 'Mustard · Wine', tags: ['seated'] },
  { id: 'diwali-12', world: 'diwali', title: 'Fairy Light Embrace', ref: 'REF-S2 panel 13', pose: 'embrace under lights', framing: 'waist-up', setting: 'fairy light curtain', light: 'night',
    her: H('Saree', 'Black', 'Georgette', 'gold border', 'black saree with gold border'), him: H('Festive Kurta Set', 'Ivory', 'Cotton Silk', 'tonal', 'ivory kurta set'), tone: 'Gold', colourStory: 'Black · Ivory', tags: ['embrace'] },
  { id: 'diwali-13', world: 'diwali', title: 'Pre-Draped Lift Selfie', ref: 'REF-S2 panel 14', pose: 'lift mirror selfie', framing: 'mirror full body', setting: 'lift', light: 'cool',
    her: H('Pre-Draped Saree', 'Peach', 'Georgette', 'sequin', 'peach pre-draped saree'), him: H('Ethnic Shirt', 'Sage Green', 'Cotton', 'solid', 'sage ethnic shirt'), tone: 'Gold', colourStory: 'Peach · Sage', tags: ['mirror-selfie'] },
  { id: 'diwali-14', world: 'diwali', title: 'Courtyard Bench Diyas', ref: 'REF-S2 panel 15', pose: 'bench seated whispering', framing: 'full seated', setting: 'courtyard', light: 'diyas',
    her: H('Sharara', 'Mint', 'Georgette', 'sequin', 'mint sharara'), him: H('Modern Kurta', 'Navy', 'Cotton Silk', 'solid', 'navy kurta'), tone: 'Gold', colourStory: 'Mint · Navy', tags: ['seated'] },
  { id: 'diwali-15', world: 'diwali', title: 'Lantern Hand Twirl', ref: 'REF-S2 panel 16', pose: 'both hands spin', framing: 'full body', setting: 'lantern courtyard', light: 'night',
    her: H('Lehenga', 'Gold', 'Tissue', 'zari', 'gold tissue lehenga'), him: H('Festive Kurta Set', 'Black', 'Cotton Silk', 'solid', 'black kurta set'), tone: 'Gold', colourStory: 'Gold · Black', tags: ['twirl'] },
  { id: 'diwali-16', world: 'diwali', title: 'Doorway Side Hug', ref: 'REF-S2 panel 17', pose: 'side hug at doorway', framing: '3/4', setting: 'decorated door', light: 'evening',
    her: H('Anarkali', 'Red', 'Georgette', 'gota', 'red anarkali'), him: H('Festive Jacket', 'Cream', 'Silk Blend', 'subtle embroidery', 'cream jacket over kurta'), tone: 'Gold', colourStory: 'Red · Cream', tags: ['hug'] },
  { id: 'diwali-17', world: 'diwali', title: 'Rangoli Twirl Watch', ref: 'REF-S2 panel 18', pose: 'she twirls, he watches', framing: 'full body', setting: 'rangoli courtyard', light: 'dusk',
    her: H('Lehenga', 'Lilac', 'Georgette', 'sequin', 'lilac sequin lehenga'), him: H('Modern Kurta', 'Ivory', 'Cotton', 'solid', 'ivory kurta'), tone: 'Silver', colourStory: 'Lilac · Ivory', tags: ['twirl'] },
  { id: 'diwali-18', world: 'diwali', title: 'Market Lights Walk', ref: 'REF-S1 panel 4', pose: 'walking toward camera', framing: 'full body', setting: 'lit market', light: 'night',
    her: H('Kurta Sets', 'Wine', 'Silk Blend', 'zari', 'wine kurta set'), him: H('Modern Kurta', 'Beige', 'Linen', 'solid', 'beige kurta'), tone: 'Gold', colourStory: 'Wine · Beige', tags: ['walking'] },
  { id: 'diwali-19', world: 'diwali', title: 'Forehead Touch by the Diyas', ref: 'REF-S1 panel 6', pose: 'forehead touch', framing: 'waist-up', setting: 'diya windowsill', light: 'diya',
    her: H('Saree', 'Rani Pink', 'Silk', 'zari', 'rani pink silk saree'), him: H('Modern Kurta', 'Ivory', 'Cotton Silk', 'solid', 'ivory kurta'), tone: 'Gold', colourStory: 'Rani pink · Ivory', tags: ['close'] },
  { id: 'diwali-20', world: 'diwali', title: 'Diwali Lawn Overhead', ref: 'REF-C2', pose: 'lying on lawn with diyas, overhead', framing: 'overhead', setting: 'lawn', light: 'dusk',
    her: H('Sharara', 'Ivory', 'Georgette', 'gold sequin', 'ivory sequin sharara'), him: H('Festive Kurta Set', 'Maroon', 'Cotton Silk', 'solid', 'maroon kurta set'), tone: 'Gold', colourStory: 'Ivory · Maroon', tags: ['overhead'] },

  // ───────────── FESTIVE PARTY (priority 4) ─────────────
  { id: 'festive-party-01', world: 'festive-party', title: 'Black Sequin Party Mirror Selfie', ref: 'REF-C1', pose: 'mirror selfie', framing: '3/4 mirror', setting: 'party venue washroom mirror', light: 'moody',
    her: H('Saree', 'Black', 'Georgette', 'sequin', 'black sequin saree'), him: H('Modern Kurta', 'Black', 'Georgette', 'mirror sequin', 'black mirror-sequin kurta'), tone: 'Silver', colourStory: 'Black-on-black', tags: ['mirror-selfie'] },
  { id: 'festive-party-02', world: 'festive-party', title: 'Rooftop Overhead in Emerald', ref: 'REF-C2', pose: 'overhead lying', framing: 'overhead', setting: 'rooftop lounge', light: 'dusk',
    her: H('Lehenga', 'Emerald', 'Velvet', 'sequin', 'emerald velvet lehenga'), him: H('Festive Jacket', 'Black', 'Velvet', 'solid', 'black velvet jacket'), tone: 'Gold', colourStory: 'Emerald · Black', tags: ['overhead'] },
  { id: 'festive-party-03', world: 'festive-party', title: 'Staircase Sit', ref: 'REF-C3', pose: 'seated on staircase', framing: 'full seated', setting: 'wooden staircase', light: 'warm',
    her: H('Sharara', 'Wine', 'Georgette', 'sequin', 'wine sequin sharara'), him: H('Modern Kurta', 'Cream', 'Cotton Silk', 'solid', 'cream kurta'), tone: 'Gold', colourStory: 'Wine · Cream', tags: ['seated'] },
  { id: 'festive-party-04', world: 'festive-party', title: 'Red Jacket Laugh', ref: 'REF-C2 side panel', pose: 'face-cup laugh', framing: 'waist-up', setting: 'party lights', light: 'night',
    her: H('Pre-Draped Saree', 'Black', 'Satin', 'solid', 'black satin pre-draped saree'), him: H('Festive Jacket', 'Red', 'Brocade', 'brocade', 'red brocade jacket over black'), tone: 'Silver', colourStory: 'Black · Red brocade', tags: ['candid'] },
  { id: 'festive-party-05', world: 'festive-party', title: 'Lounge Hand-Hold Crop', ref: 'REF-C1 side panel', pose: 'hand-hold crop', framing: 'detail crop', setting: 'lounge', light: 'warm',
    her: H('Lehenga', 'Silver', 'Tissue', 'sequin', 'silver tissue lehenga'), him: H('Modern Kurta', 'Navy', 'Silk Blend', 'solid', 'navy kurta'), tone: 'Silver', colourStory: 'Silver · Navy', tags: ['hand-hold'] },
  { id: 'festive-party-06', world: 'festive-party', title: 'Bar Counter Shoulder Line', ref: 'REF-C1 side panel', pose: 'shoulder to shoulder', framing: 'nose-to-knee', setting: 'party bar counter', light: 'moody',
    her: H('Anarkali', 'Black', 'Georgette', 'gold', 'black anarkali with gold'), him: H('Embroidered Ethnic Shirt', 'Ivory', 'Silk Blend', 'tonal', 'ivory embroidered shirt'), tone: 'Gold', colourStory: 'Black · Ivory', tags: ['outfit-check'] },
  { id: 'festive-party-07', world: 'festive-party', title: 'Corridor Walk-Out', ref: 'REF-S1 panel 2', pose: 'walking away', framing: 'back view', setting: 'hotel corridor', light: 'warm',
    her: H('Saree', 'Emerald', 'Satin', 'solid', 'emerald satin saree'), him: H('Festive Kurta Set', 'Black', 'Cotton Silk', 'solid', 'black kurta set'), tone: 'Gold', colourStory: 'Emerald · Black', tags: ['walking'] },
  { id: 'festive-party-08', world: 'festive-party', title: 'Earring Fix', ref: 'REF-S1 panel 6', pose: 'he helps fix her earring', framing: 'waist-up', setting: 'party hallway', light: 'warm',
    her: H('Sharara', 'Black', 'Georgette', 'mirror', 'black mirror sharara'), him: H('Printed Ethnic Shirt', 'Teal', 'Rayon', 'paisley', 'teal printed shirt'), tone: 'Silver', colourStory: 'Black · Teal', tags: ['candid'] },
  { id: 'festive-party-09', world: 'festive-party', title: 'Dance Floor Spin', ref: 'REF-S2 panel 16', pose: 'spin on dance floor', framing: 'full body', setting: 'dance floor', light: 'party lights',
    her: H('Lehenga', 'Wine', 'Velvet', 'sequin', 'wine velvet lehenga'), him: H('Modern Kurta', 'Black', 'Cotton', 'solid', 'black kurta'), tone: 'Gold', colourStory: 'Wine · Black', tags: ['twirl'] },
  { id: 'festive-party-10', world: 'festive-party', title: 'Flash Selfie', ref: 'REF-S2 panel 11', pose: 'flash selfie', framing: 'head-and-shoulders', setting: 'party', light: 'flash',
    her: H('Pre-Draped Saree', 'Silver', 'Georgette', 'sequin', 'silver sequin pre-draped saree'), him: H('Embroidered Ethnic Shirt', 'Black', 'Cotton', 'sequin dots', 'black sequin-dot shirt'), tone: 'Silver', colourStory: 'Silver · Black', tags: ['selfie'] },
  { id: 'festive-party-11', world: 'festive-party', title: 'Couch Laugh', ref: 'REF-S2 panel 20', pose: 'seated laughing', framing: 'full seated', setting: 'house party couch', light: 'lamp',
    her: H('Kurta Sets', 'Emerald', 'Silk Blend', 'sequin', 'emerald kurta set'), him: H('Modern Kurta', 'Ivory', 'Cotton', 'solid', 'ivory kurta'), tone: 'Gold', colourStory: 'Emerald · Ivory', tags: ['seated'] },
  { id: 'festive-party-12', world: 'festive-party', title: 'Terrace Embrace', ref: 'REF-S2 panel 13', pose: 'embrace', framing: 'waist-up', setting: 'terrace lights', light: 'night',
    her: H('Gharara', 'Black', 'Georgette', 'gold', 'black gold gharara'), him: H('Festive Jacket', 'Ivory', 'Silk Blend', 'subtle embroidery', 'ivory jacket'), tone: 'Gold', colourStory: 'Black · Ivory', tags: ['embrace'] },
  { id: 'festive-party-13', world: 'festive-party', title: 'Gold Lift Mirror', ref: 'REF-S2 panel 14', pose: 'lift mirror selfie', framing: 'mirror full', setting: 'brass lift', light: 'warm',
    her: H('Saree', 'Gold', 'Tissue', 'zari', 'gold tissue saree'), him: H('Modern Kurta', 'Black', 'Cotton Silk', 'solid', 'black kurta'), tone: 'Gold', colourStory: 'Gold · Black', tags: ['mirror-selfie'] },
  { id: 'festive-party-14', world: 'festive-party', title: 'Poolside Bench', ref: 'REF-S2 panel 15', pose: 'bench whisper', framing: 'full seated', setting: 'poolside bench', light: 'night',
    her: H('Anarkali', 'Navy', 'Georgette', 'sequin', 'navy sequin anarkali'), him: H('Ethnic Shirt', 'White', 'Linen', 'solid', 'white linen ethnic shirt'), tone: 'Silver', colourStory: 'Navy · White', tags: ['seated'] },
  { id: 'festive-party-15', world: 'festive-party', title: 'Two-Hand Spin', ref: 'REF-S2 panel 16', pose: 'two-hand spin', framing: 'full body', setting: 'banquet lawn', light: 'fairy',
    her: H('Lehenga', 'Rani Pink', 'Georgette', 'sequin', 'rani pink sequin lehenga'), him: H('Festive Kurta Set', 'Ivory', 'Cotton Silk', 'solid', 'ivory kurta set'), tone: 'Gold', colourStory: 'Rani pink · Ivory', tags: ['twirl'] },
  { id: 'festive-party-16', world: 'festive-party', title: 'Entrance Side Hug', ref: 'REF-S2 panel 17', pose: 'side hug', framing: '3/4', setting: 'venue entrance', light: 'night',
    her: H('Sharara', 'Emerald', 'Georgette', 'sequin', 'emerald sequin sharara'), him: H('Modern Kurta', 'Black', 'Cotton', 'solid', 'black kurta'), tone: 'Gold', colourStory: 'Emerald · Black', tags: ['hug'] },
  { id: 'festive-party-17', world: 'festive-party', title: 'Lawn Twirl Watch', ref: 'REF-S2 panel 18', pose: 'twirl watch', framing: 'full body', setting: 'party lawn', light: 'dusk',
    her: H('Lehenga', 'Black', 'Georgette', 'sequin', 'black sequin lehenga'), him: H('Embroidered Ethnic Shirt', 'Ivory', 'Silk Blend', 'tonal', 'ivory embroidered shirt'), tone: 'Silver', colourStory: 'Black · Ivory', tags: ['twirl'] },
  { id: 'festive-party-18', world: 'festive-party', title: 'Arrival Walk', ref: 'REF-S1 panel 4', pose: 'walking toward camera', framing: 'full body', setting: 'venue driveway', light: 'night',
    her: H('Pre-Draped Saree', 'Wine', 'Satin', 'solid', 'wine satin pre-draped saree'), him: H('Festive Jacket', 'Navy', 'Silk Blend', 'solid', 'navy jacket'), tone: 'Gold', colourStory: 'Wine · Navy', tags: ['walking'] },
  { id: 'festive-party-19', world: 'festive-party', title: 'Candlelit Forehead Touch', ref: 'REF-S1 panel 6', pose: 'forehead touch', framing: 'waist-up', setting: 'candle-lit table', light: 'candle',
    her: H('Saree', 'Wine', 'Georgette', 'sequin', 'wine sequin saree'), him: H('Modern Kurta', 'Black', 'Georgette', 'mirror sequin', 'black sequin kurta'), tone: 'Silver', colourStory: 'Wine · Black', tags: ['close'] },
  { id: 'festive-party-20', world: 'festive-party', title: 'Rooftop Rug Overhead', ref: 'REF-C2', pose: 'overhead lying on rug', framing: 'overhead', setting: 'rooftop rug', light: 'dusk',
    her: H('Lehenga', 'Silver', 'Georgette', 'mirror', 'silver mirror lehenga'), him: H('Printed Ethnic Shirt', 'Black', 'Rayon', 'block print', 'black printed shirt'), tone: 'Silver', colourStory: 'Silver · Black', tags: ['overhead'] },

  // ───────────── TRADITIONAL (priority 5) ─────────────
  { id: 'traditional-01', world: 'traditional', title: 'Temple Town Mirror Selfie', ref: 'REF-C1', pose: 'mirror selfie', framing: '3/4 mirror', setting: 'old haveli mirror', light: 'window',
    her: H('Saree', 'Mustard', 'Silk', 'temple border', 'mustard silk saree with temple border'), him: H('Festive Kurta Set', 'Ivory', 'Cotton Silk', 'solid', 'ivory kurta set'), tone: 'Gold', colourStory: 'Mustard · Ivory', tags: ['mirror-selfie'] },
  { id: 'traditional-02', world: 'traditional', title: 'Haveli Floor Overhead', ref: 'REF-C2', pose: 'overhead lying', framing: 'overhead', setting: 'patterned haveli floor', light: 'sun',
    her: H('Lehenga', 'Maroon', 'Silk', 'bandhani', 'maroon bandhani silk lehenga'), him: H('Modern Kurta', 'Cream', 'Cotton', 'solid', 'cream kurta'), tone: 'Gold', colourStory: 'Maroon · Cream', tags: ['overhead'] },
  { id: 'traditional-03', world: 'traditional', title: 'Ghat Steps', ref: 'REF-C3', pose: 'seated on ghat steps', framing: 'full seated', setting: 'river ghat', light: 'golden hour',
    her: H('Saree', 'Red', 'Cotton', 'contrast border', 'red cotton saree with white border'), him: H('Modern Kurta', 'White', 'Cotton', 'solid', 'white kurta'), tone: 'Gold', colourStory: 'Red · White', tags: ['seated'] },
  { id: 'traditional-04', world: 'traditional', title: 'Courtyard Laugh', ref: 'REF-C2 side panel', pose: 'face-cup laugh', framing: 'waist-up', setting: 'courtyard', light: 'day',
    her: H('Anarkali', 'Teal', 'Cotton', 'block print', 'teal block-print anarkali'), him: H('Festive Kurta Set', 'Beige', 'Linen', 'solid', 'beige kurta set'), tone: 'Oxidised Silver', colourStory: 'Teal · Beige', tags: ['candid'] },
  { id: 'traditional-05', world: 'traditional', title: 'Temple Door Hand-Hold', ref: 'REF-C1 side panel', pose: 'hand-hold crop', framing: 'detail crop', setting: 'temple door', light: 'day',
    her: H('Saree', 'Emerald', 'Silk', 'zari', 'emerald silk saree'), him: H('Festive Kurta Set', 'Cream', 'Cotton Silk', 'solid', 'cream kurta set'), tone: 'Gold', colourStory: 'Emerald · Cream', tags: ['hand-hold'] },
  { id: 'traditional-06', world: 'traditional', title: 'Jharokha Shoulder Line', ref: 'REF-C1 side panel', pose: 'shoulder to shoulder', framing: 'nose-to-knee', setting: 'jharokha window', light: 'window',
    her: H('Kurta Sets', 'Indigo', 'Cotton', 'block print', 'indigo block-print kurta set'), him: H('Modern Kurta', 'White', 'Cotton', 'solid', 'white kurta'), tone: 'Oxidised Silver', colourStory: 'Indigo · White', tags: ['outfit-check'] },
  { id: 'traditional-07', world: 'traditional', title: 'Fort Lane Walk', ref: 'REF-S1 panel 2', pose: 'walking away', framing: 'back view', setting: 'fort lane', light: 'afternoon',
    her: H('Lehenga', 'Mustard', 'Cotton', 'bandhani', 'mustard bandhani lehenga'), him: H('Modern Kurta', 'Maroon', 'Cotton', 'solid', 'maroon kurta'), tone: 'Oxidised Silver', colourStory: 'Mustard · Maroon', tags: ['walking'] },
  { id: 'traditional-08', world: 'traditional', title: 'Pallu Fix at the Temple', ref: 'REF-S1 panel 6', pose: 'he adjusts her pallu', framing: 'waist-up', setting: 'temple corridor', light: 'soft',
    her: H('Saree', 'Ivory', 'Cotton', 'gold border', 'ivory kasavu-style saree with gold border'), him: H('Modern Kurta', 'Ivory', 'Cotton', 'solid', 'ivory kurta'), tone: 'Gold', colourStory: 'Ivory · Gold', tags: ['dupatta-adjust'] },
  { id: 'traditional-09', world: 'traditional', title: 'Courtyard Spin', ref: 'REF-S2 panel 16', pose: 'twirl', framing: 'full body', setting: 'haveli courtyard', light: 'day',
    her: H('Anarkali', 'Red', 'Cotton', 'gota', 'red gota anarkali'), him: H('Festive Kurta Set', 'Ivory', 'Cotton', 'solid', 'ivory kurta set'), tone: 'Gold', colourStory: 'Red · Ivory', tags: ['twirl'] },
  { id: 'traditional-10', world: 'traditional', title: 'Temple Selfie', ref: 'REF-S2 panel 11', pose: 'selfie', framing: 'head-and-shoulders', setting: 'temple steps', light: 'day',
    her: H('Saree', 'Rani Pink', 'Silk', 'temple border', 'rani pink silk saree'), him: H('Modern Kurta', 'Mustard', 'Cotton', 'solid', 'mustard kurta'), tone: 'Gold', colourStory: 'Rani pink · Mustard', tags: ['selfie'] },
  { id: 'traditional-11', world: 'traditional', title: 'Jhoola Laugh', ref: 'REF-S2 panel 20', pose: 'seated on jhoola laughing', framing: 'full seated', setting: 'wooden jhoola', light: 'day',
    her: H('Lehenga', 'Green', 'Cotton', 'block print', 'green block-print lehenga'), him: H('Modern Kurta', 'Cream', 'Linen', 'solid', 'cream kurta'), tone: 'Oxidised Silver', colourStory: 'Green · Cream', tags: ['seated'] },
  { id: 'traditional-12', world: 'traditional', title: 'Archway Embrace', ref: 'REF-S2 panel 13', pose: 'embrace', framing: 'waist-up', setting: 'stone archway', light: 'dusk',
    her: H('Saree', 'Maroon', 'Silk', 'zari', 'maroon silk saree'), him: H('Festive Kurta Set', 'Ivory', 'Cotton Silk', 'solid', 'ivory kurta set'), tone: 'Gold', colourStory: 'Maroon · Ivory', tags: ['embrace'] },
  { id: 'traditional-13', world: 'traditional', title: 'Heirloom Mirror', ref: 'REF-S2 panel 14', pose: 'mirror selfie', framing: 'mirror full', setting: 'carved mirror', light: 'warm',
    her: H('Pre-Draped Saree', 'Mustard', 'Silk Blend', 'zari', 'mustard pre-draped saree'), him: H('Modern Kurta', 'Green', 'Cotton', 'solid', 'green kurta'), tone: 'Gold', colourStory: 'Mustard · Green', tags: ['mirror-selfie'] },
  { id: 'traditional-14', world: 'traditional', title: 'Stone Bench', ref: 'REF-S2 panel 15', pose: 'bench seated', framing: 'full seated', setting: 'stone bench', light: 'evening',
    her: H('Kurta Sets', 'Maroon', 'Cotton', 'gota', 'maroon kurta set'), him: H('Festive Kurta Set', 'Beige', 'Linen', 'solid', 'beige kurta set'), tone: 'Gold', colourStory: 'Maroon · Beige', tags: ['seated'] },
  { id: 'traditional-15', world: 'traditional', title: 'Hand Spin Courtyard', ref: 'REF-S2 panel 16', pose: 'two-hand spin', framing: 'full body', setting: 'courtyard', light: 'day',
    her: H('Lehenga', 'Royal Blue', 'Silk', 'bandhani', 'royal blue bandhani lehenga'), him: H('Modern Kurta', 'White', 'Cotton', 'solid', 'white kurta'), tone: 'Oxidised Silver', colourStory: 'Royal blue · White', tags: ['twirl'] },
  { id: 'traditional-16', world: 'traditional', title: 'Gate Side Hug', ref: 'REF-S2 panel 17', pose: 'side hug', framing: '3/4', setting: 'old gate', light: 'day',
    her: H('Anarkali', 'Mustard', 'Cotton', 'block print', 'mustard anarkali'), him: H('Modern Kurta', 'Indigo', 'Cotton', 'block print', 'indigo kurta'), tone: 'Oxidised Silver', colourStory: 'Mustard · Indigo', tags: ['hug'] },
  { id: 'traditional-17', world: 'traditional', title: 'Temple Twirl Watch', ref: 'REF-S2 panel 18', pose: 'twirl watch', framing: 'full body', setting: 'temple lawn', light: 'dusk',
    her: H('Lehenga', 'Red', 'Cotton', 'bandhani', 'red bandhani lehenga'), him: H('Modern Kurta', 'Cream', 'Cotton', 'solid', 'cream kurta'), tone: 'Oxidised Silver', colourStory: 'Red · Cream', tags: ['twirl'] },
  { id: 'traditional-18', world: 'traditional', title: 'Bazaar Walk', ref: 'REF-S1 panel 4', pose: 'walking toward camera', framing: 'full body', setting: 'old bazaar', light: 'day',
    her: H('Saree', 'Green', 'Cotton', 'contrast border', 'green cotton saree'), him: H('Modern Kurta', 'White', 'Cotton', 'solid', 'white kurta'), tone: 'Gold', colourStory: 'Green · White', tags: ['walking'] },
  { id: 'traditional-19', world: 'traditional', title: 'Aarti Forehead Touch', ref: 'REF-S1 panel 6', pose: 'forehead touch', framing: 'waist-up', setting: 'temple lamps', light: 'lamp',
    her: H('Saree', 'Red', 'Silk', 'zari', 'red silk saree'), him: H('Modern Kurta', 'Ivory', 'Cotton Silk', 'solid', 'ivory kurta'), tone: 'Gold', colourStory: 'Red · Ivory', tags: ['close'] },
  { id: 'traditional-20', world: 'traditional', title: 'Courtyard Overhead', ref: 'REF-C2', pose: 'overhead lying', framing: 'overhead', setting: 'courtyard tiles', light: 'sun',
    her: H('Lehenga', 'Ivory', 'Cotton', 'block print', 'ivory block-print lehenga'), him: H('Modern Kurta', 'Maroon', 'Cotton', 'solid', 'maroon kurta'), tone: 'Oxidised Silver', colourStory: 'Ivory · Maroon', tags: ['overhead'] },
];
