// 100 VIRAAS couple looks — exactly 20 per public world.
// Each look is anchored to a supplied reference (REF-C1..C3 individual screenshots, REF-S1/S2 sheet panels)
// and records the outfit + pose + framing language to recreate. `her`/`him` drive the linked products,
// so the couple image and the linked catalog products always describe the same garments.
//
// Fields: id, world, title, ref, pose, framing, setting, light, her{cat,colour,fabric,detail,desc},
//         him{cat,colour,fabric,detail,desc}, layer (optional men's stole/dupatta), tone (jewellery metal),
//         colourStory, tags

const H = (cat, colour, fabric, detail, desc) => ({ cat, colour, fabric, detail, desc });

export const WORLDS = [
  { slug: 'garba', name: 'Garba', long: 'Garba / Navratri', blurb: 'Nine nights of mirror work, bandhani and twirl-ready flare.' },
  { slug: 'college-fest', name: 'College Fest', long: 'College Fest', blurb: 'Light, move-all-day festive looks for campus ethnic day.' },
  { slug: 'diwali', name: 'Diwali', long: 'Diwali', blurb: 'Diya-lit silks, soft gold and house-party ready drapes.' },
  { slug: 'festive-party', name: 'Festive Party', long: 'Festive Party', blurb: 'After-dark sequins, jewel tones and black-on-black.' },
  { slug: 'traditional', name: 'Traditional', long: 'Traditional', blurb: 'Handloom, temple borders and heirloom-inspired styling — worn young.' },
];

export const COUPLES = [
  // ───────────── GARBA / NAVRATRI (priority 1) ─────────────
  { id: 'garba-01', world: 'garba', title: 'Rani Pink Fitting-Room Mirror Check', ref: 'REF-C1',
    pose: 'standing mirror selfie; she holds the phone over part of her face with her other hand on her cheek; he stands close behind her shoulder with an arm around her waist',
    framing: 'vertical 3/4-length mirror reflection', setting: 'clothing store fitting area with garment racks', light: 'cool fluorescent store light',
    her: H('Lehenga', 'Rani Pink', 'Silk Blend', 'gota border dupatta', 'rani pink flared silk lehenga skirt with a white strapless embroidered bandeau top and a rani pink gota-border dupatta with tassels'),
    him: H('Festive Kurta Set', 'White', 'Cotton', 'solid', 'plain white cotton kurta pyjama set'),
    layer: H('Traditional Layer', 'Red', 'Cotton', 'phulkari embroidery', 'rani red phulkari dupatta with multicolour floral embroidery and tassels'),
    tone: 'Oxidised Silver', colourStory: 'Rani pink · White · Phulkari red', tags: ['mirror-selfie', 'twinning'] },
  { id: 'garba-02', world: 'garba', title: 'Black Brocade Overhead Outfit Check', ref: 'REF-C2',
    pose: 'both lying side by side on the ground, bodies angled diagonally; her hand rests on her hair, his hands clasped at chest',
    framing: 'directly overhead top-down, full body', setting: 'sunlit grey concrete', light: 'hard afternoon sun with crisp shadows',
    her: H('Lehenga', 'Black', 'Brocade', 'gold-teal paisley brocade', 'black flared lehenga with gold and teal brocade paisley motifs and a fitted white long-sleeve crop top'),
    him: H('Modern Kurta', 'Black', 'Cotton Silk', 'copper thread placket embroidery', 'black kurta with copper-brown thread embroidery on the neckline placket'),
    layer: H('Traditional Layer', 'Ivory', 'Cotton', 'paisley block print', 'ivory paisley block-printed stole with black border'),
    tone: 'Oxidised Silver', colourStory: 'Black · White · Ivory paisley', tags: ['overhead', 'twinning'] },
  { id: 'garba-03', world: 'garba', title: 'Ivory Mirror-Work on the Diya Steps', ref: 'REF-C3',
    pose: 'seated close on stone steps; she takes a phone photo leaning into him; his forearm rests on his knee, head tilted to her',
    framing: 'vertical, full seated bodies', setting: 'old stone steps beside a carved pillar with lit diyas', light: 'warm golden hour',
    her: H('Lehenga', 'Ivory', 'Georgette', 'mirror work embellishment', 'ivory lehenga densely covered in round mirror work with a sleeveless embellished crop blouse and sheer ivory dupatta'),
    him: H('Modern Kurta', 'White', 'Cotton', 'chikankari', 'white chikankari kurta worn with blue denim'),
    tone: 'Silver', colourStory: 'Ivory · White · Denim', tags: ['seated', 'golden-hour'] },
  { id: 'garba-04', world: 'garba', title: 'Red Backless Choli, Face-Cup Laugh', ref: 'REF-C2 side panel',
    pose: 'she, seen from behind at three-quarter, cups his face with both hands; he laughs',
    framing: 'vertical waist-up', setting: 'outdoor navratri venue with string lights and trees', light: 'night ambient light',
    her: H('Chaniya Choli', 'Red', 'Cotton', 'kutchi embroidered backless blouse', 'red chaniya choli with a multicolour kutchi-embroidered tie-up backless blouse and red dupatta'),
    him: H('Festive Kurta Set', 'White', 'Cotton', 'solid', 'white cotton kurta set'),
    layer: H('Traditional Layer', 'Red', 'Cotton', 'bandhani print', 'long red bandhani dupatta'),
    tone: 'Oxidised Silver', colourStory: 'Red · White · Multicolour kutch', tags: ['night', 'candid'] },
  { id: 'garba-05', world: 'garba', title: 'Pink Bandhani Hand-Hold on the Lawn', ref: 'REF-C1 side panel',
    pose: 'standing side by side holding hands between them; chest-down crop focusing on outfits',
    framing: 'vertical chest-to-feet crop', setting: 'evening garba ground lawn', light: 'soft dusk light',
    her: H('Chaniya Choli', 'Rani Pink', 'Cotton', 'bandhani print with mirror hem', 'rani pink bandhani flared chaniya with a mirror-work hem, white blouse and sheer white lace-edged dupatta'),
    him: H('Modern Kurta', 'White', 'Cotton', 'chikankari sequin', 'white chikankari kurta with fine sequins and white pyjama'),
    tone: 'Silver', colourStory: 'Rani pink bandhani · White', tags: ['hand-hold', 'detail-crop'] },
  { id: 'garba-06', world: 'garba', title: 'Red & Ivory Shoulder-to-Shoulder', ref: 'REF-C1 side panel',
    pose: 'standing shoulder to shoulder, her bangled arm resting against him; nose-to-knee crop',
    framing: 'vertical nose-to-knee crop', setting: 'plain cream indoor wall', light: 'warm indoor light',
    her: H('Lehenga', 'Red', 'Silk', 'gold border', 'red silk lehenga with gold-border dupatta and ivory embroidered blouse'),
    him: H('Festive Kurta Set', 'Ivory', 'Cotton', 'self stripe', 'ivory self-stripe cotton kurta pyjama set with sheer white dupatta'),
    tone: 'Silver', colourStory: 'Red · Ivory', tags: ['outfit-check'] },
  { id: 'garba-07', world: 'garba', title: 'Patchwork Walk Into the Canopy', ref: 'REF-S1 panel 2/10',
    pose: 'walking hand in hand away from camera into the crowd, three-quarter back view',
    framing: 'vertical full body from behind', setting: 'crowded garba ground under striped canopy and string lights', light: 'night festival light',
    her: H('Chaniya Choli', 'Multicolour', 'Cotton', 'patchwork with mirror work', 'multicolour patchwork flared chaniya choli in pink, orange, yellow and green with mirror work and a backless tie-up blouse'),
    him: H('Festive Kurta Set', 'Black', 'Cotton', 'solid', 'black kurta and black pants'),
    layer: H('Traditional Layer', 'Red', 'Cotton', 'bandhani print', 'red bandhani dupatta over one shoulder'),
    tone: 'Oxidised Silver', colourStory: 'Multicolour patchwork · Black · Red', tags: ['walking', 'back-view'] },
  { id: 'garba-08', world: 'garba', title: 'Black Patola Dandiya Face-Off', ref: 'REF-S1 panel 5',
    pose: 'facing each other mid-dandiya, sticks crossed between them, both laughing',
    framing: 'vertical full body', setting: 'night garba ground with dancers', light: 'festival lights',
    her: H('Chaniya Choli', 'Black', 'Rayon', 'gold lampi border with patola dupatta', 'black chaniya with gold border, black long-sleeve crop top and multicolour patola dupatta with tassels'),
    him: H('Ethnic Shirt', 'Navy', 'Cotton', 'small embroidered motifs', 'navy short kurta-shirt with small white embroidered motifs and cream pants'),
    tone: 'Oxidised Silver', colourStory: 'Black · Patola multicolour · Navy', tags: ['dandiya', 'playful'] },
  { id: 'garba-09', world: 'garba', title: 'Kutchi Halter, Dupatta Fix', ref: 'REF-S1 panel 6',
    pose: 'he gently adjusts the dupatta on her shoulder; she looks down smiling',
    framing: 'vertical waist-up', setting: 'evening path beside a garba venue', light: 'warm bokeh light',
    her: H('Chaniya Choli', 'White', 'Cotton', 'kutchi mirror halter', 'white chaniya with kutchi mirror-embroidered halter blouse and multicolour patchwork tasselled dupatta'),
    him: H('Modern Kurta', 'White', 'Cotton', 'chikankari', 'white chikankari kurta'),
    layer: H('Traditional Layer', 'Navy', 'Georgette', 'sequin scatter', 'navy sequin-scattered stole'),
    tone: 'Oxidised Silver', colourStory: 'White · Kutch multicolour · Navy sequin', tags: ['dupatta-adjust'] },
  { id: 'garba-10', world: 'garba', title: 'Red Flare Twirl Under the Floodlights', ref: 'REF-S1 panel 8 / REF-S2 panel 16',
    pose: 'she twirls mid-spin while he holds her hand above her head guiding the twirl',
    framing: 'vertical full body', setting: 'grass garba field with floodlights and bunting', light: 'night floodlight',
    her: H('Chaniya Choli', 'Red', 'Cotton', 'kutchi mirror crop top', 'wide red flared chaniya with black kutchi mirror crop top and red-black bandhani dupatta'),
    him: H('Festive Kurta Set', 'Ivory', 'Cotton', 'solid', 'ivory kurta pyjama set'),
    layer: H('Traditional Layer', 'Red', 'Cotton', 'bandhani print', 'red bandhani dupatta'),
    tone: 'Oxidised Silver', colourStory: 'Red · Black kutch · Ivory', tags: ['twirl', 'motion'] },
  { id: 'garba-11', world: 'garba', title: 'Royal Blue Cheek-to-Cheek Selfie', ref: 'REF-S2 panel 11/19',
    pose: 'arm-length selfie taken by him, cheek to cheek, both grinning', framing: 'vertical head-and-shoulders', setting: 'night garba ground bokeh', light: 'slight phone-flash night',
    her: H('Chaniya Choli', 'Royal Blue', 'Cotton', 'mirror work', 'royal blue mirror-work chaniya choli with red bandhani dupatta loosely over her head'),
    him: H('Festive Kurta Set', 'White', 'Cotton', 'solid', 'white kurta set'),
    layer: H('Traditional Layer', 'Red', 'Cotton', 'solid', 'red cotton dupatta around the neck'),
    tone: 'Oxidised Silver', colourStory: 'Royal blue · Red · White', tags: ['selfie'] },
  { id: 'garba-12', world: 'garba', title: 'Mustard Mirror Mat-Side Laughs', ref: 'REF-S2 panel 20',
    pose: 'seated on a mat on the ground laughing, her head on his shoulder', framing: 'vertical full seated', setting: 'garba venue edge with fairy lights', light: 'warm night',
    her: H('Chaniya Choli', 'Mustard', 'Cotton', 'red mirror border', 'mustard chaniya choli with red mirror-work border, red embroidered blouse and green bandhani dupatta'),
    him: H('Printed Ethnic Shirt', 'Olive', 'Rayon', 'botanical print', 'olive printed ethnic shirt with ivory trousers'),
    tone: 'Oxidised Silver', colourStory: 'Mustard · Red · Olive', tags: ['seated', 'candid'] },
  { id: 'garba-13', world: 'garba', title: 'Black Sequin Stage-Glow Embrace', ref: 'REF-S2 panel 13',
    pose: 'gentle embrace, her head on his chest, eyes closed', framing: 'vertical waist-up', setting: 'near a garba stage', light: 'orange-red stage glow',
    her: H('Chaniya Choli', 'Rust', 'Rayon', 'mirror work', 'rust-ochre and red mirror-work chaniya choli with black bandhani dupatta'),
    him: H('Modern Kurta', 'Black', 'Georgette', 'mirror sequin', 'black mirror-sequin kurta'),
    tone: 'Oxidised Silver', colourStory: 'Rust · Black', tags: ['embrace', 'night'] },
  { id: 'garba-14', world: 'garba', title: 'Emerald Lift Mirror Selfie', ref: 'REF-S2 panel 14',
    pose: 'mirror selfie inside a steel lift; she holds the phone, he rests his chin on her head', framing: 'vertical full body mirror', setting: 'steel elevator interior', light: 'cool overhead lift light',
    her: H('Chaniya Choli', 'Emerald', 'Cotton', 'gamthi print with mirror', 'emerald gamthi-print chaniya choli with mirror blouse and magenta dupatta'),
    him: H('Ethnic Shirt', 'Ivory', 'Cotton', 'tonal embroidery', 'ivory ethnic shirt with tonal embroidery and emerald trousers'),
    tone: 'Oxidised Silver', colourStory: 'Emerald · Magenta · Ivory', tags: ['mirror-selfie'] },
  { id: 'garba-15', world: 'garba', title: 'Black-on-Black Fairy Light Bench', ref: 'REF-S2 panel 15',
    pose: 'seated on a bench, knees touching, he whispers, she laughs looking away', framing: 'vertical full seated', setting: 'bench under fairy lights', light: 'fairy-light glow',
    her: H('Chaniya Choli', 'Black', 'Rayon', 'black mirror work', 'black chaniya choli with black embroidered crop blouse and black mirror-dot dupatta'),
    him: H('Festive Kurta Set', 'Black', 'Cotton Silk', 'tonal embroidery', 'black kurta set with tonal embroidery'),
    layer: H('Traditional Layer', 'Black', 'Cotton', 'gold paisley', 'black and gold paisley shawl'),
    tone: 'Oxidised Silver', colourStory: 'Black-on-black · Gold', tags: ['seated', 'black-on-black'] },
  { id: 'garba-16', world: 'garba', title: 'Wine Lehenga Twirl, Hand in Hand', ref: 'REF-S2 panel 16',
    pose: 'both spinning together holding both hands, leaning back', framing: 'vertical full body', setting: 'night garba field', light: 'floodlights',
    her: H('Lehenga', 'Wine', 'Cotton Silk', 'kutch embroidery', 'wine lehenga with kutch-embroidered blouse'),
    him: H('Modern Kurta', 'Cream', 'Cotton', 'embroidered placket', 'cream kurta with embroidered placket'),
    layer: H('Traditional Layer', 'Wine', 'Cotton', 'bandhani print', 'wine bandhani stole'),
    tone: 'Oxidised Silver', colourStory: 'Wine · Cream', tags: ['twirl'] },
  { id: 'garba-17', world: 'garba', title: 'Blue Bandhani Festive-Lights Hug', ref: 'REF-S2 panel 17',
    pose: 'side hug facing camera, she tucks under his arm, both laughing', framing: 'vertical 3/4', setting: 'lit garba entrance arch', light: 'festive lights',
    her: H('Chaniya Choli', 'Navy', 'Cotton', 'bandhani print', 'navy bandhani chaniya choli with red mirror blouse'),
    him: H('Printed Ethnic Shirt', 'White', 'Cotton', 'indigo block print', 'white shirt with indigo block print'),
    tone: 'Oxidised Silver', colourStory: 'Navy bandhani · Red · Indigo', tags: ['hug'] },
  { id: 'garba-18', world: 'garba', title: 'Ivory Twirl, Navy Kurta Watch', ref: 'REF-S2 panel 18',
    pose: 'she twirls in the foreground, he watches smiling behind', framing: 'vertical full body', setting: 'garba courtyard', light: 'night warm',
    her: H('Chaniya Choli', 'Ivory', 'Cotton', 'multicolour embroidered border', 'ivory chaniya with multicolour embroidered border and kutch balloon-sleeve blouse'),
    him: H('Modern Kurta', 'Navy', 'Cotton', 'embroidered yoke', 'navy kurta with embroidered yoke'),
    tone: 'Oxidised Silver', colourStory: 'Ivory · Multicolour · Navy', tags: ['twirl'] },
  { id: 'garba-19', world: 'garba', title: 'Maroon Mirror Kurta, Ground Walk', ref: 'REF-S1 panel 4',
    pose: 'walking toward camera side by side, fingers linked, mid-laugh', framing: 'vertical full body', setting: 'garba ground walkway', light: 'dusk',
    her: H('Chaniya Choli', 'Maroon', 'Cotton', 'gota and mirror', 'maroon chaniya with gota and mirror work and mustard dupatta'),
    him: H('Modern Kurta', 'Maroon', 'Cotton', 'mirror work', 'maroon mirror-work kurta with ivory pants'),
    tone: 'Oxidised Silver', colourStory: 'Maroon · Mustard · Ivory', tags: ['walking'] },
  { id: 'garba-20', world: 'garba', title: 'Pink Pair Forehead Touch', ref: 'REF-S1 panel 6',
    pose: 'foreheads touching, eyes closed, dandiya sticks held together', framing: 'vertical waist-up', setting: 'garba ground night', light: 'soft night',
    her: H('Chaniya Choli', 'Hot Pink', 'Cotton', 'mirror work', 'hot pink mirror-work chaniya choli with white blouse'),
    him: H('Modern Kurta', 'White', 'Cotton', 'solid', 'white kurta'),
    layer: H('Traditional Layer', 'Pink', 'Cotton', 'bandhani print', 'pink bandhani scarf'),
    tone: 'Oxidised Silver', colourStory: 'Hot pink · White', tags: ['close'] },

  // ───────────── COLLEGE FEST (priority 2) ─────────────
  { id: 'college-fest-01', world: 'college-fest', title: 'Campus Corridor Mirror Fit Check', ref: 'REF-C1',
    pose: 'mirror selfie in a campus washroom mirror, she holds the phone, he stands behind her shoulder', framing: 'vertical 3/4 mirror', setting: 'college corridor mirror', light: 'daylight tube light',
    her: H('Lehenga', 'Lilac', 'Georgette', 'lightweight printed', 'lightweight lilac printed lehenga with white crop blouse'),
    him: H('Ethnic Shirt', 'White', 'Cotton', 'tonal embroidery', 'white ethnic shirt with tonal embroidery and beige trousers'),
    tone: 'Silver', colourStory: 'Lilac · White', tags: ['mirror-selfie'] },
  { id: 'college-fest-02', world: 'college-fest', title: 'Sharara on the Campus Lawn, Overhead', ref: 'REF-C2',
    pose: 'lying on the campus lawn side by side, laughing, shot from above', framing: 'overhead top-down', setting: 'campus lawn', light: 'afternoon sun',
    her: H('Sharara', 'Mint', 'Cotton', 'gota trim', 'mint sharara set with gota trim'),
    him: H('Printed Ethnic Shirt', 'Navy', 'Rayon', 'floral print', 'navy floral printed ethnic shirt'),
    tone: 'Silver', colourStory: 'Mint · Navy', tags: ['overhead'] },
  { id: 'college-fest-03', world: 'college-fest', title: 'Amphitheatre Steps, Saree Day', ref: 'REF-C3',
    pose: 'seated on amphitheatre steps, she photographs them on her phone, he leans in', framing: 'vertical full seated', setting: 'college amphitheatre steps', light: 'golden hour',
    her: H('Saree', 'Black', 'Georgette', 'sequin border', 'black georgette saree with sequin border and sleeveless blouse'),
    him: H('Modern Kurta', 'Ivory', 'Cotton', 'chikankari', 'ivory chikankari kurta with denim'),
    tone: 'Silver', colourStory: 'Black · Ivory', tags: ['seated', 'saree-day'] },
  { id: 'college-fest-04', world: 'college-fest', title: 'Anarkali Ferris-Wheel Laugh', ref: 'REF-C2 side panel',
    pose: 'she holds his cheeks laughing', framing: 'vertical waist-up', setting: 'fest ground ferris wheel at dusk', light: 'dusk neon',
    her: H('Anarkali', 'Mustard', 'Cotton', 'block print', 'mustard block-print anarkali with dupatta'),
    him: H('Modern Kurta', 'Olive', 'Cotton', 'embroidered placket', 'olive short kurta with embroidered placket'),
    tone: 'Oxidised Silver', colourStory: 'Mustard · Olive', tags: ['candid'] },
  { id: 'college-fest-05', world: 'college-fest', title: 'Pre-Draped Saree Walk Through Campus', ref: 'REF-S1 panel 2',
    pose: 'walking side by side through a campus corridor, chatting', framing: 'vertical full body', setting: 'arched college corridor', light: 'daylight',
    her: H('Pre-Draped Saree', 'Sage Green', 'Crepe', 'solid with embroidered blouse', 'sage green pre-draped saree with embroidered blouse'),
    him: H('Ethnic Shirt', 'Cream', 'Linen', 'solid mandarin', 'cream linen mandarin ethnic shirt'),
    tone: 'Silver', colourStory: 'Sage · Cream', tags: ['walking'] },
  { id: 'college-fest-06', world: 'college-fest', title: 'Gharara Stage-Side Selfie', ref: 'REF-S2 panel 11',
    pose: 'cheek-to-cheek selfie backstage', framing: 'vertical head-and-shoulders', setting: 'fest backstage lights', light: 'stage light',
    her: H('Gharara', 'Peach', 'Georgette', 'gota patti', 'peach gota-patti gharara set'),
    him: H('Printed Ethnic Shirt', 'Teal', 'Rayon', 'paisley print', 'teal paisley printed ethnic shirt'),
    tone: 'Gold', colourStory: 'Peach · Teal', tags: ['selfie'] },
  { id: 'college-fest-07', world: 'college-fest', title: 'Chaniya-Inspired Fest Twirl', ref: 'REF-S1 panel 8',
    pose: 'she twirls, he claps and cheers', framing: 'vertical full body', setting: 'college quad with bunting', light: 'late afternoon',
    her: H('Chaniya Choli', 'Yellow', 'Cotton', 'printed with mirror', 'yellow printed chaniya with mirror blouse'),
    him: H('Ethnic Shirt', 'White', 'Cotton', 'solid', 'white short ethnic shirt with rolled sleeves'),
    tone: 'Oxidised Silver', colourStory: 'Yellow · White', tags: ['twirl'] },
  { id: 'college-fest-08', world: 'college-fest', title: 'Library Steps Dupatta Fix', ref: 'REF-S1 panel 6',
    pose: 'he adjusts her dupatta on library steps', framing: 'vertical waist-up', setting: 'library entrance steps', light: 'soft daylight',
    her: H('Kurta Sets', 'Powder Blue', 'Cotton', 'chikankari', 'powder blue chikankari kurta set with dupatta'),
    him: H('Modern Kurta', 'White', 'Cotton', 'pintuck', 'white pintuck kurta'),
    tone: 'Silver', colourStory: 'Powder blue · White', tags: ['dupatta-adjust'] },
  { id: 'college-fest-09', world: 'college-fest', title: 'Canteen Table Lean', ref: 'REF-S2 panel 20',
    pose: 'seated across a canteen table leaning in, laughing', framing: 'vertical 3/4', setting: 'college canteen', light: 'window daylight',
    her: H('Sharara', 'Rani Pink', 'Rayon', 'mirror work', 'rani pink mirror-work sharara set'),
    him: H('Printed Ethnic Shirt', 'Black', 'Rayon', 'block print', 'black block-print ethnic shirt'),
    tone: 'Oxidised Silver', colourStory: 'Rani pink · Black', tags: ['seated'] },
  { id: 'college-fest-10', world: 'college-fest', title: 'Scooter Stop Outfit Check', ref: 'REF-C1 side panel',
    pose: 'standing beside a parked scooter holding hands, chest-down crop', framing: 'vertical detail crop', setting: 'campus parking', light: 'midday',
    her: H('Lehenga', 'Teal', 'Cotton', 'printed flared', 'teal printed flared lehenga'),
    him: H('Modern Kurta', 'Beige', 'Linen', 'solid', 'beige linen kurta'),
    tone: 'Oxidised Silver', colourStory: 'Teal · Beige', tags: ['hand-hold'] },
  { id: 'college-fest-11', world: 'college-fest', title: 'Anarkali Group-Photo Break', ref: 'REF-S1 panel 4',
    pose: 'side hug facing camera', framing: 'vertical 3/4', setting: 'fest stalls', light: 'evening',
    her: H('Anarkali', 'Maroon', 'Georgette', 'gota', 'maroon georgette anarkali with gota trims'),
    him: H('Festive Jacket', 'Beige', 'Cotton Silk', 'solid nehru', 'beige nehru jacket over white kurta'),
    tone: 'Gold', colourStory: 'Maroon · Beige', tags: ['hug'] },
  { id: 'college-fest-12', world: 'college-fest', title: 'Black Saree Stairwell Selfie', ref: 'REF-S2 panel 14',
    pose: 'stairwell mirror selfie', framing: 'vertical full body mirror', setting: 'college stairwell mirror', light: 'tube light',
    her: H('Pre-Draped Saree', 'Black', 'Georgette', 'sequin', 'black sequin pre-draped saree'),
    him: H('Embroidered Ethnic Shirt', 'Black', 'Cotton', 'rust hem embroidery', 'black shirt with rust embroidered hem'),
    tone: 'Silver', colourStory: 'Black · Rust', tags: ['mirror-selfie'] },
  { id: 'college-fest-13', world: 'college-fest', title: 'Kurta-Set Tree Shade Sit', ref: 'REF-C3',
    pose: 'seated under a tree on a low wall, she photographs, he leans', framing: 'vertical full seated', setting: 'campus tree shade', light: 'dappled light',
    her: H('Kurta Sets', 'Yellow', 'Cotton', 'block print', 'yellow block-print kurta set'),
    him: H('Printed Ethnic Shirt', 'White', 'Cotton', 'indigo block print', 'white indigo-print shirt'),
    tone: 'Oxidised Silver', colourStory: 'Yellow · Indigo', tags: ['seated'] },
  { id: 'college-fest-14', world: 'college-fest', title: 'Gharara Night Concert', ref: 'REF-S2 panel 13',
    pose: 'close embrace in concert crowd', framing: 'vertical waist-up', setting: 'fest concert crowd', light: 'stage light purple',
    her: H('Gharara', 'Emerald', 'Silk Blend', 'zari', 'emerald zari gharara set'),
    him: H('Modern Kurta', 'Black', 'Cotton', 'solid', 'black short kurta'),
    tone: 'Gold', colourStory: 'Emerald · Black', tags: ['night'] },
  { id: 'college-fest-15', world: 'college-fest', title: 'Printed Lehenga Hallway Walk', ref: 'REF-S1 panel 2',
    pose: 'walking away down a hallway, hand in hand', framing: 'vertical back view', setting: 'hostel hallway', light: 'evening',
    her: H('Lehenga', 'Coral', 'Cotton', 'floral print', 'coral floral printed lehenga'),
    him: H('Ethnic Shirt', 'Sage Green', 'Linen', 'solid', 'sage linen ethnic shirt'),
    tone: 'Silver', colourStory: 'Coral · Sage', tags: ['walking'] },
  { id: 'college-fest-16', world: 'college-fest', title: 'Sharara Rooftop Overhead', ref: 'REF-C2',
    pose: 'lying on rooftop mat, overhead', framing: 'overhead', setting: 'hostel rooftop', light: 'golden hour',
    her: H('Sharara', 'Ivory', 'Cotton', 'chikankari', 'ivory chikankari sharara set'),
    him: H('Embroidered Ethnic Shirt', 'Ivory', 'Silk Blend', 'tonal floral', 'ivory silk shirt with tonal floral embroidery'),
    tone: 'Silver', colourStory: 'Ivory on ivory', tags: ['overhead'] },
  { id: 'college-fest-17', world: 'college-fest', title: 'Anarkali Twirl, Phone Filming', ref: 'REF-S2 panel 18',
    pose: 'she twirls, he films on phone', framing: 'vertical full body', setting: 'college quad', light: 'afternoon',
    her: H('Anarkali', 'Rani Pink', 'Georgette', 'mirror yoke', 'rani pink anarkali with mirror yoke'),
    him: H('Modern Kurta', 'Mint', 'Cotton', 'embroidered placket', 'mint short kurta'),
    tone: 'Oxidised Silver', colourStory: 'Rani pink · Mint', tags: ['twirl'] },
  { id: 'college-fest-18', world: 'college-fest', title: 'Saree & Shirt Classroom Window', ref: 'REF-C1 side panel',
    pose: 'standing by classroom window shoulder to shoulder', framing: 'vertical nose-to-knee', setting: 'classroom window', light: 'window light',
    her: H('Saree', 'Mustard', 'Cotton', 'contrast border', 'mustard cotton saree with maroon border'),
    him: H('Printed Ethnic Shirt', 'Maroon', 'Rayon', 'small motif', 'maroon small-motif printed shirt'),
    tone: 'Gold', colourStory: 'Mustard · Maroon', tags: ['outfit-check'] },
  { id: 'college-fest-19', world: 'college-fest', title: 'Chaniya Dandiya Practice', ref: 'REF-S1 panel 5',
    pose: 'dandiya practice mid-strike', framing: 'vertical full body', setting: 'college ground', light: 'evening floodlight',
    her: H('Chaniya Choli', 'Navy', 'Cotton', 'mirror work', 'navy mirror chaniya with multicolour dupatta'),
    him: H('Printed Ethnic Shirt', 'Mustard', 'Rayon', 'floral print', 'mustard printed ethnic shirt'),
    tone: 'Oxidised Silver', colourStory: 'Navy · Mustard', tags: ['dandiya'] },
  { id: 'college-fest-20', world: 'college-fest', title: 'Lightweight Lehenga Bench Laugh', ref: 'REF-S2 panel 20',
    pose: 'seated on bench laughing, her head on his shoulder', framing: 'vertical full seated', setting: 'campus bench', light: 'evening',
    her: H('Lehenga', 'Powder Blue', 'Georgette', 'sequin', 'powder blue lightweight sequin lehenga'),
    him: H('Modern Kurta', 'Navy', 'Cotton', 'solid', 'navy short kurta'),
    tone: 'Silver', colourStory: 'Powder blue · Navy', tags: ['seated'] },

  // ───────────── DIWALI (priority 3) ─────────────
  { id: 'diwali-01', world: 'diwali', title: 'Diya-Lit Mirror Selfie at Home', ref: 'REF-C1', pose: 'mirror selfie in a hallway mirror, he behind her shoulder', framing: 'vertical 3/4 mirror', setting: 'home hallway with diyas', light: 'warm diya glow',
    her: H('Saree', 'Wine', 'Silk Blend', 'zari border', 'wine silk saree with zari border'), him: H('Festive Kurta Set', 'Cream', 'Cotton Silk', 'tonal embroidery', 'cream kurta set'), tone: 'Gold', colourStory: 'Wine · Cream', tags: ['mirror-selfie'] },
  { id: 'diwali-02', world: 'diwali', title: 'Rangoli Overhead', ref: 'REF-C2', pose: 'kneeling around a rangoli, shot overhead', framing: 'overhead', setting: 'courtyard rangoli with diyas', light: 'dusk',
    her: H('Lehenga', 'Emerald', 'Silk', 'zari', 'emerald silk lehenga'), him: H('Modern Kurta', 'Ivory', 'Cotton Silk', 'solid', 'ivory kurta'), tone: 'Gold', colourStory: 'Emerald · Ivory', tags: ['overhead'] },
  { id: 'diwali-03', world: 'diwali', title: 'Diya Steps Glow', ref: 'REF-C3', pose: 'seated on steps lined with diyas, she photographs them', framing: 'vertical full seated', setting: 'home steps with diyas', light: 'diya glow',
    her: H('Anarkali', 'Ivory', 'Georgette', 'gold sequin', 'ivory anarkali with gold sequins'), him: H('Modern Kurta', 'Mustard', 'Cotton Silk', 'embroidered neckline', 'mustard kurta'), tone: 'Gold', colourStory: 'Ivory · Mustard', tags: ['seated'] },
  { id: 'diwali-04', world: 'diwali', title: 'Phuljhadi Face-Cup', ref: 'REF-C2 side panel', pose: 'she cups his face holding a sparkler', framing: 'vertical waist-up', setting: 'terrace', light: 'sparkler light',
    her: H('Sharara', 'Red', 'Georgette', 'gota', 'red gota sharara'), him: H('Festive Kurta Set', 'White', 'Cotton', 'solid', 'white kurta set'), tone: 'Gold', colourStory: 'Red · White', tags: ['sparkler'] },
  { id: 'diwali-05', world: 'diwali', title: 'Marigold Door Hand-Hold', ref: 'REF-C1 side panel', pose: 'holding hands, chest-down crop', framing: 'detail crop', setting: 'marigold-decorated doorway', light: 'evening',
    her: H('Pre-Draped Saree', 'Mustard', 'Silk Blend', 'zari', 'mustard pre-draped saree'), him: H('Modern Kurta', 'Maroon', 'Cotton Silk', 'solid', 'maroon kurta'), tone: 'Gold', colourStory: 'Mustard · Maroon', tags: ['hand-hold'] },
  { id: 'diwali-06', world: 'diwali', title: 'Balcony Lights Shoulder-to-Shoulder', ref: 'REF-C1 side panel', pose: 'shoulder to shoulder at balcony', framing: 'vertical nose-to-knee', setting: 'balcony fairy lights', light: 'night',
    her: H('Kurta Sets', 'Rani Pink', 'Silk Blend', 'gota', 'rani pink kurta set'), him: H('Festive Jacket', 'Navy', 'Silk Blend', 'subtle embroidery', 'navy jacket over cream kurta'), tone: 'Gold', colourStory: 'Rani pink · Navy', tags: ['outfit-check'] },
  { id: 'diwali-07', world: 'diwali', title: 'Walking Past the Lantern Lane', ref: 'REF-S1 panel 2', pose: 'walking away hand in hand', framing: 'back view', setting: 'lantern-lit lane', light: 'night lanterns',
    her: H('Lehenga', 'Maroon', 'Velvet', 'zari', 'maroon velvet lehenga'), him: H('Festive Kurta Set', 'Black', 'Cotton Silk', 'tonal', 'black kurta set'), tone: 'Gold', colourStory: 'Maroon · Black', tags: ['walking'] },
  { id: 'diwali-08', world: 'diwali', title: 'Diya Lighting Together', ref: 'REF-S1 panel 6', pose: 'lighting a diya together, heads close', framing: 'vertical waist-up', setting: 'home altar', light: 'diya',
    her: H('Saree', 'Royal Blue', 'Silk', 'zari', 'royal blue silk saree'), him: H('Modern Kurta', 'Cream', 'Cotton Silk', 'solid', 'cream kurta'), tone: 'Gold', colourStory: 'Royal blue · Cream', tags: ['candid'] },
  { id: 'diwali-09', world: 'diwali', title: 'Gharara Twirl on the Terrace', ref: 'REF-S2 panel 16', pose: 'twirl guided by his hand', framing: 'full body', setting: 'terrace lights', light: 'night',
    her: H('Gharara', 'Wine', 'Silk Blend', 'zari', 'wine gharara'), him: H('Modern Kurta', 'Ivory', 'Cotton', 'solid', 'ivory kurta'), tone: 'Gold', colourStory: 'Wine · Ivory', tags: ['twirl'] },
  { id: 'diwali-10', world: 'diwali', title: 'Cheek-to-Cheek Sparkler Selfie', ref: 'REF-S2 panel 11', pose: 'selfie with sparklers', framing: 'head-and-shoulders', setting: 'rooftop', light: 'sparkler',
    her: H('Anarkali', 'Emerald', 'Georgette', 'zari', 'emerald anarkali'), him: H('Modern Kurta', 'Black', 'Cotton', 'solid', 'black kurta'), tone: 'Gold', colourStory: 'Emerald · Black', tags: ['selfie'] },
  { id: 'diwali-11', world: 'diwali', title: 'Sweets Box Sofa Laugh', ref: 'REF-S2 panel 20', pose: 'seated on sofa sharing sweets', framing: 'full seated', setting: 'living room', light: 'warm lamp',
    her: H('Kurta Sets', 'Mustard', 'Silk Blend', 'zari', 'mustard kurta set'), him: H('Printed Ethnic Shirt', 'Wine', 'Rayon', 'paisley', 'wine paisley shirt'), tone: 'Gold', colourStory: 'Mustard · Wine', tags: ['seated'] },
  { id: 'diwali-12', world: 'diwali', title: 'Fairy Light Embrace', ref: 'REF-S2 panel 13', pose: 'embrace under lights', framing: 'waist-up', setting: 'fairy light curtain', light: 'night',
    her: H('Saree', 'Black', 'Georgette', 'gold border', 'black saree with gold border'), him: H('Festive Kurta Set', 'Ivory', 'Cotton Silk', 'tonal', 'ivory kurta set'), tone: 'Gold', colourStory: 'Black · Ivory', tags: ['embrace'] },
  { id: 'diwali-13', world: 'diwali', title: 'Pre-Draped Lift Selfie', ref: 'REF-S2 panel 14', pose: 'lift mirror selfie', framing: 'mirror full body', setting: 'lift', light: 'cool',
    her: H('Pre-Draped Saree', 'Peach', 'Georgette', 'sequin', 'peach pre-draped saree'), him: H('Ethnic Shirt', 'Sage Green', 'Cotton', 'solid', 'sage ethnic shirt'), tone: 'Gold', colourStory: 'Peach · Sage', tags: ['mirror-selfie'] },
  { id: 'diwali-14', world: 'diwali', title: 'Courtyard Bench Diyas', ref: 'REF-S2 panel 15', pose: 'bench seated whispering', framing: 'full seated', setting: 'courtyard', light: 'diyas',
    her: H('Sharara', 'Mint', 'Georgette', 'sequin', 'mint sharara'), him: H('Modern Kurta', 'Navy', 'Cotton Silk', 'solid', 'navy kurta'), tone: 'Gold', colourStory: 'Mint · Navy', tags: ['seated'] },
  { id: 'diwali-15', world: 'diwali', title: 'Lantern Hand Twirl', ref: 'REF-S2 panel 16', pose: 'both hands spin', framing: 'full body', setting: 'lantern courtyard', light: 'night',
    her: H('Lehenga', 'Gold', 'Tissue', 'zari', 'gold tissue lehenga'), him: H('Festive Kurta Set', 'Black', 'Cotton Silk', 'solid', 'black kurta set'), tone: 'Gold', colourStory: 'Gold · Black', tags: ['twirl'] },
  { id: 'diwali-16', world: 'diwali', title: 'Doorway Side Hug', ref: 'REF-S2 panel 17', pose: 'side hug at doorway', framing: '3/4', setting: 'decorated door', light: 'evening',
    her: H('Anarkali', 'Red', 'Georgette', 'gota', 'red anarkali'), him: H('Festive Jacket', 'Cream', 'Silk Blend', 'subtle embroidery', 'cream jacket over kurta'), tone: 'Gold', colourStory: 'Red · Cream', tags: ['hug'] },
  { id: 'diwali-17', world: 'diwali', title: 'Rangoli Twirl Watch', ref: 'REF-S2 panel 18', pose: 'she twirls, he watches', framing: 'full body', setting: 'rangoli courtyard', light: 'dusk',
    her: H('Lehenga', 'Lilac', 'Georgette', 'sequin', 'lilac sequin lehenga'), him: H('Modern Kurta', 'Ivory', 'Cotton', 'solid', 'ivory kurta'), tone: 'Silver', colourStory: 'Lilac · Ivory', tags: ['twirl'] },
  { id: 'diwali-18', world: 'diwali', title: 'Market Lights Walk', ref: 'REF-S1 panel 4', pose: 'walking toward camera', framing: 'full body', setting: 'lit market', light: 'night',
    her: H('Kurta Sets', 'Wine', 'Silk Blend', 'zari', 'wine kurta set'), him: H('Modern Kurta', 'Beige', 'Linen', 'solid', 'beige kurta'), tone: 'Gold', colourStory: 'Wine · Beige', tags: ['walking'] },
  { id: 'diwali-19', world: 'diwali', title: 'Forehead Touch by the Diyas', ref: 'REF-S1 panel 6', pose: 'forehead touch', framing: 'waist-up', setting: 'diya windowsill', light: 'diya',
    her: H('Saree', 'Rani Pink', 'Silk', 'zari', 'rani pink silk saree'), him: H('Modern Kurta', 'Ivory', 'Cotton Silk', 'solid', 'ivory kurta'), tone: 'Gold', colourStory: 'Rani pink · Ivory', tags: ['close'] },
  { id: 'diwali-20', world: 'diwali', title: 'Diwali Lawn Overhead', ref: 'REF-C2', pose: 'lying on lawn with diyas, overhead', framing: 'overhead', setting: 'lawn', light: 'dusk',
    her: H('Sharara', 'Ivory', 'Georgette', 'gold sequin', 'ivory sequin sharara'), him: H('Festive Kurta Set', 'Maroon', 'Cotton Silk', 'solid', 'maroon kurta set'), tone: 'Gold', colourStory: 'Ivory · Maroon', tags: ['overhead'] },

  // ───────────── FESTIVE PARTY (priority 4) ─────────────
  { id: 'festive-party-01', world: 'festive-party', title: 'Black Sequin Party Mirror Selfie', ref: 'REF-C1', pose: 'mirror selfie', framing: '3/4 mirror', setting: 'party venue washroom mirror', light: 'moody',
    her: H('Saree', 'Black', 'Georgette', 'sequin', 'black sequin saree'), him: H('Modern Kurta', 'Black', 'Georgette', 'mirror sequin', 'black mirror-sequin kurta'), tone: 'Silver', colourStory: 'Black-on-black', tags: ['mirror-selfie'] },
  { id: 'festive-party-02', world: 'festive-party', title: 'Rooftop Overhead in Emerald', ref: 'REF-C2', pose: 'overhead lying', framing: 'overhead', setting: 'rooftop lounge', light: 'dusk',
    her: H('Lehenga', 'Emerald', 'Velvet', 'sequin', 'emerald velvet lehenga'), him: H('Festive Jacket', 'Black', 'Velvet', 'solid', 'black velvet jacket'), tone: 'Gold', colourStory: 'Emerald · Black', tags: ['overhead'] },
  { id: 'festive-party-03', world: 'festive-party', title: 'Staircase Sit', ref: 'REF-C3', pose: 'seated on staircase', framing: 'full seated', setting: 'wooden staircase', light: 'warm',
    her: H('Sharara', 'Wine', 'Georgette', 'sequin', 'wine sequin sharara'), him: H('Modern Kurta', 'Cream', 'Cotton Silk', 'solid', 'cream kurta'), tone: 'Gold', colourStory: 'Wine · Cream', tags: ['seated'] },
  { id: 'festive-party-04', world: 'festive-party', title: 'Red Jacket Laugh', ref: 'REF-C2 side panel', pose: 'face-cup laugh', framing: 'waist-up', setting: 'party lights', light: 'night',
    her: H('Pre-Draped Saree', 'Black', 'Satin', 'solid', 'black satin pre-draped saree'), him: H('Festive Jacket', 'Red', 'Brocade', 'brocade', 'red brocade jacket over black'), tone: 'Silver', colourStory: 'Black · Red brocade', tags: ['candid'] },
  { id: 'festive-party-05', world: 'festive-party', title: 'Lounge Hand-Hold Crop', ref: 'REF-C1 side panel', pose: 'hand-hold crop', framing: 'detail crop', setting: 'lounge', light: 'warm',
    her: H('Lehenga', 'Silver', 'Tissue', 'sequin', 'silver tissue lehenga'), him: H('Modern Kurta', 'Navy', 'Silk Blend', 'solid', 'navy kurta'), tone: 'Silver', colourStory: 'Silver · Navy', tags: ['hand-hold'] },
  { id: 'festive-party-06', world: 'festive-party', title: 'Bar Counter Shoulder Line', ref: 'REF-C1 side panel', pose: 'shoulder to shoulder', framing: 'nose-to-knee', setting: 'party bar counter', light: 'moody',
    her: H('Anarkali', 'Black', 'Georgette', 'gold', 'black anarkali with gold'), him: H('Embroidered Ethnic Shirt', 'Ivory', 'Silk Blend', 'tonal', 'ivory embroidered shirt'), tone: 'Gold', colourStory: 'Black · Ivory', tags: ['outfit-check'] },
  { id: 'festive-party-07', world: 'festive-party', title: 'Corridor Walk-Out', ref: 'REF-S1 panel 2', pose: 'walking away', framing: 'back view', setting: 'hotel corridor', light: 'warm',
    her: H('Saree', 'Emerald', 'Satin', 'solid', 'emerald satin saree'), him: H('Festive Kurta Set', 'Black', 'Cotton Silk', 'solid', 'black kurta set'), tone: 'Gold', colourStory: 'Emerald · Black', tags: ['walking'] },
  { id: 'festive-party-08', world: 'festive-party', title: 'Earring Fix', ref: 'REF-S1 panel 6', pose: 'he helps fix her earring', framing: 'waist-up', setting: 'party hallway', light: 'warm',
    her: H('Sharara', 'Black', 'Georgette', 'mirror', 'black mirror sharara'), him: H('Printed Ethnic Shirt', 'Teal', 'Rayon', 'paisley', 'teal printed shirt'), tone: 'Silver', colourStory: 'Black · Teal', tags: ['candid'] },
  { id: 'festive-party-09', world: 'festive-party', title: 'Dance Floor Spin', ref: 'REF-S2 panel 16', pose: 'spin on dance floor', framing: 'full body', setting: 'dance floor', light: 'party lights',
    her: H('Lehenga', 'Wine', 'Velvet', 'sequin', 'wine velvet lehenga'), him: H('Modern Kurta', 'Black', 'Cotton', 'solid', 'black kurta'), tone: 'Gold', colourStory: 'Wine · Black', tags: ['twirl'] },
  { id: 'festive-party-10', world: 'festive-party', title: 'Flash Selfie', ref: 'REF-S2 panel 11', pose: 'flash selfie', framing: 'head-and-shoulders', setting: 'party', light: 'flash',
    her: H('Pre-Draped Saree', 'Silver', 'Georgette', 'sequin', 'silver sequin pre-draped saree'), him: H('Embroidered Ethnic Shirt', 'Black', 'Cotton', 'sequin dots', 'black sequin-dot shirt'), tone: 'Silver', colourStory: 'Silver · Black', tags: ['selfie'] },
  { id: 'festive-party-11', world: 'festive-party', title: 'Couch Laugh', ref: 'REF-S2 panel 20', pose: 'seated laughing', framing: 'full seated', setting: 'house party couch', light: 'lamp',
    her: H('Kurta Sets', 'Emerald', 'Silk Blend', 'sequin', 'emerald kurta set'), him: H('Modern Kurta', 'Ivory', 'Cotton', 'solid', 'ivory kurta'), tone: 'Gold', colourStory: 'Emerald · Ivory', tags: ['seated'] },
  { id: 'festive-party-12', world: 'festive-party', title: 'Terrace Embrace', ref: 'REF-S2 panel 13', pose: 'embrace', framing: 'waist-up', setting: 'terrace lights', light: 'night',
    her: H('Gharara', 'Black', 'Georgette', 'gold', 'black gold gharara'), him: H('Festive Jacket', 'Ivory', 'Silk Blend', 'subtle embroidery', 'ivory jacket'), tone: 'Gold', colourStory: 'Black · Ivory', tags: ['embrace'] },
  { id: 'festive-party-13', world: 'festive-party', title: 'Gold Lift Mirror', ref: 'REF-S2 panel 14', pose: 'lift mirror selfie', framing: 'mirror full', setting: 'brass lift', light: 'warm',
    her: H('Saree', 'Gold', 'Tissue', 'zari', 'gold tissue saree'), him: H('Modern Kurta', 'Black', 'Cotton Silk', 'solid', 'black kurta'), tone: 'Gold', colourStory: 'Gold · Black', tags: ['mirror-selfie'] },
  { id: 'festive-party-14', world: 'festive-party', title: 'Poolside Bench', ref: 'REF-S2 panel 15', pose: 'bench whisper', framing: 'full seated', setting: 'poolside bench', light: 'night',
    her: H('Anarkali', 'Navy', 'Georgette', 'sequin', 'navy sequin anarkali'), him: H('Ethnic Shirt', 'White', 'Linen', 'solid', 'white linen ethnic shirt'), tone: 'Silver', colourStory: 'Navy · White', tags: ['seated'] },
  { id: 'festive-party-15', world: 'festive-party', title: 'Two-Hand Spin', ref: 'REF-S2 panel 16', pose: 'two-hand spin', framing: 'full body', setting: 'banquet lawn', light: 'fairy',
    her: H('Lehenga', 'Rani Pink', 'Georgette', 'sequin', 'rani pink sequin lehenga'), him: H('Festive Kurta Set', 'Ivory', 'Cotton Silk', 'solid', 'ivory kurta set'), tone: 'Gold', colourStory: 'Rani pink · Ivory', tags: ['twirl'] },
  { id: 'festive-party-16', world: 'festive-party', title: 'Entrance Side Hug', ref: 'REF-S2 panel 17', pose: 'side hug', framing: '3/4', setting: 'venue entrance', light: 'night',
    her: H('Sharara', 'Emerald', 'Georgette', 'sequin', 'emerald sequin sharara'), him: H('Modern Kurta', 'Black', 'Cotton', 'solid', 'black kurta'), tone: 'Gold', colourStory: 'Emerald · Black', tags: ['hug'] },
  { id: 'festive-party-17', world: 'festive-party', title: 'Lawn Twirl Watch', ref: 'REF-S2 panel 18', pose: 'twirl watch', framing: 'full body', setting: 'party lawn', light: 'dusk',
    her: H('Lehenga', 'Black', 'Georgette', 'sequin', 'black sequin lehenga'), him: H('Embroidered Ethnic Shirt', 'Ivory', 'Silk Blend', 'tonal', 'ivory embroidered shirt'), tone: 'Silver', colourStory: 'Black · Ivory', tags: ['twirl'] },
  { id: 'festive-party-18', world: 'festive-party', title: 'Arrival Walk', ref: 'REF-S1 panel 4', pose: 'walking toward camera', framing: 'full body', setting: 'venue driveway', light: 'night',
    her: H('Pre-Draped Saree', 'Wine', 'Satin', 'solid', 'wine satin pre-draped saree'), him: H('Festive Jacket', 'Navy', 'Silk Blend', 'solid', 'navy jacket'), tone: 'Gold', colourStory: 'Wine · Navy', tags: ['walking'] },
  { id: 'festive-party-19', world: 'festive-party', title: 'Candlelit Forehead Touch', ref: 'REF-S1 panel 6', pose: 'forehead touch', framing: 'waist-up', setting: 'candle-lit table', light: 'candle',
    her: H('Saree', 'Wine', 'Georgette', 'sequin', 'wine sequin saree'), him: H('Modern Kurta', 'Black', 'Georgette', 'mirror sequin', 'black sequin kurta'), tone: 'Silver', colourStory: 'Wine · Black', tags: ['close'] },
  { id: 'festive-party-20', world: 'festive-party', title: 'Rooftop Rug Overhead', ref: 'REF-C2', pose: 'overhead lying on rug', framing: 'overhead', setting: 'rooftop rug', light: 'dusk',
    her: H('Lehenga', 'Silver', 'Georgette', 'mirror', 'silver mirror lehenga'), him: H('Printed Ethnic Shirt', 'Black', 'Rayon', 'block print', 'black printed shirt'), tone: 'Silver', colourStory: 'Silver · Black', tags: ['overhead'] },

  // ───────────── TRADITIONAL (priority 5) ─────────────
  { id: 'traditional-01', world: 'traditional', title: 'Temple Town Mirror Selfie', ref: 'REF-C1', pose: 'mirror selfie', framing: '3/4 mirror', setting: 'old haveli mirror', light: 'window',
    her: H('Saree', 'Mustard', 'Silk', 'temple border', 'mustard silk saree with temple border'), him: H('Festive Kurta Set', 'Ivory', 'Cotton Silk', 'solid', 'ivory kurta set'), tone: 'Gold', colourStory: 'Mustard · Ivory', tags: ['mirror-selfie'] },
  { id: 'traditional-02', world: 'traditional', title: 'Haveli Floor Overhead', ref: 'REF-C2', pose: 'overhead lying', framing: 'overhead', setting: 'patterned haveli floor', light: 'sun',
    her: H('Lehenga', 'Maroon', 'Silk', 'bandhani', 'maroon bandhani silk lehenga'), him: H('Modern Kurta', 'Cream', 'Cotton', 'solid', 'cream kurta'), tone: 'Gold', colourStory: 'Maroon · Cream', tags: ['overhead'] },
  { id: 'traditional-03', world: 'traditional', title: 'Ghat Steps', ref: 'REF-C3', pose: 'seated on ghat steps', framing: 'full seated', setting: 'river ghat', light: 'golden hour',
    her: H('Saree', 'Red', 'Cotton', 'contrast border', 'red cotton saree with white border'), him: H('Modern Kurta', 'White', 'Cotton', 'solid', 'white kurta'), tone: 'Gold', colourStory: 'Red · White', tags: ['seated'] },
  { id: 'traditional-04', world: 'traditional', title: 'Courtyard Laugh', ref: 'REF-C2 side panel', pose: 'face-cup laugh', framing: 'waist-up', setting: 'courtyard', light: 'day',
    her: H('Anarkali', 'Teal', 'Cotton', 'block print', 'teal block-print anarkali'), him: H('Festive Kurta Set', 'Beige', 'Linen', 'solid', 'beige kurta set'), tone: 'Oxidised Silver', colourStory: 'Teal · Beige', tags: ['candid'] },
  { id: 'traditional-05', world: 'traditional', title: 'Temple Door Hand-Hold', ref: 'REF-C1 side panel', pose: 'hand-hold crop', framing: 'detail crop', setting: 'temple door', light: 'day',
    her: H('Saree', 'Emerald', 'Silk', 'zari', 'emerald silk saree'), him: H('Festive Kurta Set', 'Cream', 'Cotton Silk', 'solid', 'cream kurta set'), tone: 'Gold', colourStory: 'Emerald · Cream', tags: ['hand-hold'] },
  { id: 'traditional-06', world: 'traditional', title: 'Jharokha Shoulder Line', ref: 'REF-C1 side panel', pose: 'shoulder to shoulder', framing: 'nose-to-knee', setting: 'jharokha window', light: 'window',
    her: H('Kurta Sets', 'Indigo', 'Cotton', 'block print', 'indigo block-print kurta set'), him: H('Modern Kurta', 'White', 'Cotton', 'solid', 'white kurta'), tone: 'Oxidised Silver', colourStory: 'Indigo · White', tags: ['outfit-check'] },
  { id: 'traditional-07', world: 'traditional', title: 'Fort Lane Walk', ref: 'REF-S1 panel 2', pose: 'walking away', framing: 'back view', setting: 'fort lane', light: 'afternoon',
    her: H('Lehenga', 'Mustard', 'Cotton', 'bandhani', 'mustard bandhani lehenga'), him: H('Modern Kurta', 'Maroon', 'Cotton', 'solid', 'maroon kurta'), tone: 'Oxidised Silver', colourStory: 'Mustard · Maroon', tags: ['walking'] },
  { id: 'traditional-08', world: 'traditional', title: 'Pallu Fix at the Temple', ref: 'REF-S1 panel 6', pose: 'he adjusts her pallu', framing: 'waist-up', setting: 'temple corridor', light: 'soft',
    her: H('Saree', 'Ivory', 'Cotton', 'gold border', 'ivory kasavu-style saree with gold border'), him: H('Modern Kurta', 'Ivory', 'Cotton', 'solid', 'ivory kurta'), tone: 'Gold', colourStory: 'Ivory · Gold', tags: ['dupatta-adjust'] },
  { id: 'traditional-09', world: 'traditional', title: 'Courtyard Spin', ref: 'REF-S2 panel 16', pose: 'twirl', framing: 'full body', setting: 'haveli courtyard', light: 'day',
    her: H('Anarkali', 'Red', 'Cotton', 'gota', 'red gota anarkali'), him: H('Festive Kurta Set', 'Ivory', 'Cotton', 'solid', 'ivory kurta set'), tone: 'Gold', colourStory: 'Red · Ivory', tags: ['twirl'] },
  { id: 'traditional-10', world: 'traditional', title: 'Temple Selfie', ref: 'REF-S2 panel 11', pose: 'selfie', framing: 'head-and-shoulders', setting: 'temple steps', light: 'day',
    her: H('Saree', 'Rani Pink', 'Silk', 'temple border', 'rani pink silk saree'), him: H('Modern Kurta', 'Mustard', 'Cotton', 'solid', 'mustard kurta'), tone: 'Gold', colourStory: 'Rani pink · Mustard', tags: ['selfie'] },
  { id: 'traditional-11', world: 'traditional', title: 'Jhoola Laugh', ref: 'REF-S2 panel 20', pose: 'seated on jhoola laughing', framing: 'full seated', setting: 'wooden jhoola', light: 'day',
    her: H('Lehenga', 'Green', 'Cotton', 'block print', 'green block-print lehenga'), him: H('Modern Kurta', 'Cream', 'Linen', 'solid', 'cream kurta'), tone: 'Oxidised Silver', colourStory: 'Green · Cream', tags: ['seated'] },
  { id: 'traditional-12', world: 'traditional', title: 'Archway Embrace', ref: 'REF-S2 panel 13', pose: 'embrace', framing: 'waist-up', setting: 'stone archway', light: 'dusk',
    her: H('Saree', 'Maroon', 'Silk', 'zari', 'maroon silk saree'), him: H('Festive Kurta Set', 'Ivory', 'Cotton Silk', 'solid', 'ivory kurta set'), tone: 'Gold', colourStory: 'Maroon · Ivory', tags: ['embrace'] },
  { id: 'traditional-13', world: 'traditional', title: 'Heirloom Mirror', ref: 'REF-S2 panel 14', pose: 'mirror selfie', framing: 'mirror full', setting: 'carved mirror', light: 'warm',
    her: H('Pre-Draped Saree', 'Mustard', 'Silk Blend', 'zari', 'mustard pre-draped saree'), him: H('Modern Kurta', 'Green', 'Cotton', 'solid', 'green kurta'), tone: 'Gold', colourStory: 'Mustard · Green', tags: ['mirror-selfie'] },
  { id: 'traditional-14', world: 'traditional', title: 'Stone Bench', ref: 'REF-S2 panel 15', pose: 'bench seated', framing: 'full seated', setting: 'stone bench', light: 'evening',
    her: H('Kurta Sets', 'Maroon', 'Cotton', 'gota', 'maroon kurta set'), him: H('Festive Kurta Set', 'Beige', 'Linen', 'solid', 'beige kurta set'), tone: 'Gold', colourStory: 'Maroon · Beige', tags: ['seated'] },
  { id: 'traditional-15', world: 'traditional', title: 'Hand Spin Courtyard', ref: 'REF-S2 panel 16', pose: 'two-hand spin', framing: 'full body', setting: 'courtyard', light: 'day',
    her: H('Lehenga', 'Royal Blue', 'Silk', 'bandhani', 'royal blue bandhani lehenga'), him: H('Modern Kurta', 'White', 'Cotton', 'solid', 'white kurta'), tone: 'Oxidised Silver', colourStory: 'Royal blue · White', tags: ['twirl'] },
  { id: 'traditional-16', world: 'traditional', title: 'Gate Side Hug', ref: 'REF-S2 panel 17', pose: 'side hug', framing: '3/4', setting: 'old gate', light: 'day',
    her: H('Anarkali', 'Mustard', 'Cotton', 'block print', 'mustard anarkali'), him: H('Modern Kurta', 'Indigo', 'Cotton', 'block print', 'indigo kurta'), tone: 'Oxidised Silver', colourStory: 'Mustard · Indigo', tags: ['hug'] },
  { id: 'traditional-17', world: 'traditional', title: 'Temple Twirl Watch', ref: 'REF-S2 panel 18', pose: 'twirl watch', framing: 'full body', setting: 'temple lawn', light: 'dusk',
    her: H('Lehenga', 'Red', 'Cotton', 'bandhani', 'red bandhani lehenga'), him: H('Modern Kurta', 'Cream', 'Cotton', 'solid', 'cream kurta'), tone: 'Oxidised Silver', colourStory: 'Red · Cream', tags: ['twirl'] },
  { id: 'traditional-18', world: 'traditional', title: 'Bazaar Walk', ref: 'REF-S1 panel 4', pose: 'walking toward camera', framing: 'full body', setting: 'old bazaar', light: 'day',
    her: H('Saree', 'Green', 'Cotton', 'contrast border', 'green cotton saree'), him: H('Modern Kurta', 'White', 'Cotton', 'solid', 'white kurta'), tone: 'Gold', colourStory: 'Green · White', tags: ['walking'] },
  { id: 'traditional-19', world: 'traditional', title: 'Aarti Forehead Touch', ref: 'REF-S1 panel 6', pose: 'forehead touch', framing: 'waist-up', setting: 'temple lamps', light: 'lamp',
    her: H('Saree', 'Red', 'Silk', 'zari', 'red silk saree'), him: H('Modern Kurta', 'Ivory', 'Cotton Silk', 'solid', 'ivory kurta'), tone: 'Gold', colourStory: 'Red · Ivory', tags: ['close'] },
  { id: 'traditional-20', world: 'traditional', title: 'Courtyard Overhead', ref: 'REF-C2', pose: 'overhead lying', framing: 'overhead', setting: 'courtyard tiles', light: 'sun',
    her: H('Lehenga', 'Ivory', 'Cotton', 'block print', 'ivory block-print lehenga'), him: H('Modern Kurta', 'Maroon', 'Cotton', 'solid', 'maroon kurta'), tone: 'Oxidised Silver', colourStory: 'Ivory · Maroon', tags: ['overhead'] },
];
