// 100 VIRAAS couple looks — exactly 20 per public world.
// Each look is anchored to a supplied reference (REF-C1..C3 individual screenshots, REF-S1/S2 sheet panels)
// and records the outfit + pose + framing language to recreate. `her`/`him` drive the linked products,
// so the couple image and the linked catalog products always describe the same garments.
//
// Fields: id, world, title, ref, pose, framing, setting, light, her{cat,colour,fabric,detail,desc},
//         him{cat,colour,fabric,detail,desc}, layer (optional men's stole/dupatta), tone (jewellery metal),
//         colourStory, tags

const H = (cat, colour, fabric, detail, desc) => ({ cat, colour, fabric, detail, desc });

export const WORLDS = [
  { slug: 'garba', name: 'Garba', long: 'Garba / Navratri', blurb: 'Nine nights of mirror work, bandhani and twirl-ready flare.' },
  { slug: 'college-fest', name: 'College Fest', long: 'College Fest', blurb: 'Light, move-all-day festive looks for campus ethnic day.' },
  { slug: 'diwali', name: 'Diwali', long: 'Diwali', blurb: 'Diya-lit silks, soft gold and house-party ready drapes.' },
  { slug: 'festive-party', name: 'Festive Party', long: 'Festive Party', blurb: 'After-dark sequins, jewel tones and black-on-black.' },
  { slug: 'traditional', name: 'Traditional', long: 'Traditional', blurb: 'Handloom, temple borders and heirloom-inspired styling — worn young.' },
];

export const COUPLES = [
  // ───────────── GARBA / NAVRATRI (priority 1) ─────────────
  { id: 'garba-01', world: 'garba', title: 'Ivory Mirror Lehenga, Festive Steps Selfie', ref: 'GARBA-REF-01',
    referenceNumber: 1,
    pose: 'both sitting very close together on festive steps, bodies relaxed and slightly angled toward each other, she holds a smartphone in front of her face for a selfie, he leans his face toward her affectionately', poseDescription: 'both sitting very close together on festive steps, bodies relaxed and slightly angled toward each other, she holds a smartphone in front of her face for a selfie, he leans his face toward her affectionately',
    framing: 'vertical close to medium portrait, couple large in frame, not a distant full-body catalogue shot', framingDescription: 'vertical close to medium portrait, couple large in frame, not a distant full-body catalogue shot',
    setting: 'traditional courtyard or haveli-style festive setting with warm diyas and soft decorative lights', environmentDescription: 'traditional courtyard or haveli-style festive setting with warm diyas and soft decorative lights', light: 'warm golden festive evening light',
    her: H('Lehenga', 'Ivory', 'Georgette', 'mirror-work blouse', 'ivory heavily mirror-worked and sequinned lehenga with a fitted ivory embellished blouse and a matching dupatta'),
    him: H('Modern Kurta', 'Ivory', 'Cotton', 'embroidered festive', 'ivory embroidered festive kurta with light blue relaxed denim jeans'),
    outfitDescription: 'Ivory mirror-work lehenga and embellished blouse with dupatta; ivory embroidered kurta with light blue jeans', qaStatus: 'GENERATED',
    tone: 'Silver', colourStory: 'Ivory · Ivory', tags: ['seated','selfie','mirror-work'] },
  { id: 'garba-02', world: 'garba', title: 'Overhead on the Festive Floor', ref: 'GARBA-REF-02',
    referenceNumber: 2,
    pose: 'true birds-eye overhead view with the camera directly above them, both lying beside each other looking upward, bodies arranged diagonally within the frame, relaxed natural pose', poseDescription: 'true birds-eye overhead view with the camera directly above them, both lying beside each other looking upward, bodies arranged diagonally within the frame, relaxed natural pose',
    framing: 'true birds-eye overhead photograph, camera directly above, not eye level', framingDescription: 'true birds-eye overhead photograph, camera directly above, not eye level',
    setting: 'outdoor floor-level festive location', environmentDescription: 'outdoor floor-level festive location', light: 'soft festive daylight',
    her: H('Lehenga', 'Black', 'Silk Blend', 'gold motif with white blouse', 'black lehenga with gold and metallic motifs, a fitted white long-sleeve blouse and a traditional dupatta drape'),
    him: H('Modern Kurta', 'Black', 'Cotton', 'with ivory patterned stole', 'black festive kurta with an ivory patterned stole and a light lower garment'),
    outfitDescription: 'Black lehenga with gold motifs and white long-sleeve blouse; black kurta with ivory stole', qaStatus: 'GENERATED',
    tone: 'Gold', colourStory: 'Black · Ivory', tags: ['overhead','lying'] },
  { id: 'garba-03', world: 'garba', title: 'Hot Pink Lehenga Store Mirror Selfie', ref: 'GARBA-REF-03',
    referenceNumber: 3,
    pose: 'mirror selfie, she holds the phone in front of the mirror, he stands close behind and beside her with one arm around her waist, their bodies crop naturally at the edges', poseDescription: 'mirror selfie, she holds the phone in front of the mirror, he stands close behind and beside her with one arm around her waist, their bodies crop naturally at the edges',
    framing: 'vertical mirror-selfie composition, tight and fashion-focused', framingDescription: 'vertical mirror-selfie composition, tight and fashion-focused',
    setting: 'real clothing store and festive shopping environment', environmentDescription: 'real clothing store and festive shopping environment', light: 'indoor store lighting',
    her: H('Lehenga', 'Rani Pink', 'Silk', 'white bandeau blouse with gold-bordered dupatta', 'very bright hot pink lehenga with a white fitted bandeau crop blouse and a rich gold-bordered pink festive dupatta, oxidised silver jewellery'),
    him: H('Modern Kurta', 'White', 'Cotton', 'with hot pink embroidered stole', 'white kurta with a bright embroidered hot pink festive dupatta scarf with colourful detailing and tassels'),
    outfitDescription: 'Hot pink lehenga, white bandeau blouse, gold-bordered dupatta; white kurta with hot pink embroidered stole', qaStatus: 'GENERATED',
    tone: 'Oxidised Silver', colourStory: 'Hot Pink · White', tags: ['mirror-selfie','store'] },
  { id: 'garba-04', world: 'garba', title: 'Ivory Kurta and Bandhani Drape', ref: 'GARBA-REF-04',
    referenceNumber: 4,
    pose: 'standing side by side extremely close, arms relaxed naturally, torsos and outfits dominating the frame', poseDescription: 'standing side by side extremely close, arms relaxed naturally, torsos and outfits dominating the frame',
    framing: 'tight portrait crop, not a wide full-body fashion shoot', framingDescription: 'tight portrait crop, not a wide full-body fashion shoot',
    setting: 'crowded festive event and garba gathering with real people softly visible behind them', environmentDescription: 'crowded festive event and garba gathering with real people softly visible behind them', light: 'festive event lighting',
    her: H('Pre-Draped Saree', 'Ivory', 'Georgette', 'red bandhani dupatta drape', 'cream and ivory embroidered blouse with a rich red and pink bandhani style dupatta drape and festive detailing'),
    him: H('Modern Kurta', 'Ivory', 'Cotton', 'all-over embroidery', 'ivory cream festive kurta with subtle all-over embroidery and a traditional lower garment'),
    outfitDescription: 'Ivory embroidered blouse with red and pink bandhani drape; ivory embroidered kurta', qaStatus: 'GENERATED',
    tone: 'Gold', colourStory: 'Ivory · Red', tags: ['standing','close-crop','crowd'] },
  { id: 'garba-05', world: 'garba', title: 'Purple Night Festive Close-Up', ref: 'GARBA-REF-05',
    referenceNumber: 5,
    pose: 'both standing extremely close with arms and body language naturally connected, intimate and fashion-detail focused', poseDescription: 'both standing extremely close with arms and body language naturally connected, intimate and fashion-detail focused',
    framing: 'close upper-body to mid-body frame with clothes and accessories clearly visible', framingDescription: 'close upper-body to mid-body frame with clothes and accessories clearly visible',
    setting: 'night-time festive event', environmentDescription: 'night-time festive event', light: 'night festive event lighting',
    her: H('Lehenga', 'Lilac', 'Silk Blend', 'embroidered with embellished blouse', 'rich purple and lilac traditional festive outfit with detailed embroidery, an embellished blouse and a flowing dupatta'),
    him: H('Modern Kurta', 'Purple', 'Cotton', 'with white stole', 'deep purple festive kurta with a white cream stole and ethnic detailing'),
    outfitDescription: 'Purple lilac embroidered lehenga with embellished blouse; deep purple kurta with white stole', qaStatus: 'GENERATED',
    tone: 'Silver', colourStory: 'Purple · Purple', tags: ['close-crop','night'] },
  { id: 'garba-06', world: 'garba', title: 'She Touches His Cheek, Garba Night', ref: 'GARBA-REF-06',
    referenceNumber: 6,
    pose: 'she faces the man and touches his cheek and face, he stands relaxed facing her, their interaction is the main subject', poseDescription: 'she faces the man and touches his cheek and face, he stands relaxed facing her, their interaction is the main subject',
    framing: 'vertical portrait, both people fully visible from approximately head to below the knees', framingDescription: 'vertical portrait, both people fully visible from approximately head to below the knees',
    setting: 'night garba ground with a colourful decorative canopy and a crowd in the background', environmentDescription: 'night garba ground with a colourful decorative canopy and a crowd in the background', light: 'night garba ground lighting',
    her: H('Chaniya Choli', 'Multicolour', 'Cotton', 'mirror-work skirt with black crop blouse', 'black sleeveless crop blouse with a dramatic colourful mirror-work and embroidered multicolour chaniya skirt, festive jewellery'),
    him: H('Modern Kurta', 'Black', 'Cotton', 'contemporary with white trousers', 'black contemporary kurta with white and ivory trousers'),
    outfitDescription: 'Black crop blouse with multicolour mirror-work chaniya; black kurta with white trousers', qaStatus: 'GENERATED',
    tone: 'Oxidised Silver', colourStory: 'Multicolour · Black', tags: ['interaction','garba-ground'] },
  { id: 'garba-07', world: 'garba', title: 'Twirl Under the String Lights', ref: 'GARBA-REF-07',
    referenceNumber: 7,
    pose: 'she is captured in the middle of a spin and twirl with her skirt and dupatta flowing dynamically, he stands slightly behind watching and supporting her', poseDescription: 'she is captured in the middle of a spin and twirl with her skirt and dupatta flowing dynamically, he stands slightly behind watching and supporting her',
    framing: 'vertical full-body action composition capturing the entire flare of the skirt', framingDescription: 'vertical full-body action composition capturing the entire flare of the skirt',
    setting: 'outdoor garba street and ground with decorative string lights and a festival crowd', environmentDescription: 'outdoor garba street and ground with decorative string lights and a festival crowd', light: 'night festive lights',
    her: H('Lehenga', 'Ivory', 'Cotton', 'colourful printed dupatta', 'white and ivory lehenga chaniya with a colourful blue and green printed festive dupatta'),
    him: H('Printed Ethnic Shirt', 'Navy', 'Cotton', 'blue and white print with white stole', 'blue and white contemporary printed ethnic kurta with a white stole'),
    outfitDescription: 'Ivory lehenga with colourful blue and green printed dupatta; blue and white printed kurta with white stole', qaStatus: 'GENERATED',
    tone: 'Silver', colourStory: 'Ivory · Blue', tags: ['twirl','action'] },
  { id: 'garba-08', world: 'garba', title: 'Maroon Kurta, Multicolour Chaniya', ref: 'GARBA-REF-08',
    referenceNumber: 8,
    pose: 'both standing naturally and looking toward each other, no straight mannequin-like stance, gaze and interaction natural', poseDescription: 'both standing naturally and looking toward each other, no straight mannequin-like stance, gaze and interaction natural',
    framing: 'vertical fashion portrait with full bodies visible', framingDescription: 'vertical fashion portrait with full bodies visible',
    setting: 'real garba event under warm festive lights on an open dance ground', environmentDescription: 'real garba event under warm festive lights on an open dance ground', light: 'warm festive lights',
    her: H('Chaniya Choli', 'Multicolour', 'Cotton', 'maroon and green accents with cream dupatta', 'multicolour traditional chaniya choli with a cream dupatta, rich maroon and deep green accents, mirror and embroidered details'),
    him: H('Modern Kurta', 'Wine', 'Cotton', 'with cream stole', 'deep maroon wine kurta with a long cream and off-white stole'),
    outfitDescription: 'Multicolour chaniya choli with cream dupatta and maroon green accents; maroon kurta with cream stole', qaStatus: 'GENERATED',
    tone: 'Gold', colourStory: 'Multicolour · Maroon', tags: ['standing','garba-ground'] },
  { id: 'garba-09', world: 'garba', title: 'Close Crop on Hands and Dupatta', ref: 'GARBA-REF-09',
    referenceNumber: 9,
    pose: 'very close cropped interaction with her hand and his hand positioned naturally, the gesture is the subject', poseDescription: 'very close cropped interaction with her hand and his hand positioned naturally, the gesture is the subject',
    framing: 'close crop around torso and hands, a real phone photograph at a festival', framingDescription: 'close crop around torso and hands, a real phone photograph at a festival',
    setting: 'festival environment', environmentDescription: 'festival environment', light: 'natural festival lighting',
    her: H('Chaniya Choli', 'Black', 'Cotton', 'colourful embroidered mirror dupatta', 'modern black crop blouse with a black festive chaniya skirt and a colourful embroidered mirror-work dupatta draped on one side'),
    him: H('Modern Kurta', 'Black', 'Cotton', 'textured with ivory trousers', 'black textured and embroidered kurta with ivory white trousers'),
    outfitDescription: 'Black crop blouse and chaniya with colourful mirror dupatta; black textured kurta with ivory trousers', qaStatus: 'GENERATED',
    tone: 'Oxidised Silver', colourStory: 'Black · Multicolour', tags: ['close-crop','hands'] },
  { id: 'garba-10', world: 'garba', title: 'Gold Blouse, Maroon Printed Kurta', ref: 'GARBA-REF-10',
    referenceNumber: 10,
    pose: 'standing extremely close together with their arms and hands overlapping naturally, camera close enough that garments and accessories dominate', poseDescription: 'standing extremely close together with their arms and hands overlapping naturally, camera close enough that garments and accessories dominate',
    framing: 'tight vertical fashion-detail photograph, not a distant full-body catalogue composition', framingDescription: 'tight vertical fashion-detail photograph, not a distant full-body catalogue composition',
    setting: 'festive event environment', environmentDescription: 'festive event environment', light: 'festive lighting',
    her: H('Lehenga', 'Ivory', 'Silk', 'gold embellished blouse with sheer dupatta', 'heavily embellished gold and silver blouse with a pale ivory lehenga and a light transparent dupatta'),
    him: H('Printed Ethnic Shirt', 'Maroon', 'Cotton', 'traditional festive print', 'rich red maroon printed ethnic shirt kurta with traditional festive texture'),
    outfitDescription: 'Gold and silver embellished blouse with pale ivory lehenga and sheer dupatta; maroon printed ethnic shirt', qaStatus: 'GENERATED',
    tone: 'Gold', colourStory: 'Ivory · Maroon', tags: ['close-crop','detail'] },
  { id: 'garba-11', world: 'garba', title: 'Navy Geometric Chaniya', ref: 'GARBA-REF-11',
    referenceNumber: 11,
    pose: 'both standing beside each other with hands and dupattas held naturally, their hands holding the fabric and stole', poseDescription: 'both standing beside each other with hands and dupattas held naturally, their hands holding the fabric and stole',
    framing: 'mid-body to upper-body fashion crop emphasising textile, print and hand styling', framingDescription: 'mid-body to upper-body fashion crop emphasising textile, print and hand styling',
    setting: 'festive event environment', environmentDescription: 'festive event environment', light: 'festive lighting',
    her: H('Chaniya Choli', 'Navy', 'Cotton', 'geometric sparkle embellishment', 'dark navy festive chaniya with geometric and sparkly embellishments and a matching dupatta'),
    him: H('Printed Ethnic Shirt', 'Navy', 'Cotton', 'printed with stole', 'dark navy printed ethnic kurta with a complementary stole'),
    outfitDescription: 'Navy chaniya with geometric sparkle embellishment; navy printed kurta with stole', qaStatus: 'GENERATED',
    tone: 'Silver', colourStory: 'Navy · Navy', tags: ['mid-crop','textile'] },
  { id: 'garba-12', world: 'garba', title: 'Blue Lehenga, Magenta Dupatta', ref: 'GARBA-REF-12',
    referenceNumber: 12,
    pose: 'both standing very close with her arm and body slightly overlapping his side, cloth arrangement and overlap preserved', poseDescription: 'both standing very close with her arm and body slightly overlapping his side, cloth arrangement and overlap preserved',
    framing: 'vertical close to mid-body composition, not widened', framingDescription: 'vertical close to mid-body composition, not widened',
    setting: 'festive event environment', environmentDescription: 'festive event environment', light: 'festive lighting',
    her: H('Lehenga', 'Royal Blue', 'Cotton', 'patterned with magenta dupatta', 'deep blue patterned festive lehenga skirt with a bright pink and magenta dupatta and a colourful border'),
    him: H('Modern Kurta', 'Purple', 'Cotton', 'light lavender with white stole', 'light lavender pink kurta with a long white stole and white trousers'),
    outfitDescription: 'Deep blue patterned lehenga with magenta dupatta; lavender kurta with white stole', qaStatus: 'GENERATED',
    tone: 'Silver', colourStory: 'Blue · Magenta', tags: ['close-crop','overlap'] },
  { id: 'garba-13', world: 'garba', title: 'Matching Navy Textile Crop', ref: 'GARBA-REF-13',
    referenceNumber: 13,
    pose: 'both standing side by side with hands positioned naturally in front, gripping and holding the dupattas', poseDescription: 'both standing side by side with hands positioned naturally in front, gripping and holding the dupattas',
    framing: 'very tight fashion crop focused on the matching textile language and accessories', framingDescription: 'very tight fashion crop focused on the matching textile language and accessories',
    setting: 'festive event environment', environmentDescription: 'festive event environment', light: 'festive lighting',
    her: H('Chaniya Choli', 'Navy', 'Cotton', 'colourful motif with embellished blouse', 'navy and black festive chaniya with repeated small colourful motifs and a dark navy embellished blouse'),
    him: H('Printed Ethnic Shirt', 'Black', 'Cotton', 'printed embroidery detail', 'matching dark navy and black ethnic kurta with printed and embroidered detail'),
    outfitDescription: 'Navy chaniya with colourful motifs and embellished blouse; matching navy and black printed kurta', qaStatus: 'GENERATED',
    tone: 'Oxidised Silver', colourStory: 'Navy · Black', tags: ['tight-crop','matching'] },
  { id: 'garba-14', world: 'garba', title: 'Red Lehenga, Gujarati Stole', ref: 'GARBA-REF-14',
    referenceNumber: 14,
    pose: 'close-standing festive couple, her arm around and near his side, his arm naturally around her waist and shoulder area', poseDescription: 'close-standing festive couple, her arm around and near his side, his arm naturally around her waist and shoulder area',
    framing: 'vertical close to mid-body photograph', framingDescription: 'vertical close to mid-body photograph',
    setting: 'real outdoor garba event', environmentDescription: 'real outdoor garba event', light: 'daylight to evening festive light',
    her: H('Lehenga', 'Red', 'Cotton', 'cream blouse with traditional detailing', 'bright red and orange festive lehenga with a cream and ivory blouse and rich traditional detailing'),
    him: H('Modern Kurta', 'Ivory', 'Cotton', 'with multicolour Gujarati stole', 'ivory and white festive kurta with a multicolour Gujarati style scarf and dupatta'),
    outfitDescription: 'Red and orange lehenga with cream blouse; ivory kurta with multicolour Gujarati stole', qaStatus: 'GENERATED',
    tone: 'Gold', colourStory: 'Red · Ivory', tags: ['standing','garba-event'] },
  { id: 'garba-15', world: 'garba', title: 'Black and White Garba Pair', ref: 'GARBA-REF-15',
    referenceNumber: 15,
    pose: 'both standing closely with bodies angled naturally toward one another, hand positions and garment positioning preserved', poseDescription: 'both standing closely with bodies angled naturally toward one another, hand positions and garment positioning preserved',
    framing: 'tight crop around the couple, not a studio catalogue photo', framingDescription: 'tight crop around the couple, not a studio catalogue photo',
    setting: 'festive event environment', environmentDescription: 'festive event environment', light: 'festive lighting',
    her: H('Chaniya Choli', 'Black', 'Cotton', 'light embroidered blouse with dupatta', 'black and white contemporary garba outfit with a dark chaniya skirt, a light embroidered blouse and a traditional dupatta'),
    him: H('Printed Ethnic Shirt', 'Black', 'Cotton', 'charcoal print with ivory stole', 'black and charcoal printed kurta with an ivory and white stole and trousers'),
    outfitDescription: 'Dark chaniya with light embroidered blouse and dupatta; charcoal printed kurta with ivory stole', qaStatus: 'GENERATED',
    tone: 'Silver', colourStory: 'Black · White', tags: ['tight-crop','standing'] },
  { id: 'garba-16', world: 'garba', title: 'Lavender Mirror Chaniya', ref: 'GARBA-REF-16',
    referenceNumber: 16,
    pose: 'close side-by-side standing interaction with hands positioned around the stole and dupatta, physical relationship preserved', poseDescription: 'close side-by-side standing interaction with hands positioned around the stole and dupatta, physical relationship preserved',
    framing: 'vertical medium-close portrait', framingDescription: 'vertical medium-close portrait',
    setting: 'festive event environment', environmentDescription: 'festive event environment', light: 'festive evening and night light',
    her: H('Lehenga', 'Lilac', 'Silk Blend', 'mirror and metallic accents', 'lavender and purple traditional garba lehenga chaniya with shiny mirror and metallic accents and a matching dupatta'),
    him: H('Modern Kurta', 'Purple', 'Cotton', 'embroidered with white stole', 'rich purple embroidered and printed kurta with a white and ivory stole and white trousers'),
    outfitDescription: 'Lavender chaniya with mirror and metallic accents; purple embroidered kurta with white stole', qaStatus: 'GENERATED',
    tone: 'Silver', colourStory: 'Lavender · Purple', tags: ['standing','night'] },
  { id: 'garba-17', world: 'garba', title: 'Maroon Chaniya, Night Street', ref: 'GARBA-REF-17',
    referenceNumber: 17,
    pose: 'close affectionate standing interaction with one persons head and upper body leaning toward the other, preserving the natural asymmetry of the pose', poseDescription: 'close affectionate standing interaction with one persons head and upper body leaning toward the other, preserving the natural asymmetry of the pose',
    framing: 'vertical full to three-quarter body photograph', framingDescription: 'vertical full to three-quarter body photograph',
    setting: 'outdoor night festive street with lights and parked vehicles and background activity', environmentDescription: 'outdoor night festive street with lights and parked vehicles and background activity', light: 'night street lighting',
    her: H('Chaniya Choli', 'Maroon', 'Cotton', 'black blouse with rich dupatta', 'deep burgundy and maroon festive chaniya skirt with a black blouse and a rich traditional dupatta'),
    him: H('Modern Kurta', 'Black', 'Cotton', 'with ivory lower', 'black kurta with an ivory and white lower garment'),
    outfitDescription: 'Maroon chaniya with black blouse and rich dupatta; black kurta with ivory lower', qaStatus: 'GENERATED',
    tone: 'Gold', colourStory: 'Maroon · Black', tags: ['standing','night-street'] },
  { id: 'garba-18', world: 'garba', title: 'Navy Lehenga, Cross-Body Bag', ref: 'GARBA-REF-18',
    referenceNumber: 18,
    pose: 'both facing each other with arms crossed or relaxed in the same configuration, his cross-body bag and her drape and accessories preserved', poseDescription: 'both facing each other with arms crossed or relaxed in the same configuration, his cross-body bag and her drape and accessories preserved',
    framing: 'vertical mid to full-body composition with both subjects clearly visible', framingDescription: 'vertical mid to full-body composition with both subjects clearly visible',
    setting: 'night-time outdoor road and garba surroundings', environmentDescription: 'night-time outdoor road and garba surroundings', light: 'night outdoor lighting',
    her: H('Lehenga', 'Black', 'Silk Blend', 'colourful dupatta with traditional jewellery', 'dark navy and black festive lehenga with a colourful dupatta and traditional jewellery'),
    him: H('Modern Kurta', 'White', 'Cotton', 'embroidered with charcoal lower', 'white and off-white embroidered kurta with a black and charcoal lower garment and a cross-body bag'),
    outfitDescription: 'Navy and black lehenga with colourful dupatta; white embroidered kurta with charcoal lower and cross-body bag', qaStatus: 'GENERATED',
    tone: 'Silver', colourStory: 'Navy · White', tags: ['standing','night-road'] },
  { id: 'garba-19', world: 'garba', title: 'Black and White Street Lean', ref: 'GARBA-REF-19',
    referenceNumber: 19,
    pose: 'she leans very close into him, one person bends and tilts toward the other, spontaneous but preserving the exact body relationship', poseDescription: 'she leans very close into him, one person bends and tilts toward the other, spontaneous but preserving the exact body relationship',
    framing: 'vertical full-body to three-quarter framing, camera perspective unchanged', framingDescription: 'vertical full-body to three-quarter framing, camera perspective unchanged',
    setting: 'night festive street with realistic background activity and practical lights', environmentDescription: 'night festive street with realistic background activity and practical lights', light: 'night street lighting',
    her: H('Chaniya Choli', 'Black', 'Cotton', 'white crop blouse with colourful detailing', 'black and white contemporary festive outfit with a white crop blouse and a dark chaniya skirt with colourful detailing'),
    him: H('Modern Kurta', 'Black', 'Cotton', 'charcoal with white trousers', 'black and charcoal kurta or ethnic layer with white and ivory trousers'),
    outfitDescription: 'White crop blouse with dark chaniya and colourful detailing; charcoal kurta with white trousers', qaStatus: 'GENERATED',
    tone: 'Silver', colourStory: 'Black · White', tags: ['leaning','night-street'] },
  { id: 'garba-20', world: 'garba', title: 'Ivory Chaniya, Seated Together', ref: 'GARBA-REF-20',
    referenceNumber: 20,
    pose: 'both seated close together with her leaning toward him and toward his shoulder, heads and shoulders positioned closely, exact sitting arrangement preserved', poseDescription: 'both seated close together with her leaning toward him and toward his shoulder, heads and shoulders positioned closely, exact sitting arrangement preserved',
    framing: 'vertical intimate seated portrait, not a standing image', framingDescription: 'vertical intimate seated portrait, not a standing image',
    setting: 'real outdoor festive setting', environmentDescription: 'real outdoor festive setting', light: 'warm and night decorative lighting',
    her: H('Chaniya Choli', 'Ivory', 'Cotton', 'blue printed detailing', 'white and ivory festive chaniya with blue and navy printed detailing and a matching dupatta'),
    him: H('Modern Kurta', 'Powder Blue', 'Cotton', 'light blue patterned', 'light blue and white patterned ethnic kurta with a white and light lower garment'),
    outfitDescription: 'Ivory chaniya with blue printed detailing; light blue patterned kurta with white lower', qaStatus: 'GENERATED',
    tone: 'Silver', colourStory: 'Ivory · Blue', tags: ['seated','intimate'] },

  // ───────────── COLLEGE FEST (priority 2) ─────────────
  { id: 'college-fest-01', world: 'college-fest', title: 'Black Kurta, Mirror Doorway', ref: 'LOOK-01',
    pose: 'standing very close together, she slightly in front and to the left, he slightly behind and to the right with his arm naturally around her shoulder, she stands relaxed with her handbag hanging from one hand, both looking toward the camera, casual affectionate not formal', framing: 'vertical full-body portrait, couple centred, entire outfits visible down to footwear', setting: 'dark reflective modern interior with a tall glass doorway behind them', light: 'night indoor lighting',
    her: H('Kurta Sets', 'Black', 'Cotton', 'white floral embroidery with palazzo', 'black long straight kurta with prominent white floral embroidery, white loose palazzo bottoms, statement silver layered necklace, long silver earrings, silver embellished small handbag, white embroidered flats'),
    him: H('Ethnic Shirt', 'Black', 'Cotton', 'solid full-sleeve', 'solid black full-sleeve button-up shirt, relaxed fit, white wide trousers, white sneakers, simple wristwatch'),
    tone: 'Silver', colourStory: 'Black · White', tags: ['standing','mirror-doorway'] },
  { id: 'college-fest-02', world: 'college-fest', title: 'Cream Printed Set on the Cafe Bench', ref: 'LOOK-02',
    pose: 'both seated together on a wooden bench, he on the left and she on the right, bodies slightly turned toward each other, looking at each other naturally in relaxed conversation, one arm resting naturally rather than posed', framing: 'vertical lifestyle portrait, full seated bodies and footwear visible, small round black cafe table in the left foreground', setting: 'indoor modern cafe lounge with plants and window elements behind', light: 'soft daylight',
    her: H('Kurta Sets', 'Ivory', 'Cotton', 'olive floral print with dupatta', 'cream printed kurta set with a delicate olive floral pattern, matching bottoms, a long flowing dupatta with a green printed border, white sneakers, light beige shoulder bag'),
    him: H('Ethnic Shirt', 'Olive', 'Cotton', 'solid full-sleeve', 'dark olive casual full-sleeve button-up shirt, relaxed fit, off-white loose trousers, white sneakers, wristwatch'),
    tone: 'Silver', colourStory: 'Cream · Olive', tags: ['seated','cafe'] },
  { id: 'college-fest-03', world: 'college-fest', title: 'Ivory Mirror Lehenga, Steps Selfie', ref: 'LOOK-03',
    pose: 'both seated very close together on stone steps, she slightly forward holding a smartphone up in front of her face like a selfie with the phone partially obscuring her face, he leaning closely toward her face, heads close together', framing: 'vertical close lifestyle portrait, camera slightly close to the subjects', setting: 'stone haveli steps with diyas and soft festive lights around, warm beige environment', light: 'warm golden evening lighting',
    her: H('Lehenga', 'Ivory', 'Georgette', 'mirror-work blouse', 'ivory heavily mirror-work and sequin lehenga with a matching embellished blouse with thin shoulder straps, ivory dupatta, traditional silver bangles, large silver jhumka earrings'),
    him: H('Modern Kurta', 'Cream', 'Cotton', 'embroidered', 'cream embroidered kurta with light blue relaxed jeans, wristwatch, dark footwear'),
    tone: 'Silver', colourStory: 'Ivory · Cream', tags: ['seated','selfie'] },
  { id: 'college-fest-04', world: 'college-fest', title: 'Wine Dress and Floral Blazer', ref: 'LOOK-04',
    pose: 'standing very close, she on the left slightly leaning toward him, he on the right looking down toward her, both looking at each other rather than the camera, his arm naturally behind and around her', framing: 'vertical full-body portrait', setting: 'warm indoor evening setting with a curtain background strung with warm fairy lights and a dark elegant floor', light: 'soft cinematic lighting',
    her: H('Lehenga', 'Wine', 'Georgette', 'gold border', 'deep wine floor-length festive lehenga with a sleeveless spaghetti-strap bodice, long flowing skirt, decorative gold traditional border near the lower edge and on the dupatta, minimal elegant jewellery'),
    him: H('Festive Jacket', 'Black', 'Cotton Blend', 'burgundy floral pattern', 'solid black shirt and black trousers with black shoes worn under a black and burgundy floral patterned tailored blazer with a dense muted paisley pattern'),
    tone: 'Gold', colourStory: 'Wine · Black', tags: ['standing','evening'] },
  { id: 'college-fest-05', world: 'college-fest', title: 'Overhead Walk, Arm Linked', ref: 'LOOK-05',
    pose: 'top-down overhead photograph with the camera looking almost directly down, couple walking closely together with her arm looped around his arm, bodies seen from above, both looking naturally downward, legs and footwear visible', framing: 'vertical overhead composition with the concrete outdoor walkway visible underneath', setting: 'outdoor stone walkway', light: 'natural daylight',
    her: H('Kurta Sets', 'Ivory', 'Cotton', 'navy block print with white dupatta', 'white printed kurta set with a blue and navy floral block-print pattern, matching light bottoms, white lightweight dupatta, small delicate necklace'),
    him: H('Ethnic Shirt', 'Navy', 'Cotton', 'solid', 'solid navy button-up shirt, relaxed fit, off-white trousers, white sneakers, dark wristwatch'),
    tone: 'Silver', colourStory: 'Ivory · Navy', tags: ['overhead','walking'] },
  { id: 'college-fest-06', world: 'college-fest', title: 'Close Crop, Maroon Dupatta Detail', ref: 'LOOK-06',
    pose: 'very close cropped couple portrait showing torso arms and hands more than faces, she holds and adjusts her deep red dupatta near her front, he stands immediately beside her, their bodies almost touching', framing: 'vertical close crop focused on garment details, dupatta border, embroidery and hand placement', setting: 'neutral indoor background', light: 'soft indoor light',
    her: H('Kurta Sets', 'Ivory', 'Silk Blend', 'gold floral embroidery with maroon dupatta', 'taupe champagne ethnic suit with heavy gold floral embroidery and a deep maroon dupatta with a prominent ornate gold embroidered border, mehendi visible on hands, gold jewellery'),
    him: H('Modern Kurta', 'Cream', 'Cotton', 'plain', 'plain cream kurta with a clean straight silhouette, minimal styling, no jacket'),
    tone: 'Gold', colourStory: 'Champagne · Maroon', tags: ['close-crop','detail'] },
  { id: 'college-fest-07', world: 'college-fest', title: 'Soft Pink Monochrome Close Crop', ref: 'LOOK-07',
    pose: 'extremely close couple crop with their upper torsos touching, he positioned beside and behind her, her arm across and around him, he holds a smartphone close to his body, faces partially cropped out', framing: 'vertical close-up cropped around the chest and waist area', setting: 'outdoor', light: 'natural daylight',
    her: H('Kurta Sets', 'Rani Pink', 'Cotton', 'white floral embroidery', 'soft pastel pink ethnic kurta with white floral embroidery on the sleeves and body, soft feminine silhouette, minimal jewellery'),
    him: H('Ethnic Shirt', 'Pink', 'Cotton', 'solid pastel', 'light pastel pink button-up shirt, relaxed casual fit, holding a smartphone, wristwatch'),
    tone: 'Silver', colourStory: 'Pink · Pink', tags: ['close-crop','monochrome'] },
  { id: 'college-fest-08', world: 'college-fest', title: 'White Outfit, Hot Pink Bandhani Dupatta', ref: 'LOOK-08',
    pose: 'standing side by side, she on the left holding and fanning her hot pink dupatta outward so it becomes the dominant visual element, he on the right standing relaxed with one hand near his pocket, framed from the shoulders through the legs', framing: 'vertical fashion lifestyle photograph', setting: 'outdoor with a green fence and plants behind', light: 'outdoor daylight',
    her: H('Kurta Sets', 'Ivory', 'Cotton', 'hot pink bandhani dupatta', 'white ethnic base outfit with a simple sleeveless inner, bright hot pink bandhani dupatta with a traditional dotted geometric print and gold trim, beige flat sandals'),
    him: H('Modern Kurta', 'White', 'Cotton', 'chikankari', 'white chikankari embroidered kurta with light blue relaxed jeans, white casual footwear, silver watch'),
    tone: 'Silver', colourStory: 'White · Hot Pink', tags: ['standing','bandhani'] },
  { id: 'college-fest-09', world: 'college-fest', title: 'Magenta Set on the Night Staircase', ref: 'LOOK-09',
    pose: 'standing together near a staircase, she close to his side and turning toward him, he raises one hand toward his hair, natural playful interaction, no formal posing', framing: 'vertical full to three-quarter portrait', setting: 'outdoor apartment staircase at night', light: 'night lighting with warm street and festive lights',
    her: H('Lehenga', 'Rani Pink', 'Georgette', 'white floral motifs', 'bright magenta festive lehenga with a patterned skirt carrying white floral motifs and a sheer flowing hot pink dupatta with a gold border'),
    him: H('Modern Kurta', 'Peach', 'Cotton', 'coral with cream ethnic layer', 'peach coral kurta with a white cream embroidered ethnic layer worn over it and a light cream lower garment'),
    tone: 'Gold', colourStory: 'Magenta · Peach', tags: ['staircase','night'] },
  { id: 'college-fest-10', world: 'college-fest', title: 'Sky Blue Suit, Foreheads Touching', ref: 'LOOK-10',
    pose: 'both seated on stairs, she on the left and he on the right, faces leaning very close toward each other with foreheads and cheeks almost touching, natural intimate eye contact, she holds a smartphone down near her lap', framing: 'vertical portrait with a close seated perspective', setting: 'stone indoor stairs', light: 'soft daylight',
    her: H('Kurta Sets', 'Powder Blue', 'Cotton', 'white embroidery', 'light sky blue embroidered ethnic suit with a matching light blue dupatta and white embroidery, traditional salwar styling'),
    him: H('Modern Kurta', 'Powder Blue', 'Cotton', 'embroidered', 'powder light blue embroidered kurta with white trousers in a matching pastel palette with traditional motifs'),
    tone: 'Silver', colourStory: 'Sky Blue · Sky Blue', tags: ['seated','intimate'] },
  { id: 'college-fest-11', world: 'college-fest', title: 'Ivory Anarkali on the Staircase', ref: 'LOOK-11',
    pose: 'seated on a staircase, she lower left and in front, he one or two steps above and to the right, she looking upward at him, he resting his elbow and hand near his face while looking at her, neither looking at the camera', framing: 'vertical lifestyle portrait with the staircase dominating the background', setting: 'indoor staircase', light: 'warm indoor light with a soft warm tone',
    her: H('Anarkali', 'Ivory', 'Georgette', 'floral embroidery', 'ivory embroidered festive anarkali with delicate floral embroidery and a matching sheer dupatta, minimal delicate jewellery'),
    him: H('Modern Kurta', 'White', 'Cotton', 'light embroidery', 'all white kurta pajama with light embroidered detailing, traditional silhouette'),
    tone: 'Silver', colourStory: 'Ivory · White', tags: ['seated','staircase'] },
  { id: 'college-fest-12', world: 'college-fest', title: 'Magenta Dupatta in the Heritage Lane', ref: 'LOOK-12',
    pose: 'both walking side by side in a heritage lane, she slightly ahead and to the left, he slightly behind and to the right, both looking downward naturally, relaxed walking movement with hands close to their bodies', framing: 'vertical full-body photograph', setting: 'old heritage village lane with cream walls and a wooden door', light: 'warm natural daylight',
    her: H('Lehenga', 'Wine', 'Silk Blend', 'gold embroidered dupatta', 'deep magenta ethnic lehenga with a cream printed lower portion, a rich decorative border and a large deep magenta dupatta with ornate gold embroidery'),
    him: H('Modern Kurta', 'Cream', 'Cotton', 'textured', 'cream kurta with a matching cream lower garment and a simple embroidered texture, white footwear'),
    tone: 'Gold', colourStory: 'Magenta · Cream', tags: ['walking','heritage'] },
  { id: 'college-fest-13', world: 'college-fest', title: 'White Lehenga, Navy Dupatta, Steps', ref: 'LOOK-13',
    pose: 'she stands in the foreground to the left with her back partly toward the camera and extends one arm forward and upward, he is seated crouched on the steps below her leaning forward and down, playful unequal-height pose', framing: 'vertical full-body asymmetrical composition', setting: 'night environment with a dark reflective wall and windows behind, staircase visible', light: 'night low light',
    her: H('Lehenga', 'Ivory', 'Georgette', 'navy floral dupatta', 'white long ethnic lehenga skirt with a flowing navy blue floral printed dupatta and a white embroidered blouse, traditional silver jewellery'),
    him: H('Modern Kurta', 'White', 'Cotton', 'embroidered', 'white embroidered kurta with white pajama trousers, minimal festive styling'),
    tone: 'Silver', colourStory: 'White · Navy', tags: ['asymmetric','steps'] },
  { id: 'college-fest-14', world: 'college-fest', title: 'Red Lehenga, Night Driveway', ref: 'LOOK-14',
    pose: 'standing outside at night with his arm around her shoulder, she standing close against him, both smiling and laughing naturally, he looking down toward her and she looking toward him', framing: 'vertical smartphone-style photograph', setting: 'night street driveway with a dark car immediately behind them, festive lights and greenery in the background', light: 'strong overhead light source at night',
    her: H('Lehenga', 'Red', 'Silk', 'gold embellished blouse', 'bright red festive lehenga with a heavy gold embellished blouse, rich festive detailing, gold jewellery, bangles and watch as visible'),
    him: H('Modern Kurta', 'Black', 'Cotton', 'gold motifs', 'charcoal grey ethnic kurta with repeating gold and cream traditional motifs and an embroidered neckline and cuffs, dark lower garment'),
    tone: 'Gold', colourStory: 'Red · Charcoal', tags: ['standing','night'] },
  { id: 'college-fest-15', world: 'college-fest', title: 'Maroon Crop Top, White Stole', ref: 'LOOK-15',
    pose: 'both standing very close in a garden, she facing slightly toward him, he leaning downward toward her, a white stole positioned between them with their hands interacting around the stole and waist area, playful styling moment rather than a camera-facing pose', framing: 'vertical medium to full-body photograph', setting: 'garden terrace with plants and a modern concrete wall', light: 'daylight',
    her: H('Lehenga', 'Maroon', 'Cotton', 'oxidised silver embellishment', 'deep maroon crop top with a matching long skirt, white and silver geometric embellishments, oxidised silver jewellery, large silver earrings, heavy silver bangles, bare midriff'),
    him: H('Printed Ethnic Shirt', 'Maroon', 'Cotton', 'traditional print with white stole', 'red maroon printed shirt with a dense traditional print, black loose wide trousers and a long white scarf draped around his neck'),
    tone: 'Oxidised Silver', colourStory: 'Maroon · White', tags: ['garden','stole'] },
  { id: 'college-fest-16', world: 'college-fest', title: 'Maroon Dress, Lavender Kurta', ref: 'LOOK-16',
    pose: 'both standing and walking together, she on the right and he on the left, he looking toward her, she laughing with one hand raised near her face, natural walking conversation energy with visible space between their bodies', framing: 'vertical portrait', setting: 'ornate upscale interior with a carved golden decorative wall', light: 'warm yellow indoor lighting',
    her: H('Lehenga', 'Wine', 'Georgette', 'soft pink dupatta', 'deep maroon long flowing ethnic dress with a soft pink sheer dupatta, elegant simple jewellery'),
    him: H('Modern Kurta', 'Purple', 'Cotton', 'solid', 'soft lavender kurta with a straight simple silhouette'),
    tone: 'Gold', colourStory: 'Maroon · Lavender', tags: ['walking','interior'] },
  { id: 'college-fest-17', world: 'college-fest', title: 'She Fixes His Hair, Navy Dupatta', ref: 'LOOK-17',
    pose: 'she faces him and lifts both hands toward his face and head, adjusting his hair and collar area, he stands straight looking toward her, close personal interaction', framing: 'vertical three-quarter to full-body', setting: 'outdoor residential or college style environment with green plants behind', light: 'bright daytime',
    her: H('Kurta Sets', 'Ivory', 'Cotton', 'navy dupatta', 'white ethnic outfit with a deep navy blue dupatta with a blue embroidered border, traditional silver earrings, simple white lower'),
    him: H('Modern Kurta', 'Cream', 'Cotton', 'embroidered', 'cream embroidered kurta with a white lower garment, wristwatch, clean contemporary traditional look'),
    tone: 'Silver', colourStory: 'White · Navy', tags: ['interaction','daytime'] },
  { id: 'college-fest-18', world: 'college-fest', title: 'Purple Suit in the Stairwell', ref: 'LOOK-18',
    pose: 'both seated on a staircase, he on the left leaning forward with one hand covering part of his face, she on the right seated upright touching and adjusting her hair, casual slightly awkward youthful pose, neither looking at the camera', framing: 'vertical portrait', setting: 'indoor stairwell with a white wall and the staircase rising behind', light: 'cool indoor lighting',
    her: H('Kurta Sets', 'Purple', 'Cotton', 'embroidered neckline', 'deep purple ethnic suit with a long straight kurta, a detailed embroidered neckline and front panel, a matching purple dupatta, long sleeves, minimal jewellery'),
    him: H('Festive Separates', 'White', 'Cotton', 'long-sleeve top with dark jeans', 'plain white long-sleeve t-shirt with dark charcoal jeans, white sneakers, wristwatch'),
    tone: 'Silver', colourStory: 'Purple · White', tags: ['seated','stairwell'] },
  { id: 'college-fest-19', world: 'college-fest', title: 'Blush Lehenga in the Heritage Arch', ref: 'LOOK-19',
    pose: 'standing a few feet apart inside a grand heritage arch, she on the left partially lifting one hand to her face, he on the right standing upright with relaxed arms, both looking generally toward each other or to the side rather than at the camera, strong negative space between them', framing: 'vertical architectural composition with the archway a major part of the image', setting: 'huge ornate Mughal and Rajasthani style archway with carved walls and a pink doorway far behind', light: 'warm daylight',
    her: H('Anarkali', 'Rani Pink', 'Georgette', 'embroidered upper with dupatta', 'soft blush dusty pink lehenga style anarkali with an intricately embellished upper portion, a flowing dupatta, traditional festive jewellery'),
    him: H('Modern Kurta', 'White', 'Cotton', 'minimal embroidery', 'pure white kurta pajama with minimal embroidery, clean relaxed silhouette, white footwear'),
    tone: 'Gold', colourStory: 'Blush · White', tags: ['archway','heritage'] },
  { id: 'college-fest-20', world: 'college-fest', title: 'Maroon Kurta, Balcony Crop', ref: 'LOOK-20',
    pose: 'standing side by side, he on the right with both arms crossed, she on the left with one hand around her waist, bodies close together, casual relaxed upper-body pose', framing: 'horizontal cropped composition from below the shoulders to the waist, not a full-body shot', setting: 'night balcony terrace with a railing behind', light: 'warm outdoor evening light',
    her: H('Kurta Sets', 'Maroon', 'Cotton', 'subtle embroidery', 'deep maroon ethnic kurta suit with subtle traditional embroidery and a long straight silhouette, minimal jewellery'),
    him: H('Modern Kurta', 'White', 'Cotton', 'embroidered', 'white embroidered kurta with white pajama trousers, arms crossed'),
    tone: 'Silver', colourStory: 'Maroon · White', tags: ['balcony','cropped'] },

  // ───────────── DIWALI (priority 3) ─────────────
  { id: 'diwali-01', world: 'diwali', title: 'Black Embroidered Kurta, Glass Doorway', ref: 'DIWALI-REF-01',
    referenceNumber: 1,
    pose: 'standing very close together, she slightly in front and to the left, he slightly behind and to the right with his arm naturally around her shoulder, she stands relaxed with her handbag hanging from one hand, both looking toward the camera', poseDescription: 'standing very close together, she slightly in front and to the left, he slightly behind and to the right with his arm naturally around her shoulder, she stands relaxed with her handbag hanging from one hand, both looking toward the camera',
    framing: 'vertical full-body portrait, couple centred, entire outfits visible down to footwear', framingDescription: 'vertical full-body portrait, couple centred, entire outfits visible down to footwear',
    setting: 'dark reflective modern interior with a tall glass and mirror doorway behind them', environmentDescription: 'dark reflective modern interior with a tall glass and mirror doorway behind them', light: 'night indoor lighting',
    her: H('Kurta Sets', 'Black', 'Cotton', 'white floral embroidery with palazzo', 'black long straight kurta with prominent white floral embroidery, white loose palazzo bottoms, statement silver layered necklace, long silver earrings, silver embellished small handbag, white embroidered flats'),
    him: H('Ethnic Shirt', 'Black', 'Cotton', 'solid full-sleeve', 'solid black full-sleeve button-up shirt, relaxed fit, white wide trousers, white sneakers, simple wristwatch'),
    outfitDescription: "Black kurta with white floral embroidery and white palazzo; black shirt with white trousers and sneakers", qaStatus: 'GENERATED',
    tone: 'Silver', colourStory: 'Black · White', tags: ['standing','mirror-doorway'] },
  { id: 'diwali-02', world: 'diwali', title: 'Cream Printed Set on the Cafe Bench', ref: 'DIWALI-REF-02',
    referenceNumber: 2,
    pose: 'both seated together on a wooden bench, he on the left and she on the right, bodies slightly turned toward each other, looking at each other naturally in relaxed conversation, one arm resting naturally', poseDescription: 'both seated together on a wooden bench, he on the left and she on the right, bodies slightly turned toward each other, looking at each other naturally in relaxed conversation, one arm resting naturally',
    framing: 'vertical lifestyle portrait, full seated bodies and footwear visible, small round black cafe table in the left foreground', framingDescription: 'vertical lifestyle portrait, full seated bodies and footwear visible, small round black cafe table in the left foreground',
    setting: 'indoor modern cafe lounge with plants and window elements behind', environmentDescription: 'indoor modern cafe lounge with plants and window elements behind', light: 'soft daylight',
    her: H('Kurta Sets', 'Ivory', 'Cotton', 'olive floral print with dupatta', 'cream printed kurta set with a delicate olive floral pattern, matching bottoms, a long flowing dupatta with a green printed border, white sneakers, light beige shoulder bag'),
    him: H('Ethnic Shirt', 'Olive', 'Cotton', 'solid full-sleeve', 'dark olive casual full-sleeve button-up shirt, relaxed fit, off-white loose trousers, white sneakers, wristwatch'),
    outfitDescription: "Cream printed kurta set with olive floral dupatta; olive shirt with off-white trousers", qaStatus: 'GENERATED',
    tone: 'Silver', colourStory: 'Cream · Olive', tags: ['seated','cafe'] },
  { id: 'diwali-03', world: 'diwali', title: 'Ivory Mirror Lehenga, Steps Selfie', ref: 'DIWALI-REF-03',
    referenceNumber: 3,
    pose: 'both seated very close together on stone steps, she slightly forward holding a smartphone up in front of her face like a selfie with the phone partially obscuring her face, he leaning closely toward her face, heads close together', poseDescription: 'both seated very close together on stone steps, she slightly forward holding a smartphone up in front of her face like a selfie with the phone partially obscuring her face, he leaning closely toward her face, heads close together',
    framing: 'vertical close lifestyle portrait, camera slightly close to the subjects', framingDescription: 'vertical close lifestyle portrait, camera slightly close to the subjects',
    setting: 'stone haveli steps with diyas and soft festive lights around, warm beige environment', environmentDescription: 'stone haveli steps with diyas and soft festive lights around, warm beige environment', light: 'warm golden evening lighting',
    her: H('Lehenga', 'Ivory', 'Georgette', 'mirror-work blouse', 'ivory heavily mirror-work and sequin lehenga with a matching embellished blouse with thin shoulder straps, ivory dupatta, traditional silver bangles, large silver jhumka earrings'),
    him: H('Modern Kurta', 'Cream', 'Cotton', 'embroidered', 'cream embroidered kurta with light blue relaxed jeans, wristwatch'),
    outfitDescription: "Ivory mirror-work lehenga with embellished blouse; cream embroidered kurta with light blue jeans", qaStatus: 'GENERATED',
    tone: 'Silver', colourStory: 'Ivory · Cream', tags: ['seated','selfie','diyas'] },
  { id: 'diwali-04', world: 'diwali', title: 'Wine Dress and Floral Blazer', ref: 'DIWALI-REF-04',
    referenceNumber: 4,
    pose: 'standing very close, she on the left slightly leaning toward him, he on the right looking down toward her, both looking at each other rather than the camera, his arm naturally behind and around her', poseDescription: 'standing very close, she on the left slightly leaning toward him, he on the right looking down toward her, both looking at each other rather than the camera, his arm naturally behind and around her',
    framing: 'vertical full-body portrait', framingDescription: 'vertical full-body portrait',
    setting: 'warm indoor evening setting with a curtain background strung with warm fairy lights and a dark elegant floor', environmentDescription: 'warm indoor evening setting with a curtain background strung with warm fairy lights and a dark elegant floor', light: 'soft cinematic lighting',
    her: H('Lehenga', 'Wine', 'Georgette', 'gold border', 'deep wine floor-length festive lehenga with a sleeveless spaghetti-strap bodice, long flowing skirt, decorative gold traditional border near the lower edge and on the dupatta, minimal elegant jewellery'),
    him: H('Festive Jacket', 'Black', 'Cotton Blend', 'burgundy floral pattern', 'solid black shirt and black trousers with black shoes worn under a black and burgundy floral patterned tailored blazer'),
    outfitDescription: "Wine floor-length lehenga with gold border; black shirt and trousers with burgundy floral blazer", qaStatus: 'GENERATED',
    tone: 'Gold', colourStory: 'Wine · Black', tags: ['standing','evening'] },
  { id: 'diwali-05', world: 'diwali', title: 'Overhead Walk, Arm Linked', ref: 'DIWALI-REF-05',
    referenceNumber: 5,
    pose: 'top-down overhead photograph with the camera looking almost directly down, couple walking closely together with her arm looped around his arm, bodies seen from above, both looking naturally downward, legs and footwear visible', poseDescription: 'top-down overhead photograph with the camera looking almost directly down, couple walking closely together with her arm looped around his arm, bodies seen from above, both looking naturally downward, legs and footwear visible',
    framing: 'vertical overhead composition with the concrete outdoor walkway visible underneath', framingDescription: 'vertical overhead composition with the concrete outdoor walkway visible underneath',
    setting: 'outdoor stone walkway', environmentDescription: 'outdoor stone walkway', light: 'natural daylight',
    her: H('Kurta Sets', 'Ivory', 'Cotton', 'navy block print with white dupatta', 'white printed kurta set with a blue and navy floral block-print pattern, matching light bottoms, white lightweight dupatta, small delicate necklace'),
    him: H('Ethnic Shirt', 'Navy', 'Cotton', 'solid', 'solid navy button-up shirt, relaxed fit, off-white trousers, white sneakers, dark wristwatch'),
    outfitDescription: "White and navy block-print kurta set; navy shirt with off-white trousers", qaStatus: 'GENERATED',
    tone: 'Silver', colourStory: 'Ivory · Navy', tags: ['overhead','walking'] },
  { id: 'diwali-06', world: 'diwali', title: 'Close Crop, Maroon Dupatta Detail', ref: 'DIWALI-REF-06',
    referenceNumber: 6,
    pose: 'very close cropped couple portrait showing torso arms and hands more than faces, she holds and adjusts her deep red dupatta near her front, he stands immediately beside her, their bodies almost touching', poseDescription: 'very close cropped couple portrait showing torso arms and hands more than faces, she holds and adjusts her deep red dupatta near her front, he stands immediately beside her, their bodies almost touching',
    framing: 'vertical close crop focused on garment details, dupatta border, embroidery and hand placement', framingDescription: 'vertical close crop focused on garment details, dupatta border, embroidery and hand placement',
    setting: 'neutral indoor background', environmentDescription: 'neutral indoor background', light: 'soft indoor light',
    her: H('Kurta Sets', 'Ivory', 'Silk Blend', 'gold floral embroidery with maroon dupatta', 'taupe champagne ethnic suit with heavy gold floral embroidery and a deep maroon dupatta with a prominent ornate gold embroidered border, mehendi on hands, gold jewellery'),
    him: H('Modern Kurta', 'Cream', 'Cotton', 'plain', 'plain cream kurta with a clean straight silhouette, minimal styling, no jacket'),
    outfitDescription: "Champagne gold-embroidered suit with deep maroon gold-bordered dupatta; plain cream kurta", qaStatus: 'GENERATED',
    tone: 'Gold', colourStory: 'Champagne · Maroon', tags: ['close-crop','detail'] },
  { id: 'diwali-07', world: 'diwali', title: 'Soft Pink Monochrome Close Crop', ref: 'DIWALI-REF-07',
    referenceNumber: 7,
    pose: 'extremely close couple crop with their upper torsos touching, he positioned beside and behind her, her arm across and around him, he holds a smartphone close to his body, faces partially cropped out', poseDescription: 'extremely close couple crop with their upper torsos touching, he positioned beside and behind her, her arm across and around him, he holds a smartphone close to his body, faces partially cropped out',
    framing: 'vertical close-up cropped around the chest and waist area', framingDescription: 'vertical close-up cropped around the chest and waist area',
    setting: 'outdoor', environmentDescription: 'outdoor', light: 'natural daylight',
    her: H('Kurta Sets', 'Rani Pink', 'Cotton', 'white floral embroidery', 'soft pastel pink ethnic kurta with white floral embroidery on the sleeves and body, soft feminine silhouette, minimal jewellery'),
    him: H('Ethnic Shirt', 'Pink', 'Cotton', 'solid pastel', 'light pastel pink button-up shirt, relaxed casual fit, holding a smartphone, wristwatch'),
    outfitDescription: "Pastel pink kurta with white floral embroidery; pastel pink shirt", qaStatus: 'GENERATED',
    tone: 'Silver', colourStory: 'Pink · Pink', tags: ['close-crop','monochrome'] },
  { id: 'diwali-08', world: 'diwali', title: 'White Outfit, Hot Pink Bandhani Dupatta', ref: 'DIWALI-REF-08',
    referenceNumber: 8,
    pose: 'standing side by side, she on the left holding and fanning her hot pink dupatta outward so it becomes the dominant visual element, he on the right standing relaxed with one hand near his pocket, framed from the shoulders through the legs', poseDescription: 'standing side by side, she on the left holding and fanning her hot pink dupatta outward so it becomes the dominant visual element, he on the right standing relaxed with one hand near his pocket, framed from the shoulders through the legs',
    framing: 'vertical fashion lifestyle photograph', framingDescription: 'vertical fashion lifestyle photograph',
    setting: 'outdoor with a green fence and plants behind', environmentDescription: 'outdoor with a green fence and plants behind', light: 'outdoor daylight',
    her: H('Kurta Sets', 'Ivory', 'Cotton', 'hot pink bandhani dupatta', 'white ethnic base outfit with a simple sleeveless inner, bright hot pink bandhani dupatta with a traditional dotted geometric print and gold trim, beige flat sandals'),
    him: H('Modern Kurta', 'White', 'Cotton', 'chikankari', 'white chikankari embroidered kurta with light blue relaxed jeans, white casual footwear, silver watch'),
    outfitDescription: "White outfit with hot pink bandhani dupatta; white chikankari kurta with light blue jeans", qaStatus: 'GENERATED',
    tone: 'Silver', colourStory: 'White · Hot Pink', tags: ['standing','bandhani'] },
  { id: 'diwali-09', world: 'diwali', title: 'Magenta Set on the Night Staircase', ref: 'DIWALI-REF-09',
    referenceNumber: 9,
    pose: 'standing together near a staircase, she close to his side and turning toward him, he raises one hand toward his hair, natural playful interaction, no formal posing', poseDescription: 'standing together near a staircase, she close to his side and turning toward him, he raises one hand toward his hair, natural playful interaction, no formal posing',
    framing: 'vertical full to three-quarter portrait', framingDescription: 'vertical full to three-quarter portrait',
    setting: 'outdoor apartment or venue staircase at night', environmentDescription: 'outdoor apartment or venue staircase at night', light: 'night lighting with warm street and festive lights',
    her: H('Lehenga', 'Rani Pink', 'Georgette', 'white floral motifs', 'bright magenta festive lehenga with a patterned skirt carrying white floral motifs and a sheer flowing hot pink dupatta with a gold border'),
    him: H('Modern Kurta', 'Peach', 'Cotton', 'coral with cream ethnic layer', 'peach coral kurta with a white cream embroidered ethnic layer worn over it and a light cream lower garment'),
    outfitDescription: "Magenta lehenga with white floral motifs and gold-bordered dupatta; peach kurta with cream ethnic layer", qaStatus: 'GENERATED',
    tone: 'Gold', colourStory: 'Magenta · Peach', tags: ['staircase','night'] },
  { id: 'diwali-10', world: 'diwali', title: 'Sky Blue Suit, Foreheads Touching', ref: 'DIWALI-REF-10',
    referenceNumber: 10,
    pose: 'both seated on stairs, she on the left and he on the right, faces leaning very close toward each other with foreheads and cheeks almost touching, natural intimate eye contact, she holds a smartphone down near her lap', poseDescription: 'both seated on stairs, she on the left and he on the right, faces leaning very close toward each other with foreheads and cheeks almost touching, natural intimate eye contact, she holds a smartphone down near her lap',
    framing: 'vertical portrait with a close seated perspective', framingDescription: 'vertical portrait with a close seated perspective',
    setting: 'stone indoor stairs', environmentDescription: 'stone indoor stairs', light: 'soft daylight',
    her: H('Kurta Sets', 'Powder Blue', 'Cotton', 'white embroidery', 'light sky blue embroidered ethnic suit with a matching light blue dupatta and white embroidery, traditional salwar styling'),
    him: H('Modern Kurta', 'Powder Blue', 'Cotton', 'embroidered', 'powder light blue embroidered kurta with white trousers in a matching pastel palette with traditional motifs'),
    outfitDescription: "Sky blue embroidered suit with matching dupatta; powder blue embroidered kurta", qaStatus: 'GENERATED',
    tone: 'Silver', colourStory: 'Sky Blue · Sky Blue', tags: ['seated','intimate'] },
  { id: 'diwali-11', world: 'diwali', title: 'Ivory Anarkali on the Staircase', ref: 'DIWALI-REF-11',
    referenceNumber: 11,
    pose: 'seated on a staircase, she lower left and in front, he one or two steps above and to the right, she looking upward at him, he resting his elbow and hand near his face while looking at her, neither looking at the camera', poseDescription: 'seated on a staircase, she lower left and in front, he one or two steps above and to the right, she looking upward at him, he resting his elbow and hand near his face while looking at her, neither looking at the camera',
    framing: 'vertical lifestyle portrait with the staircase dominating the background', framingDescription: 'vertical lifestyle portrait with the staircase dominating the background',
    setting: 'indoor staircase', environmentDescription: 'indoor staircase', light: 'warm indoor light with a soft warm tone',
    her: H('Anarkali', 'Ivory', 'Georgette', 'floral embroidery', 'ivory embroidered festive anarkali with delicate floral embroidery and a matching sheer dupatta, minimal delicate jewellery'),
    him: H('Modern Kurta', 'White', 'Cotton', 'light embroidery', 'all white kurta pajama with light embroidered detailing'),
    outfitDescription: "Ivory embroidered anarkali with sheer dupatta; white kurta pajama", qaStatus: 'GENERATED',
    tone: 'Silver', colourStory: 'Ivory · White', tags: ['seated','staircase'] },
  { id: 'diwali-12', world: 'diwali', title: 'Magenta Dupatta in the Heritage Lane', ref: 'DIWALI-REF-12',
    referenceNumber: 12,
    pose: 'both walking side by side in a heritage lane, she slightly ahead and to the left, he slightly behind and to the right, both looking downward naturally, relaxed walking movement with hands close to their bodies', poseDescription: 'both walking side by side in a heritage lane, she slightly ahead and to the left, he slightly behind and to the right, both looking downward naturally, relaxed walking movement with hands close to their bodies',
    framing: 'vertical full-body photograph', framingDescription: 'vertical full-body photograph',
    setting: 'old heritage village lane with cream walls and a wooden door', environmentDescription: 'old heritage village lane with cream walls and a wooden door', light: 'warm natural daylight',
    her: H('Lehenga', 'Wine', 'Silk Blend', 'gold embroidered dupatta', 'deep magenta ethnic lehenga with a cream printed lower portion, a rich decorative border and a large deep magenta dupatta with ornate gold embroidery'),
    him: H('Modern Kurta', 'Cream', 'Cotton', 'textured', 'cream kurta with a matching cream lower garment and a simple embroidered texture, white footwear'),
    outfitDescription: "Magenta lehenga with gold-embroidered dupatta; cream textured kurta", qaStatus: 'GENERATED',
    tone: 'Gold', colourStory: 'Magenta · Cream', tags: ['walking','heritage'] },
  { id: 'diwali-13', world: 'diwali', title: 'White Lehenga, Navy Dupatta, Steps', ref: 'DIWALI-REF-13',
    referenceNumber: 13,
    pose: 'she stands in the foreground to the left with her back partly toward the camera and extends one arm forward and upward, he is seated crouched on the steps below her leaning forward and down, playful unequal-height pose', poseDescription: 'she stands in the foreground to the left with her back partly toward the camera and extends one arm forward and upward, he is seated crouched on the steps below her leaning forward and down, playful unequal-height pose',
    framing: 'vertical full-body asymmetrical composition', framingDescription: 'vertical full-body asymmetrical composition',
    setting: 'night environment with a dark reflective wall and windows behind, staircase visible', environmentDescription: 'night environment with a dark reflective wall and windows behind, staircase visible', light: 'night low light',
    her: H('Lehenga', 'Ivory', 'Georgette', 'navy floral dupatta', 'white long ethnic lehenga skirt with a flowing navy blue floral printed dupatta and a white embroidered blouse, traditional silver jewellery'),
    him: H('Modern Kurta', 'White', 'Cotton', 'embroidered', 'white embroidered kurta with white pajama trousers'),
    outfitDescription: "White lehenga with navy floral dupatta; white embroidered kurta and pajama", qaStatus: 'GENERATED',
    tone: 'Silver', colourStory: 'White · Navy', tags: ['asymmetric','steps'] },
  { id: 'diwali-14', world: 'diwali', title: 'Red Lehenga, Night Driveway', ref: 'DIWALI-REF-14',
    referenceNumber: 14,
    pose: 'standing outside at night with his arm around her shoulder, she standing close against him, both smiling and laughing naturally, he looking down toward her and she looking toward him', poseDescription: 'standing outside at night with his arm around her shoulder, she standing close against him, both smiling and laughing naturally, he looking down toward her and she looking toward him',
    framing: 'vertical smartphone-style photograph', framingDescription: 'vertical smartphone-style photograph',
    setting: 'night street driveway with a dark car immediately behind them, festive lights and greenery in the background', environmentDescription: 'night street driveway with a dark car immediately behind them, festive lights and greenery in the background', light: 'strong overhead light source at night',
    her: H('Lehenga', 'Red', 'Silk', 'gold embellished blouse', 'bright red festive lehenga with a heavy gold embellished blouse, gold jewellery, bangles'),
    him: H('Modern Kurta', 'Black', 'Cotton', 'gold motifs', 'charcoal grey ethnic kurta with repeating gold and cream traditional motifs and an embroidered neckline and cuffs, dark lower garment'),
    outfitDescription: "Red lehenga with gold embellished blouse; charcoal kurta with gold motifs", qaStatus: 'GENERATED',
    tone: 'Gold', colourStory: 'Red · Charcoal', tags: ['standing','night'] },
  { id: 'diwali-15', world: 'diwali', title: 'Maroon Crop Top, White Stole', ref: 'DIWALI-REF-15',
    referenceNumber: 15,
    pose: 'both standing very close in a garden, she facing slightly toward him, he leaning downward toward her, a white stole positioned between them with their hands interacting around the stole and waist area, playful styling moment', poseDescription: 'both standing very close in a garden, she facing slightly toward him, he leaning downward toward her, a white stole positioned between them with their hands interacting around the stole and waist area, playful styling moment',
    framing: 'vertical medium to full-body photograph', framingDescription: 'vertical medium to full-body photograph',
    setting: 'garden terrace with plants and a modern concrete wall', environmentDescription: 'garden terrace with plants and a modern concrete wall', light: 'daylight',
    her: H('Lehenga', 'Maroon', 'Cotton', 'oxidised silver embellishment', 'deep maroon crop top with a matching long skirt, white and silver geometric embellishments, oxidised silver jewellery, large silver earrings, heavy silver bangles, bare midriff'),
    him: H('Printed Ethnic Shirt', 'Maroon', 'Cotton', 'traditional print with white stole', 'red maroon printed shirt with a dense traditional print, black loose wide trousers and a long white scarf draped around his neck'),
    outfitDescription: "Maroon crop top and skirt with silver embellishments; maroon printed shirt with white stole", qaStatus: 'GENERATED',
    tone: 'Oxidised Silver', colourStory: 'Maroon · White', tags: ['garden','stole'] },
  { id: 'diwali-16', world: 'diwali', title: 'Maroon Dress, Lavender Kurta', ref: 'DIWALI-REF-16',
    referenceNumber: 16,
    pose: 'both standing and walking together, she on the right and he on the left, he looking toward her, she laughing with one hand raised near her face, natural walking conversation energy with visible space between their bodies', poseDescription: 'both standing and walking together, she on the right and he on the left, he looking toward her, she laughing with one hand raised near her face, natural walking conversation energy with visible space between their bodies',
    framing: 'vertical portrait', framingDescription: 'vertical portrait',
    setting: 'ornate upscale interior with a carved golden decorative wall', environmentDescription: 'ornate upscale interior with a carved golden decorative wall', light: 'warm yellow indoor lighting',
    her: H('Lehenga', 'Wine', 'Georgette', 'soft pink dupatta', 'deep maroon long flowing ethnic dress with a soft pink sheer dupatta, elegant simple jewellery'),
    him: H('Modern Kurta', 'Purple', 'Cotton', 'solid', 'soft lavender kurta with a straight simple silhouette'),
    outfitDescription: "Maroon dress with soft pink dupatta; lavender kurta", qaStatus: 'GENERATED',
    tone: 'Gold', colourStory: 'Maroon · Lavender', tags: ['walking','interior'] },
  { id: 'diwali-17', world: 'diwali', title: 'She Fixes His Hair, Navy Dupatta', ref: 'DIWALI-REF-17',
    referenceNumber: 17,
    pose: 'she faces him and lifts both hands toward his face and head, adjusting his hair and collar area, he stands straight looking toward her, close personal interaction', poseDescription: 'she faces him and lifts both hands toward his face and head, adjusting his hair and collar area, he stands straight looking toward her, close personal interaction',
    framing: 'vertical three-quarter to full-body', framingDescription: 'vertical three-quarter to full-body',
    setting: 'outdoor residential or college style environment with green plants behind', environmentDescription: 'outdoor residential or college style environment with green plants behind', light: 'bright daytime',
    her: H('Kurta Sets', 'Ivory', 'Cotton', 'navy dupatta', 'white ethnic outfit with a deep navy blue dupatta with a blue embroidered border, traditional silver earrings, simple white lower'),
    him: H('Modern Kurta', 'Cream', 'Cotton', 'embroidered', 'cream embroidered kurta with a white lower garment, wristwatch'),
    outfitDescription: "White outfit with navy embroidered dupatta; cream embroidered kurta", qaStatus: 'GENERATED',
    tone: 'Silver', colourStory: 'White · Navy', tags: ['interaction','daytime'] },
  { id: 'diwali-18', world: 'diwali', title: 'Purple Suit in the Stairwell', ref: 'DIWALI-REF-18',
    referenceNumber: 18,
    pose: 'both seated on a staircase, he on the left leaning forward with one hand covering part of his face, she on the right seated upright touching and adjusting her hair, casual slightly awkward youthful pose, neither looking at the camera', poseDescription: 'both seated on a staircase, he on the left leaning forward with one hand covering part of his face, she on the right seated upright touching and adjusting her hair, casual slightly awkward youthful pose, neither looking at the camera',
    framing: 'vertical portrait', framingDescription: 'vertical portrait',
    setting: 'indoor stairwell with a white wall and the staircase rising behind', environmentDescription: 'indoor stairwell with a white wall and the staircase rising behind', light: 'cool indoor lighting',
    her: H('Kurta Sets', 'Purple', 'Cotton', 'embroidered neckline', 'deep purple ethnic suit with a long straight kurta, a detailed embroidered neckline and front panel, a matching purple dupatta, long sleeves, minimal jewellery'),
    him: H('Festive Separates', 'White', 'Cotton', 'long-sleeve top with dark jeans', 'plain white long-sleeve t-shirt with dark charcoal jeans, white sneakers, wristwatch'),
    outfitDescription: "Deep purple embroidered suit with dupatta; white tee with charcoal jeans", qaStatus: 'GENERATED',
    tone: 'Silver', colourStory: 'Purple · White', tags: ['seated','stairwell'] },
  { id: 'diwali-19', world: 'diwali', title: 'Blush Lehenga in the Heritage Arch', ref: 'DIWALI-REF-19',
    referenceNumber: 19,
    pose: 'standing a few feet apart inside a grand heritage arch, she on the left partially lifting one hand to her face, he on the right standing upright with relaxed arms, both looking generally toward each other or to the side rather than at the camera, strong negative space between them', poseDescription: 'standing a few feet apart inside a grand heritage arch, she on the left partially lifting one hand to her face, he on the right standing upright with relaxed arms, both looking generally toward each other or to the side rather than at the camera, strong negative space between them',
    framing: 'vertical architectural composition with the archway a major part of the image', framingDescription: 'vertical architectural composition with the archway a major part of the image',
    setting: 'huge ornate Mughal and Rajasthani style archway with carved walls and a pink doorway far behind', environmentDescription: 'huge ornate Mughal and Rajasthani style archway with carved walls and a pink doorway far behind', light: 'warm daylight',
    her: H('Anarkali', 'Rani Pink', 'Georgette', 'embroidered upper with dupatta', 'soft blush dusty pink lehenga style anarkali with an intricately embellished upper portion, a flowing dupatta, traditional festive jewellery'),
    him: H('Modern Kurta', 'White', 'Cotton', 'minimal embroidery', 'pure white kurta pajama with minimal embroidery, white footwear'),
    outfitDescription: "Blush pink embellished anarkali with dupatta; white kurta pajama", qaStatus: 'GENERATED',
    tone: 'Gold', colourStory: 'Blush · White', tags: ['archway','heritage'] },
  { id: 'diwali-20', world: 'diwali', title: 'Maroon Kurta, Balcony Crop', ref: 'DIWALI-REF-20',
    referenceNumber: 20,
    pose: 'standing side by side, he on the right with both arms crossed, she on the left with one hand around her waist, bodies close together, casual relaxed upper-body pose', poseDescription: 'standing side by side, he on the right with both arms crossed, she on the left with one hand around her waist, bodies close together, casual relaxed upper-body pose',
    framing: 'horizontal cropped composition from below the shoulders to the waist, not a full-body shot', framingDescription: 'horizontal cropped composition from below the shoulders to the waist, not a full-body shot',
    setting: 'night balcony terrace with a railing behind', environmentDescription: 'night balcony terrace with a railing behind', light: 'warm outdoor evening light',
    her: H('Kurta Sets', 'Maroon', 'Cotton', 'subtle embroidery', 'deep maroon ethnic kurta suit with subtle traditional embroidery and a long straight silhouette, minimal jewellery'),
    him: H('Modern Kurta', 'White', 'Cotton', 'embroidered', 'white embroidered kurta with white pajama trousers, arms crossed'),
    outfitDescription: "Maroon embroidered kurta suit; white embroidered kurta pajama", qaStatus: 'GENERATED',
    tone: 'Silver', colourStory: 'Maroon · White', tags: ['balcony','cropped'] },

  // ───────────── FESTIVE PARTY (priority 4) ─────────────
  { id: 'festive-party-01', world: 'festive-party', title: 'Black Sequin Party Mirror Selfie', ref: 'REF-C1', pose: 'mirror selfie', framing: '3/4 mirror', setting: 'party venue washroom mirror', light: 'moody',
    her: H('Saree', 'Black', 'Georgette', 'sequin', 'black sequin saree'), him: H('Modern Kurta', 'Black', 'Georgette', 'mirror sequin', 'black mirror-sequin kurta'), tone: 'Silver', colourStory: 'Black-on-black', tags: ['mirror-selfie'] },
  { id: 'festive-party-02', world: 'festive-party', title: 'Rooftop Overhead in Emerald', ref: 'REF-C2', pose: 'overhead lying', framing: 'overhead', setting: 'rooftop lounge', light: 'dusk',
    her: H('Lehenga', 'Emerald', 'Velvet', 'sequin', 'emerald velvet lehenga'), him: H('Festive Jacket', 'Black', 'Velvet', 'solid', 'black velvet jacket'), tone: 'Gold', colourStory: 'Emerald · Black', tags: ['overhead'] },
  { id: 'festive-party-03', world: 'festive-party', title: 'Staircase Sit', ref: 'REF-C3', pose: 'seated on staircase', framing: 'full seated', setting: 'wooden staircase', light: 'warm',
    her: H('Sharara', 'Wine', 'Georgette', 'sequin', 'wine sequin sharara'), him: H('Modern Kurta', 'Cream', 'Cotton Silk', 'solid', 'cream kurta'), tone: 'Gold', colourStory: 'Wine · Cream', tags: ['seated'] },
  { id: 'festive-party-04', world: 'festive-party', title: 'Red Jacket Laugh', ref: 'REF-C2 side panel', pose: 'face-cup laugh', framing: 'waist-up', setting: 'party lights', light: 'night',
    her: H('Pre-Draped Saree', 'Black', 'Satin', 'solid', 'black satin pre-draped saree'), him: H('Festive Jacket', 'Red', 'Brocade', 'brocade', 'red brocade jacket over black'), tone: 'Silver', colourStory: 'Black · Red brocade', tags: ['candid'] },
  { id: 'festive-party-05', world: 'festive-party', title: 'Lounge Hand-Hold Crop', ref: 'REF-C1 side panel', pose: 'hand-hold crop', framing: 'detail crop', setting: 'lounge', light: 'warm',
    her: H('Lehenga', 'Silver', 'Tissue', 'sequin', 'silver tissue lehenga'), him: H('Modern Kurta', 'Navy', 'Silk Blend', 'solid', 'navy kurta'), tone: 'Silver', colourStory: 'Silver · Navy', tags: ['hand-hold'] },
  { id: 'festive-party-06', world: 'festive-party', title: 'Bar Counter Shoulder Line', ref: 'REF-C1 side panel', pose: 'shoulder to shoulder', framing: 'nose-to-knee', setting: 'party bar counter', light: 'moody',
    her: H('Anarkali', 'Black', 'Georgette', 'gold', 'black anarkali with gold'), him: H('Embroidered Ethnic Shirt', 'Ivory', 'Silk Blend', 'tonal', 'ivory embroidered shirt'), tone: 'Gold', colourStory: 'Black · Ivory', tags: ['outfit-check'] },
  { id: 'festive-party-07', world: 'festive-party', title: 'Corridor Walk-Out', ref: 'REF-S1 panel 2', pose: 'walking away', framing: 'back view', setting: 'hotel corridor', light: 'warm',
    her: H('Saree', 'Emerald', 'Satin', 'solid', 'emerald satin saree'), him: H('Festive Kurta Set', 'Black', 'Cotton Silk', 'solid', 'black kurta set'), tone: 'Gold', colourStory: 'Emerald · Black', tags: ['walking'] },
  { id: 'festive-party-08', world: 'festive-party', title: 'Earring Fix', ref: 'REF-S1 panel 6', pose: 'he helps fix her earring', framing: 'waist-up', setting: 'party hallway', light: 'warm',
    her: H('Sharara', 'Black', 'Georgette', 'mirror', 'black mirror sharara'), him: H('Printed Ethnic Shirt', 'Teal', 'Rayon', 'paisley', 'teal printed shirt'), tone: 'Silver', colourStory: 'Black · Teal', tags: ['candid'] },
  { id: 'festive-party-09', world: 'festive-party', title: 'Dance Floor Spin', ref: 'REF-S2 panel 16', pose: 'spin on dance floor', framing: 'full body', setting: 'dance floor', light: 'party lights',
    her: H('Lehenga', 'Wine', 'Velvet', 'sequin', 'wine velvet lehenga'), him: H('Modern Kurta', 'Black', 'Cotton', 'solid', 'black kurta'), tone: 'Gold', colourStory: 'Wine · Black', tags: ['twirl'] },
  { id: 'festive-party-10', world: 'festive-party', title: 'Flash Selfie', ref: 'REF-S2 panel 11', pose: 'flash selfie', framing: 'head-and-shoulders', setting: 'party', light: 'flash',
    her: H('Pre-Draped Saree', 'Silver', 'Georgette', 'sequin', 'silver sequin pre-draped saree'), him: H('Embroidered Ethnic Shirt', 'Black', 'Cotton', 'sequin dots', 'black sequin-dot shirt'), tone: 'Silver', colourStory: 'Silver · Black', tags: ['selfie'] },
  { id: 'festive-party-11', world: 'festive-party', title: 'Couch Laugh', ref: 'REF-S2 panel 20', pose: 'seated laughing', framing: 'full seated', setting: 'house party couch', light: 'lamp',
    her: H('Kurta Sets', 'Emerald', 'Silk Blend', 'sequin', 'emerald kurta set'), him: H('Modern Kurta', 'Ivory', 'Cotton', 'solid', 'ivory kurta'), tone: 'Gold', colourStory: 'Emerald · Ivory', tags: ['seated'] },
  { id: 'festive-party-12', world: 'festive-party', title: 'Terrace Embrace', ref: 'REF-S2 panel 13', pose: 'embrace', framing: 'waist-up', setting: 'terrace lights', light: 'night',
    her: H('Gharara', 'Black', 'Georgette', 'gold', 'black gold gharara'), him: H('Festive Jacket', 'Ivory', 'Silk Blend', 'subtle embroidery', 'ivory jacket'), tone: 'Gold', colourStory: 'Black · Ivory', tags: ['embrace'] },
  { id: 'festive-party-13', world: 'festive-party', title: 'Gold Lift Mirror', ref: 'REF-S2 panel 14', pose: 'lift mirror selfie', framing: 'mirror full', setting: 'brass lift', light: 'warm',
    her: H('Saree', 'Gold', 'Tissue', 'zari', 'gold tissue saree'), him: H('Modern Kurta', 'Black', 'Cotton Silk', 'solid', 'black kurta'), tone: 'Gold', colourStory: 'Gold · Black', tags: ['mirror-selfie'] },
  { id: 'festive-party-14', world: 'festive-party', title: 'Poolside Bench', ref: 'REF-S2 panel 15', pose: 'bench whisper', framing: 'full seated', setting: 'poolside bench', light: 'night',
    her: H('Anarkali', 'Navy', 'Georgette', 'sequin', 'navy sequin anarkali'), him: H('Ethnic Shirt', 'White', 'Linen', 'solid', 'white linen ethnic shirt'), tone: 'Silver', colourStory: 'Navy · White', tags: ['seated'] },
  { id: 'festive-party-15', world: 'festive-party', title: 'Two-Hand Spin', ref: 'REF-S2 panel 16', pose: 'two-hand spin', framing: 'full body', setting: 'banquet lawn', light: 'fairy',
    her: H('Lehenga', 'Rani Pink', 'Georgette', 'sequin', 'rani pink sequin lehenga'), him: H('Festive Kurta Set', 'Ivory', 'Cotton Silk', 'solid', 'ivory kurta set'), tone: 'Gold', colourStory: 'Rani pink · Ivory', tags: ['twirl'] },
  { id: 'festive-party-16', world: 'festive-party', title: 'Entrance Side Hug', ref: 'REF-S2 panel 17', pose: 'side hug', framing: '3/4', setting: 'venue entrance', light: 'night',
    her: H('Sharara', 'Emerald', 'Georgette', 'sequin', 'emerald sequin sharara'), him: H('Modern Kurta', 'Black', 'Cotton', 'solid', 'black kurta'), tone: 'Gold', colourStory: 'Emerald · Black', tags: ['hug'] },
  { id: 'festive-party-17', world: 'festive-party', title: 'Lawn Twirl Watch', ref: 'REF-S2 panel 18', pose: 'twirl watch', framing: 'full body', setting: 'party lawn', light: 'dusk',
    her: H('Lehenga', 'Black', 'Georgette', 'sequin', 'black sequin lehenga'), him: H('Embroidered Ethnic Shirt', 'Ivory', 'Silk Blend', 'tonal', 'ivory embroidered shirt'), tone: 'Silver', colourStory: 'Black · Ivory', tags: ['twirl'] },
  { id: 'festive-party-18', world: 'festive-party', title: 'Arrival Walk', ref: 'REF-S1 panel 4', pose: 'walking toward camera', framing: 'full body', setting: 'venue driveway', light: 'night',
    her: H('Pre-Draped Saree', 'Wine', 'Satin', 'solid', 'wine satin pre-draped saree'), him: H('Festive Jacket', 'Navy', 'Silk Blend', 'solid', 'navy jacket'), tone: 'Gold', colourStory: 'Wine · Navy', tags: ['walking'] },
  { id: 'festive-party-19', world: 'festive-party', title: 'Candlelit Forehead Touch', ref: 'REF-S1 panel 6', pose: 'forehead touch', framing: 'waist-up', setting: 'candle-lit table', light: 'candle',
    her: H('Saree', 'Wine', 'Georgette', 'sequin', 'wine sequin saree'), him: H('Modern Kurta', 'Black', 'Georgette', 'mirror sequin', 'black sequin kurta'), tone: 'Silver', colourStory: 'Wine · Black', tags: ['close'] },
  { id: 'festive-party-20', world: 'festive-party', title: 'Rooftop Rug Overhead', ref: 'REF-C2', pose: 'overhead lying on rug', framing: 'overhead', setting: 'rooftop rug', light: 'dusk',
    her: H('Lehenga', 'Silver', 'Georgette', 'mirror', 'silver mirror lehenga'), him: H('Printed Ethnic Shirt', 'Black', 'Rayon', 'block print', 'black printed shirt'), tone: 'Silver', colourStory: 'Silver · Black', tags: ['overhead'] },

  // ───────────── TRADITIONAL (priority 5) ─────────────
  { id: 'traditional-01', world: 'traditional', title: 'Temple Town Mirror Selfie', ref: 'REF-C1', pose: 'mirror selfie', framing: '3/4 mirror', setting: 'old haveli mirror', light: 'window',
    her: H('Saree', 'Mustard', 'Silk', 'temple border', 'mustard silk saree with temple border'), him: H('Festive Kurta Set', 'Ivory', 'Cotton Silk', 'solid', 'ivory kurta set'), tone: 'Gold', colourStory: 'Mustard · Ivory', tags: ['mirror-selfie'] },
  { id: 'traditional-02', world: 'traditional', title: 'Haveli Floor Overhead', ref: 'REF-C2', pose: 'overhead lying', framing: 'overhead', setting: 'patterned haveli floor', light: 'sun',
    her: H('Lehenga', 'Maroon', 'Silk', 'bandhani', 'maroon bandhani silk lehenga'), him: H('Modern Kurta', 'Cream', 'Cotton', 'solid', 'cream kurta'), tone: 'Gold', colourStory: 'Maroon · Cream', tags: ['overhead'] },
  { id: 'traditional-03', world: 'traditional', title: 'Ghat Steps', ref: 'REF-C3', pose: 'seated on ghat steps', framing: 'full seated', setting: 'river ghat', light: 'golden hour',
    her: H('Saree', 'Red', 'Cotton', 'contrast border', 'red cotton saree with white border'), him: H('Modern Kurta', 'White', 'Cotton', 'solid', 'white kurta'), tone: 'Gold', colourStory: 'Red · White', tags: ['seated'] },
  { id: 'traditional-04', world: 'traditional', title: 'Courtyard Laugh', ref: 'REF-C2 side panel', pose: 'face-cup laugh', framing: 'waist-up', setting: 'courtyard', light: 'day',
    her: H('Anarkali', 'Teal', 'Cotton', 'block print', 'teal block-print anarkali'), him: H('Festive Kurta Set', 'Beige', 'Linen', 'solid', 'beige kurta set'), tone: 'Oxidised Silver', colourStory: 'Teal · Beige', tags: ['candid'] },
  { id: 'traditional-05', world: 'traditional', title: 'Temple Door Hand-Hold', ref: 'REF-C1 side panel', pose: 'hand-hold crop', framing: 'detail crop', setting: 'temple door', light: 'day',
    her: H('Saree', 'Emerald', 'Silk', 'zari', 'emerald silk saree'), him: H('Festive Kurta Set', 'Cream', 'Cotton Silk', 'solid', 'cream kurta set'), tone: 'Gold', colourStory: 'Emerald · Cream', tags: ['hand-hold'] },
  { id: 'traditional-06', world: 'traditional', title: 'Jharokha Shoulder Line', ref: 'REF-C1 side panel', pose: 'shoulder to shoulder', framing: 'nose-to-knee', setting: 'jharokha window', light: 'window',
    her: H('Kurta Sets', 'Indigo', 'Cotton', 'block print', 'indigo block-print kurta set'), him: H('Modern Kurta', 'White', 'Cotton', 'solid', 'white kurta'), tone: 'Oxidised Silver', colourStory: 'Indigo · White', tags: ['outfit-check'] },
  { id: 'traditional-07', world: 'traditional', title: 'Fort Lane Walk', ref: 'REF-S1 panel 2', pose: 'walking away', framing: 'back view', setting: 'fort lane', light: 'afternoon',
    her: H('Lehenga', 'Mustard', 'Cotton', 'bandhani', 'mustard bandhani lehenga'), him: H('Modern Kurta', 'Maroon', 'Cotton', 'solid', 'maroon kurta'), tone: 'Oxidised Silver', colourStory: 'Mustard · Maroon', tags: ['walking'] },
  { id: 'traditional-08', world: 'traditional', title: 'Pallu Fix at the Temple', ref: 'REF-S1 panel 6', pose: 'he adjusts her pallu', framing: 'waist-up', setting: 'temple corridor', light: 'soft',
    her: H('Saree', 'Ivory', 'Cotton', 'gold border', 'ivory kasavu-style saree with gold border'), him: H('Modern Kurta', 'Ivory', 'Cotton', 'solid', 'ivory kurta'), tone: 'Gold', colourStory: 'Ivory · Gold', tags: ['dupatta-adjust'] },
  { id: 'traditional-09', world: 'traditional', title: 'Courtyard Spin', ref: 'REF-S2 panel 16', pose: 'twirl', framing: 'full body', setting: 'haveli courtyard', light: 'day',
    her: H('Anarkali', 'Red', 'Cotton', 'gota', 'red gota anarkali'), him: H('Festive Kurta Set', 'Ivory', 'Cotton', 'solid', 'ivory kurta set'), tone: 'Gold', colourStory: 'Red · Ivory', tags: ['twirl'] },
  { id: 'traditional-10', world: 'traditional', title: 'Temple Selfie', ref: 'REF-S2 panel 11', pose: 'selfie', framing: 'head-and-shoulders', setting: 'temple steps', light: 'day',
    her: H('Saree', 'Rani Pink', 'Silk', 'temple border', 'rani pink silk saree'), him: H('Modern Kurta', 'Mustard', 'Cotton', 'solid', 'mustard kurta'), tone: 'Gold', colourStory: 'Rani pink · Mustard', tags: ['selfie'] },
  { id: 'traditional-11', world: 'traditional', title: 'Jhoola Laugh', ref: 'REF-S2 panel 20', pose: 'seated on jhoola laughing', framing: 'full seated', setting: 'wooden jhoola', light: 'day',
    her: H('Lehenga', 'Green', 'Cotton', 'block print', 'green block-print lehenga'), him: H('Modern Kurta', 'Cream', 'Linen', 'solid', 'cream kurta'), tone: 'Oxidised Silver', colourStory: 'Green · Cream', tags: ['seated'] },
  { id: 'traditional-12', world: 'traditional', title: 'Archway Embrace', ref: 'REF-S2 panel 13', pose: 'embrace', framing: 'waist-up', setting: 'stone archway', light: 'dusk',
    her: H('Saree', 'Maroon', 'Silk', 'zari', 'maroon silk saree'), him: H('Festive Kurta Set', 'Ivory', 'Cotton Silk', 'solid', 'ivory kurta set'), tone: 'Gold', colourStory: 'Maroon · Ivory', tags: ['embrace'] },
  { id: 'traditional-13', world: 'traditional', title: 'Heirloom Mirror', ref: 'REF-S2 panel 14', pose: 'mirror selfie', framing: 'mirror full', setting: 'carved mirror', light: 'warm',
    her: H('Pre-Draped Saree', 'Mustard', 'Silk Blend', 'zari', 'mustard pre-draped saree'), him: H('Modern Kurta', 'Green', 'Cotton', 'solid', 'green kurta'), tone: 'Gold', colourStory: 'Mustard · Green', tags: ['mirror-selfie'] },
  { id: 'traditional-14', world: 'traditional', title: 'Stone Bench', ref: 'REF-S2 panel 15', pose: 'bench seated', framing: 'full seated', setting: 'stone bench', light: 'evening',
    her: H('Kurta Sets', 'Maroon', 'Cotton', 'gota', 'maroon kurta set'), him: H('Festive Kurta Set', 'Beige', 'Linen', 'solid', 'beige kurta set'), tone: 'Gold', colourStory: 'Maroon · Beige', tags: ['seated'] },
  { id: 'traditional-15', world: 'traditional', title: 'Hand Spin Courtyard', ref: 'REF-S2 panel 16', pose: 'two-hand spin', framing: 'full body', setting: 'courtyard', light: 'day',
    her: H('Lehenga', 'Royal Blue', 'Silk', 'bandhani', 'royal blue bandhani lehenga'), him: H('Modern Kurta', 'White', 'Cotton', 'solid', 'white kurta'), tone: 'Oxidised Silver', colourStory: 'Royal blue · White', tags: ['twirl'] },
  { id: 'traditional-16', world: 'traditional', title: 'Gate Side Hug', ref: 'REF-S2 panel 17', pose: 'side hug', framing: '3/4', setting: 'old gate', light: 'day',
    her: H('Anarkali', 'Mustard', 'Cotton', 'block print', 'mustard anarkali'), him: H('Modern Kurta', 'Indigo', 'Cotton', 'block print', 'indigo kurta'), tone: 'Oxidised Silver', colourStory: 'Mustard · Indigo', tags: ['hug'] },
  { id: 'traditional-17', world: 'traditional', title: 'Temple Twirl Watch', ref: 'REF-S2 panel 18', pose: 'twirl watch', framing: 'full body', setting: 'temple lawn', light: 'dusk',
    her: H('Lehenga', 'Red', 'Cotton', 'bandhani', 'red bandhani lehenga'), him: H('Modern Kurta', 'Cream', 'Cotton', 'solid', 'cream kurta'), tone: 'Oxidised Silver', colourStory: 'Red · Cream', tags: ['twirl'] },
  { id: 'traditional-18', world: 'traditional', title: 'Bazaar Walk', ref: 'REF-S1 panel 4', pose: 'walking toward camera', framing: 'full body', setting: 'old bazaar', light: 'day',
    her: H('Saree', 'Green', 'Cotton', 'contrast border', 'green cotton saree'), him: H('Modern Kurta', 'White', 'Cotton', 'solid', 'white kurta'), tone: 'Gold', colourStory: 'Green · White', tags: ['walking'] },
  { id: 'traditional-19', world: 'traditional', title: 'Aarti Forehead Touch', ref: 'REF-S1 panel 6', pose: 'forehead touch', framing: 'waist-up', setting: 'temple lamps', light: 'lamp',
    her: H('Saree', 'Red', 'Silk', 'zari', 'red silk saree'), him: H('Modern Kurta', 'Ivory', 'Cotton Silk', 'solid', 'ivory kurta'), tone: 'Gold', colourStory: 'Red · Ivory', tags: ['close'] },
  { id: 'traditional-20', world: 'traditional', title: 'Courtyard Overhead', ref: 'REF-C2', pose: 'overhead lying', framing: 'overhead', setting: 'courtyard tiles', light: 'sun',
    her: H('Lehenga', 'Ivory', 'Cotton', 'block print', 'ivory block-print lehenga'), him: H('Modern Kurta', 'Maroon', 'Cotton', 'solid', 'maroon kurta'), tone: 'Oxidised Silver', colourStory: 'Ivory · Maroon', tags: ['overhead'] },
];
